### ISSUE TITLE
jgrapht version and jdk version

### ISSUE THREAD

**Issue by jiluhu** [jgrapht/jgrapht#1009]
```
 * JGraphT version:
 * Java version (java -version)/platform:  
```

**Issue**
jgrapht-1.5.0       jdk 11, not support jdk 1.8
1.4.0                   jdk  1.8

**Steps to reproduce (small coding example)**

**Expected behaviour**

**Other information**

**Comment by jkinable** [comment]
I'm not sure I understand the issue? jgrapht-1.5.0 requires jdk 11, that is, you cannot use jgrapht-1.5.0 with jdk 1.8. See [readme.me ](https://github.com/jgrapht/jgrapht/blob/master/README.md) for details.

**Comment by jiluhu** [comment]
> I'm not sure I understand the issue? jgrapht-1.5.0 requires jdk 11, that is, you cannot use jgrapht-1.5.0 with jdk 1.8. See [readme.me ](https://github.com/jgrapht/jgrapht/blob/master/README.md) for details.

When i use the Jgrapht ,I don't find the Jgrapht of jdk1.8. I don't konw use which version Jgrapht in jdk 1.8. 
Maybe you can add a description of the corresponding relationship between JDK version and other version JGrapht.

**Comment by jiluhu** [comment]
> I'm not sure I understand the issue? jgrapht-1.5.0 requires jdk 11, that is, you cannot use jgrapht-1.5.0 with jdk 1.8. See [readme.me ](https://github.com/jgrapht/jgrapht/blob/master/README.md) for details.

When i use the Jgrapht ,I don't find the Jgrapht of jdk1.8. I don't konw use which version Jgrapht in jdk 1.8. 
Maybe you can add a description of the corresponding relationship between JDK version and other version JGrapht.

**Comment by jkinable** [comment]
JGraphT version 1.0.0 is the first release that requires java 1.8. The last version of JGraphT that supports java 1.8 is version 1.4.0. Starting from JGraphT version 1.5.0, java 11 is required. This information can be found in [HISTORY.md](https://github.com/jgrapht/jgrapht/blob/master/HISTORY.md). I agree that we should probably make this a little easier to find.
If you need to use Java 1.8, then I recommend using JGrapht 1.4.0.
