### ISSUE TITLE
Weighted PageRank retrieving incoming neighbours for each iteration

### ISSUE THREAD

**Issue by FlorentinD** [jgrapht/jgrapht#1011]
See:
https://github.com/jgrapht/jgrapht/blob/ccd78f3efd8646160b0388b037bc11fa827bc3dc/jgrapht-core/src/main/java/org/jgrapht/alg/scoring/PageRank.java#L326

As part of my master thesis, I am currently running some benchmarks including PageRank and stumbled across the weighted version being much slower than the unweighted (f.i. `150ms` to `1101ms`).
I assume the edge access might be the reason. The fix could be, creating the adjacency-list not only in the unweighted case and also use it in the weighted version.

**Comment by d-michail** [comment]
Yes, indeed. I optimized the unweighted case at some point as I was conducting experiments, but never optimized the weighted case. Feel free to do optimizations and submit a PR.

**Comment by FlorentinD** [comment]
Thank you for clarifying. I will submit a PR after my thesis, e.g., mid of January.
