### ISSUE TITLE
AlphaCentrality is not really computing eigenvector centrality

### ISSUE THREAD

**Issue by vigna** [jgrapht/jgrapht#1013]
```
 * JGraphT version: 1.5.0
 * Java version (java -version)/platform:  
```

**Issue**

AlphaCentrality is not really computing eigenvector centrality. 

**Steps to reproduce (small coding example)**

Consider these three tests, which try to use AlphaCentrality to compute the eigenvector centrality of a 3-clique:

```
    @Test
	public void testGraph4() {
		final DirectedPseudograph<String, DefaultEdge> g = new DirectedPseudograph<>(DefaultEdge.class);

		g.addVertex("A");
		g.addVertex("B");
		g.addVertex("C");

		g.addEdge("A", "B");
		g.addEdge("B", "A");
		g.addEdge("B", "C");
		g.addEdge("C", "B");
		g.addEdge("A", "C");
		g.addEdge("C", "A");

		final VertexScoringAlgorithm<String, Double> pr = new AlphaCentrality<>(g, 0.49, 0, Integer.MAX_VALUE, Double.MIN_VALUE);
		System.err.println(pr.getScores());
	}

	@Test
	public void testGraph5() {
		final DirectedPseudograph<String, DefaultEdge> g = new DirectedPseudograph<>(DefaultEdge.class);

		g.addVertex("A");
		g.addVertex("B");
		g.addVertex("C");

		g.addEdge("A", "B");
		g.addEdge("B", "A");
		g.addEdge("B", "C");
		g.addEdge("C", "B");
		g.addEdge("A", "C");
		g.addEdge("C", "A");

		final VertexScoringAlgorithm<String, Double> pr = new AlphaCentrality<>(g, 0.50, 0, Integer.MAX_VALUE, Double.MIN_VALUE);
		System.err.println(pr.getScores());
	}

	@Test
	public void testGraph6() {
		final DirectedPseudograph<String, DefaultEdge> g = new DirectedPseudograph<>(DefaultEdge.class);

		g.addVertex("A");
		g.addVertex("B");
		g.addVertex("C");

		g.addEdge("A", "B");
		g.addEdge("B", "A");
		g.addEdge("B", "C");
		g.addEdge("C", "B");
		g.addEdge("A", "C");
		g.addEdge("C", "A");

		final VertexScoringAlgorithm<String, Double> pr = new AlphaCentrality<>(g, 0.51, 0, Integer.MAX_VALUE, Double.MIN_VALUE);
		System.err.println(pr.getScores());
	}
```

The first test outputs <0,0,0> (more precisely, <2.37E-322,2.37E-322,2.37E-322>). The second test emits <1/3,1/3,1/3> (the correct value). The third test emits <inf, inf, inf>.

This is unavoidable. 

When there is no external source of rank, the algorithm implemented by this class has no counterpart in the literature.
When the "damping factor" is exactly identical to the inverse of the spectral radius of the matrix, AlphaCentrality will compute the dominant eigenvector (central test) using, essentially, the power method. Unless the inverse of the spectral radius can be exactly represented in floating point (i.e., it is a dyadic), this will never happen (it happens in this case because the spectral radius is 2). When the "damping factor" is smaller, the result of the computation will be always zero. When it is larger, the result will always be infinity. Intermediate results obtained by stopping the iteration prematurely or using a low threshold may be of interest, but they have nothing to do with eigenvector centrality, which is defined as the (left, usually) dominant eigenvector of the adjacency matrix.

When there  is an external source of rank, this class compute Katz centrality. "Alpha centrality" is a name invented by Bonacich and LLoyd 50 years after Katz introduced its index (a bit shamelessly), and I must sadly admit that they had some success in making people forget the actual inventor. Most of the literature refers, correctly, to Katz's paper (1953).

I think that a separate EigenvectorCentrality class with minimal modifications (essentially, getting away with the two parameters and renormalizing at each step, thus implementing the power method) would solve the problem (I can put together a pull request if you're interested). A note in the Javadoc referring to Katz centrality in Wikipedia might also help the user understand what is being computed.

One could also amend AlphaCentrality with some conditional code, but, really, spectral centralities with or without damping factor (e.g., Landau vs. Katz) are different beasts and conflating them in the same class will always be a source of confusion for the user.

**Comment by d-michail** [comment]
Feel free to open a PR.  Being explicit about what is actually computed is a good thing, even if there is some code duplication.
