### ISSUE TITLE
BetweennessCentrality may overflow

### ISSUE THREAD

**Issue by vigna** [jgrapht/jgrapht#1014]
```
 * JGraphT version: 1.5.0
 * Java version (java -version)/platform:  
```

**Issue**

Try the following test:

```
    @Test
	public void testOverflow() {
		final Graph<Integer, DefaultEdge> g = new SimpleDirectedGraph<>(DefaultEdge.class);
		for (int i = 0; i < 3300; i++) g.addVertex(i);
		for (int i = 0; i < 3290; i++) for (int j = 0; j < 10; j++) g.addEdge(i, i - i % 10 + 10 + j);
		final VertexScoringAlgorithm<Integer, Double> bc = new BetweennessCentrality<>(g);
		final Map<Integer, Double> scores = bc.getScores();
		System.err.println(scores);
	}
```

All outputs are zeroes or NaN. The issue is that path counters in Brandes's algorithm are superexponential—in fact, the bound O(mn) reported in the Javadoc is incorrect (it was incorrect in Brandes's paper, too) as it does not take into account the time that is necessary to perform computations on numbers that are superexponential in the instance size.

There are two possible fixes: one is to check for overflow every time a counter is updated. The other one is to use BigInteger to represent path counts. Alternatively, one may advise in the Javadoc to check for NaN (albeit I'm not sure you'll always be able to detect overflow this way).

**Comment by d-michail** [comment]
Not sure how to proceed. 

- I guess if we want to check for overflow we could use `Math.addExact` for integers or compare with the maximum value for floating point values. 
- We could also go for an arbitrary precision implementation, but I am under the impression that `BigDecimal` is very slow. 
  Another option is to introduce some other dependency, perhaps `ApFloat` to support this?
- Or we could try to have two separate implementations, one detecting the overflow and the other with arbitrary precision arithmetic.

**Comment by vigna** [comment]
What we do in our class is to use longs and check whether the sum is negative. This is fast and effective, as even Long.MAX_VALUE + Long.MAX_VALUE = Long.MIN_VALUE is negative.

In theory, the range of Long is much smaller than that of Double. On the other hand, Double is very imprecise, and adding small values to a large counter might lead to significant errors. On the other hand, in real-world graphs, we never met a case in which overflow happens.

**Comment by vigna** [comment]
Note that the test above is similar to that done by Math.addExact(), but it's much simpler because we know in advance that the two numbers are nonnegative. Math.addExact() has to perform 4 operations because it has to cover three more cases.

**Comment by d-michail** [comment]
Is it possible to just check for overflow in the integer counts? There is also an update step involving doubles.

**Comment by vigna** [comment]
If you keep the path counts in longs, yes. If you mean the step at line 215, you need simply to cast the two path counts to double and perform the computation, as dependencies are doubles and must be necessarily stored as such. The only update on paths is
```
                    sigma.put(w, sigma.get(w) + sigma.get(v));
```
which is where a check is needed.

**Comment by d-michail** [comment]
I did a quick experiment and I am getting the same results (in the instance you provided) whether I use `BigInteger` or `long` for the counters. Does that mean I have a bug or do we also need to use `BigDecimal`?

**Comment by vigna** [comment]
No, if you use longs and you check the sum you must get an exception. If you can send the example I'll check it. With BigInteger I guess that conversion to double generates a NaN if the integer won't fit a double, and this example is built so that the number of paths exceeds the maximum representable double.

**Comment by vigna** [comment]
Yes, the documentation of BigInteger says the result will be Double.POSITIVE_INFINITY. Once you take the ration, it will be Double.NaN.

**Comment by vigna** [comment]
BTW, I'm just noticing you have also a weighted version. Of course in that case you cannot use longs. Probably you're right—a slow but unbreakable version with BigDecimal would solve the problem.

**Comment by d-michail** [comment]
I have a first implementation in this branch (https://github.com/d-michail/jgrapht/tree/apbetween).  I added a check for the overflow in the default implementation and throw an exception (if the user requests such a behavior from the constructor). 

I also added another implementation using `Apfloat`. Dijkstra remains with double but this should not be a problem. 

The arbitrary precision version runs (on my PC) in around 90 seconds while the `long` version needs 9 secs.

@jsichi How do we feel about adding Apfloat as a dependency? Having an arbitrary precision library would probably be handy in the future. I tried doing this with BigDecimal but the slowdown was too severe. The library has a LGPL license which should not cause any issues.

**Comment by jsichi** [comment]
Sadly, if we add an LGPL-only dependency, then someone using JGraphT under EPL would unable to upgrade to our latest version.  This isn't theoretical for projects under the Eclipse Foundation using JGraphT, since that organization prohibits LGPL dependencies (which was one of our motivations for adding the EPL dual licensing).

I don't know of a solution for this other than asking Apfloat to dual license (or change to a permissive license such as Apache).

**Comment by d-michail** [comment]
Ok, maybe I can refactor to BigDecimal, but I think it is much slower. I try to look whether there are any other good libraries, using more permissive licenses.

**Comment by vigna** [comment]
I think asking the author for double-licensing is worth a try. This thing of bundled jars breaks a bit the logic of the LGPL, so it's not crazy. I mean, we changed ours!

**Comment by vigna** [comment]
I think this might be considered closed, right?
