### ISSUE TITLE
IntVertexDijkstraShortestPath - Reference comparison of boxed numerical values.

### ISSUE THREAD

**Issue by axkr** [jgrapht/jgrapht#1027]
```
 * JGraphT version: 1.5.0
 * Java version (java -version)/platform:  8
```

**Issue**

There seem to be reference comparisons of boxed numerical values (type Integer). This typically works as long as the Integer numbers are in the range of the `java.lang.IntegerCache`. But outside it will probably fail.
- https://github.com/jgrapht/jgrapht/blob/398632f18fc311ba8b8f2b32cf006bceafa5ab58/jgrapht-core/src/main/java/org/jgrapht/alg/shortestpath/IntVertexDijkstraShortestPath.java#L200
- https://github.com/jgrapht/jgrapht/blob/398632f18fc311ba8b8f2b32cf006bceafa5ab58/jgrapht-core/src/main/java/org/jgrapht/alg/shortestpath/IntVertexDijkstraShortestPath.java#L237

Found in lgtm.com
- https://lgtm.com/projects/b/axelclk/symja_android_library/snapshot/97a2343f7d3861f2e27f9fb25166564dbfb67419/files/symja_android_library/matheclipse-external/src/main/java/org/jgrapht/alg/shortestpath/IntVertexDijkstraShortestPath.java?sort=name&dir=ASC&mode=heatmap

**Comment by jsichi** [comment]
@d-michail I think this needs a fix, right?

**Comment by d-michail** [comment]
Yep, I will try to fix this ASAP

**Comment by axkr** [comment]
Here is another one:
- https://github.com/jgrapht/jgrapht/blob/d96256578629698680ee20f74327c5b8f01c568e/jgrapht-core/src/main/java/org/jgrapht/alg/vertexcover/GreedyVCImpl.java#L111
