### ISSUE TITLE
Some classes of org.jgrapht.alg.scoring are msising

### ISSUE THREAD

**Issue by SergiVera** [jgrapht/jgrapht#1046]
Hi everyone,

The list of java classes missing when importing with maven is the following: **EdgeBetweennessCentrality.java**, **EigenvectorCentrality.java**, and **KatzCentrality.java**. Could anybody solve this issue, please? 

Many thanks in advance.

**Comment by d-michail** [comment]
This is probably a problem on your side. But, just to be safe, if someone is going to reproduce this you have to describe your environment more closely.

**Comment by SergiVera** [comment]
Hi Dimitrios,

Thanks for your reply. I have uploaded on my GitHub a simple java project with the necessary maven dependencies, as an example. I don't know why it doesn't work. Everything seems to be imported correctly in the **pom.xml**. Link to the repo: https://github.com/SergiVera/jgrahpt

**Comment by SergiVera** [comment]
Nevertheless, could you or someone else revise if there is an error with the maven dependency? I know it sounds strange what I am saying but I have tried on another computer and happens exactly the same. Thanks in advance.

**Comment by besza** [comment]
Those implementations are available since the current 1.5.1-SNAPSHOT version. 

Javadoc: https://jgrapht.org/javadoc-SNAPSHOT/org.jgrapht.core/org/jgrapht/alg/interfaces/VertexScoringAlgorithm.html
(subject to change)

Please check the project README on how to setup your `pom.xml`.

**Comment by SergiVera** [comment]
Thank you so much, Szabolcs. Now it works with the SNAPSHOT!
