### ISSUE TITLE
DijkstraManyToManyPaths throws NullPointerException in the "reversed" case when no path exists

### ISSUE THREAD

**Issue by delta-peg** [jgrapht/jgrapht#1053]
```
 * JGraphT version: 1.5.1
 * Java version (java -version)/platform:  11
```

**Issue**
Accordin to the javadoc, DijkstraManyToManyShortestPaths.getManyToManyPaths.getPath(source, sink) is supposed to return the shortest path from source to sink _or null if there is no path_.

However, a NullPointerException is thrown if the set of target vertices is larger than the set of source vertices and no path between a given source and a given target vertex exists.

**Steps to reproduce (small coding example)**
        var directedGraph = new DefaultDirectedGraph<String, DefaultEdge>(DefaultEdge.class);
        directedGraph.addVertex("a");
        directedGraph.addVertex("b");
        directedGraph.addVertex("c");
        var dijkstra = new DijkstraManyToManyShortestPaths<>(directedGraph);
        var paths = dijkstra.getManyToManyPaths(Set.of("a"), Set.of("b", "c"));

        paths.getPath("a", "b"); // throws NullPointerException

**Expected behaviour**
paths.getPath("a", "b") returns `null`

**Other information**

**Comment by d-michail** [comment]
Thanks, fixed.
