### ISSUE TITLE
TSPLibImporter crashes on burma14.tsp

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#1060]
```
 * JGraphT version: 1.5.2-snapshot
 * Java version (java -version)/platform:  java 14, Linux Mint
```

**Issue**
Loading the burma14 TSPLib instance results in an exception:
`Exception in thread "main" org.jgrapht.nio.ImportException: Failed to import graph from TSPLIB-file: Unexpected number of elements <10> in line: 1  16.47       96.10`

**Steps to reproduce (small coding example)**
```
Graph<Integer, DefaultWeightedEdge> graph=new SimpleDirectedWeightedGraph<>(SupplierUtil.createIntegerSupplier(), SupplierUtil.createDefaultWeightedEdgeSupplier());
TSPLIBImporter<Integer, DefaultWeightedEdge> importer=new TSPLIBImporter<>();
importer.importGraph(graph, new File(burma14.tsp));
```
where the burma14 instance can be found here: http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/tsp/burma14.tsp.gz

**Other information**
@HannesWell Could you have a look at this?

**Comment by HannesWell** [comment]
The problem in the _burma14_ instance is that multiple spaces are used to delimit the elements of a row, while the `TSPLIBImporter` expects and uses only a single space to split the elements in a row. Therefore more than the expected number of elements is encountered, but many of them are empty.

But this can be fixed easily. I'm just about to prepare a PR.
