### ISSUE TITLE
SuccinctIntDirectedGraphs and incoming edges support

### ISSUE THREAD

**Issue by d-michail** [jgrapht/jgrapht#1061]
```
 * JGraphT version: 1.5.1
 * Java version (java -version)/platform:  11/openjdk
```

**Issue**
While trying to integrate succinct graphs with our python bindings, I encountered a few bugs in class  `SuccinctIntDirectedGraphs` when switching of the incoming edges support.

**Steps to reproduce (small coding example)**

```
    @Test(expected = UnsupportedOperationException.class)
    public void testNoIncomingDirected()
    {
        final DefaultDirectedGraph<Integer, DefaultEdge> d = new DefaultDirectedGraph<>(
            SupplierUtil.createIntegerSupplier(), SupplierUtil.createDefaultEdgeSupplier(), false);
        for (int i = 0; i < 5; i++)
            d.addVertex(i);
        d.addEdge(0, 1);
        d.addEdge(0, 2);
        d.addEdge(1, 2);
        d.addEdge(2, 1);
        d.addEdge(2, 3);
        d.addEdge(3, 0);
        d.addEdge(3, 3);
        d.addEdge(3, 4);
        d.addEdge(4, 1);

        final SuccinctIntDirectedGraph s = new SuccinctIntDirectedGraph(d, false);
        assertEquals(2, s.outDegreeOf(0));
        s.inDegreeOf(0);
    }
```
The example above throws a `NullPointerException` while is should throw an `UnsupportedOperationException`. 

```
    @Test
    public void testNoIncomingDirectedFromList()
    {
        List<Pair<Integer, Integer>> edges = List
            .of(
                Pair.of(0, 1), Pair.of(0, 2), Pair.of(1, 2), Pair.of(2, 1), Pair.of(2, 3),
                Pair.of(3, 0), Pair.of(3, 3), Pair.of(3, 4), Pair.of(4, 1));

        final SuccinctIntDirectedGraph s = new SuccinctIntDirectedGraph(5, edges, false);
        assertEquals(2, s.outDegreeOf(0));
    }
```
The example above fails by throwing an exception that "incoming edges are not supported" while the user has not used any methods with incoming edges. 

```
    @Test(expected = UnsupportedOperationException.class)
    public void testNoIncomingDirectedFromList2()
    {
        List<Pair<Integer, Integer>> edges = List
            .of(
                Pair.of(0, 1), Pair.of(0, 2), Pair.of(1, 2), Pair.of(2, 1), Pair.of(2, 3),
                Pair.of(3, 0), Pair.of(3, 3), Pair.of(3, 4), Pair.of(4, 1));

        final SuccinctIntDirectedGraph s = new SuccinctIntDirectedGraph(5, edges, false);
        assertEquals(2, s.outDegreeOf(0));
        s.inDegreeOf(0);
    }
```
This one currently is ok since it throws the correct exception but at the wrong location (see previous example).

I have not tested the other implementations (class `SuccinctDirectedGraph`) but it is likely that it will have 
the same issues.

**Expected behaviour**

Described in the previous section along with the examples.

**Other information**

**Comment by d-michail** [comment]
@vigna It is possible to have a look at this?

**Comment by vigna** [comment]
For the first example: I've been totally lazy in tracking down every single access to incoming edges. My philosophy is that if you get a NullPointerException, you'll read the documentation a bit better. But that it is easy to fix adding tests where necessary. (Also, each test slows down a bit, and the runtime is already checking for null pointers, but I understand the policy of JGraphT might be different.)

In other two cases, I forgot a flag. At line 174 of SuccinctIntDirectedGraph,
```
        this(
            new SparseIntDirectedGraph(
                numVertices, edges, incomingEdgesSupport ? IncomingEdgesSupport.FULL_INCOMING_EDGES
                    : IncomingEdgesSupport.NO_INCOMING_EDGES));
```
should be
```
        this(
            new SparseIntDirectedGraph(
                numVertices, edges, incomingEdgesSupport ? IncomingEdgesSupport.FULL_INCOMING_EDGES
                    : IncomingEdgesSupport.NO_INCOMING_EDGES),
            incomingEdgesSupport);
```
SuccinctDirectedGraph has the same problem. That was really a stupid slip because a simple constructor test would have detected the problem. When I last-minute introduced the outgoing-only flag I saw green everywhere, but green does not mean you really covered all possible execution paths.

Do you want a PR for this?

**Comment by vigna** [comment]
https://github.com/jgrapht/jgrapht/pull/1063
