### ISSUE TITLE
DefaultEdge equals and hashCode

### ISSUE THREAD

**Issue by asarkar** [jgrapht/jgrapht#1069]
```
 * JGraphT version: 1.5.1
 * Java version (java -version)/platform:  11.
```

**Issue**
DefaultEdge does not override `equals` and `hashCode`. I found an old ticket https://github.com/jgrapht/jgrapht/issues/589 that was closed with the following comment:

> This is expected behavior.
>You're free to use your own custom edge class which overrides equals/hashCode.

User can override `equals` and `hashCode`, but why would they have to? It seems to follow from common sense that two directed unweighted edges would be equal if they have the same source and target. If there's a more involved reason to not do that, it should be explained in the Javadoc, not dismissed as had been done in the ticket above.

**Comment by jkinable** [comment]
How would you distinguish multiple edges between the same pair of vertices in a multigraph? There's also a full wiki page devoted to this subject: https://github.com/jgrapht/jgrapht/wiki/Users%3A-EqualsAndHashCode

**Comment by asarkar** [comment]
> How would you distinguish multiple edges between the same pair of vertices in a multigraph? 

I wouldn't. I think it's not unreasonable to assume that for a multigraph, user would override `equals` and `hashCode` if they want to distinguish. 

I did read the post you referred to, but it didn't answer my question. It emphasizes the need for overriding `equals` and `hashCode`, but doesn't explain the reasoning behind the design choice in `DefaultEdge`.

**Comment by d-michail** [comment]
We support the most general setup where edges have their own identity. It supports all use cases, at the expense of being a bit more complex. 

Another approach is to maintain several different implementations. An example is Guava where they have three different interfaces. 
  - https://guava.dev/releases/22.0/api/docs/com/google/common/graph/Graph.html
  - https://guava.dev/releases/22.0/api/docs/com/google/common/graph/ValueGraph.html
  - https://guava.dev/releases/22.0/api/docs/com/google/common/graph/Network.html

Our interface corresponds to `Network`. Hope this helps.

**Comment by asarkar** [comment]
> We support the most general setup where edges have their own identity. 

I'm not saying it's wrong, but I believe that this choice forces most users to write boilerplate code that could've been avoided. I'm not convinced that this makes sense as the default behavior. 
I'm closing this ticket as we are clearly going in circles. Thank you.
