### ISSUE TITLE
Compute the condensation of a graph

### ISSUE THREAD

**Issue by reprogrammer** [jgrapht/jgrapht#11]
Wikipedia defines the [condensation](http://en.wikipedia.org/wiki/Strongly_connected_component) of a graph G as follows:

> If each strongly connected component is contracted to a single vertex, the resulting graph is a directed acyclic graph, the condensation of G.

Method `StrongConnectivityInspector.stronglyConnectedSets` already computes the set of strongly connected components of a given graph. But, it doesn't provide an efficient way to find out the relationship between the strongly connected components. I suggest that jgrapht provides a way to get the condensation graph. For example, a method called `StrongConnectivityInspector.stronglyConnectedComponents` could return an object of type like `DirectedGraph<DirectedGraph<V, E>, DefaultEdge>`. Such a return value makes each component and the relationship between the components accessible to the user.

**Comment by jkinable** [comment]
A method to compute graph condensations has been added to the library by @d-michail . It will be part of the next release.
