### ISSUE TITLE
Hello, is there a way to directly obtain the shortest path of all points? There are many vertices in the graph, and cyclic acquisition leads to memory overflow.

### ISSUE THREAD

**Issue by qianxkun** [jgrapht/jgrapht#1106]
```
 * JGraphT version:
 * Java version (java -version)/platform:  
```

**Issue**

**Steps to reproduce (small coding example)**

**Expected behaviour**

**Other information**

**Comment by jkinable** [comment]
Please ask this question on https://stackoverflow.com/ (add jgrapht as a question tag). This will allow other people to see and answer your question as well. Also, you want to add more details. I've no idea what 'cyclic acquisitions' are or why they would lead to memory overflows.
