### ISSUE TITLE
How to change the color of vertex and the edge?

### ISSUE THREAD

**Issue by baobao1225** [jgrapht/jgrapht#1109]
```
 * JGraphT version:
 * Java version (java -version)/platform:  
```

**Issue**

**Steps to reproduce (small coding example)**

**Expected behaviour**

**Other information**

**Comment by jkinable** [comment]
Not enough detail to address this issue. If you have specific questions, you want to state what you have done so far, and what doesn't work. Also, unless it's an actual issue/bug, it would be better to ask your question on stackoverflow.com as more people will be able to see and answer your questions.
