### ISSUE TITLE
Please provide iterable-based methods in Graphs

### ISSUE THREAD

**Issue by vigna** [jgrapht/jgrapht#1113]
This is a suggestion for enhancement: presently, Graphs contains methods such as successorListOf() which make it easy for the user to get a list of successors, or predecessors, or neighbors of a vertex. It would be natural if methods such as successorIterableOf() and so on would be available for people using the Iterables interface.

**Comment by syoon2** [comment]
This sounds quite redundant because `java.util.List` is a subinterface of `java.lang.Iterable`.

**Comment by vigna** [comment]
No, it's not, and it has been already implemented by JGraphT. I don't know why this is issue is open, in fact.
