### ISSUE TITLE
how could I run with osmfile

### ISSUE THREAD

**Issue by linxinyaooo** [jgrapht/jgrapht#1122]
hi, 
I have run ShortestPathDemo with random graph, but I want to run it with osm file, what should I do?

**Comment by jsichi** [comment]
This question would be better asked on StackOverflow.

JGraphT provides a number of different importers, but none for domain-specific formats such as .osm.  You can probably find an exporter from .osm to a standard graph format, and then use a corresponding importer into JGraphT.

Maybe CSV:

https://github.com/Tristramg/osm4routing2

It looks like people have written direct conversion into JGraphT as well:

https://github.com/Smythy411/JGraphT-with-OSM-Data

Google is your friend.

**Comment by linxinyaooo** [comment]
> This question would be better asked on StackOverflow.
> 
> JGraphT provides a number of different importers, but none for domain-specific formats such as .osm. You can probably find an exporter from .osm to a standard graph format, and then use a corresponding importer into JGraphT.
> 
> Maybe CSV:
> 
> https://github.com/Tristramg/osm4routing2
> 
> It looks like people have written direct conversion into JGraphT as well:
> 
> https://github.com/Smythy411/JGraphT-with-OSM-Data
> 
> Google is your friend.

thanks for your reply.  I convert osm xml to csv using osm4routing and  run successfully.
