### ISSUE TITLE
Port ZhangShasha algorithm to Java8 compatible version.

### ISSUE THREAD

**Issue by Pramodmk** [jgrapht/jgrapht#1134]
```
 * JGraphT version: 1.5.1
 * Java version (java -version)/platform:  openjdk version "1.8.0_352"
```

**Issue**
I came across [ZhangShasha algorithm impl](https://github.com/jgrapht/jgrapht/blob/jgrapht-1.5.1/jgrapht-core/src/main/java/org/jgrapht/alg/similarity/ZhangShashaTreeEditDistance.java) in 1.5.1 of the JGraphT, but we use Java8. So, the latest version is not helpful since it requires Java11. The request here is to port the ZhangShasha algorithm from 1.5.1 to Java8 compatible branch and release it.

**Steps to reproduce (small coding example)**
NA

**Expected behaviour**
NA

**Other information**

**Comment by jkinable** [comment]
We updated java to version 11 starting with the 1.5.0 release, see https://github.com/jgrapht/jgrapht/blob/master/HISTORY.md
For Java 8, you have to resort to jgrapht 1.4.0 or below. The algorithm you are referencing was added in our 1.5.1 release so won't be available in earlier version. We unfortunately do not backport to older java versions.

**Comment by Pramodmk** [comment]
@jkinable - Thanks for the response!
Why is it not possible to copy the same class with its tests with some minor modifications to 1.4.0 and release tag as 1.4.1? This would also help the community who is still on Java 8 to utilize this algorithm.

**Comment by jkinable** [comment]
We simply don't have the capacity to maintain multiple versions, to backport algorithms to older versions, to update tests, etc. Moreover, we then risk creating new bugs which we would have to patch, etc. JGraphT is ran by volunteers who have limited time and resources, so we are not going to provide updates for older versions.
If you need this algorithm, you can always pull the 1.4 snapshot yourself, include the code you need and compile your own custom package.
