### ISSUE TITLE
Integer comparison should be done with `Integer.equals`

### ISSUE THREAD

**Issue by lgmsantos** [jgrapht/jgrapht#1146]
Offending line:
https://github.com/jgrapht/jgrapht/blob/22fd061572ab22cf8ac6a4b34cf644acfc857dca/jgrapht-opt/src/main/java/org/jgrapht/opt/graph/sparse/SparseIntDirectedGraph.java#L283

Minimalist java example:
```java
import java.util.*;

public class IntCompare {

    public static Integer a = 0;
    public static Integer b = 0;

    public static void main(String[] args){

        while(a == b){
            a++;
            b++;
        }

        System.out.printf("a=%d, b=%d\na==b = %s\na.equals(b) = %s\n", a, b, a==b, a.equals(b));
    }
}
```

Output:
```
> java IntCompare
a=128, b=128
a==b = false
a.equals(b) = true
```

**Comment by jsichi** [comment]
The bug you reported looks like it was in an older version.  When I check the current code, which has since been refactored, it appears to have been fixed.  But if you can trace it down to a similar problem in the latest codebase, please pinpoint it and reopen, thanks!
