### ISSUE TITLE
compilation error in DoublyLinkedList with Java 21

### ISSUE THREAD

**Issue by cushon** [jgrapht/jgrapht#1154]
```
 * JGraphT version: 7084d919351ed09f36a82230fd6f47c8e805d65e
 * Java version (java -version)/platform:  21-ea+22-1890
```

**Issue**

JGraphT does not compile with the latest versions of Java, due to the implementation of [sequenced collections](https://openjdk.org/jeps/431).

Example failure:

```
[ERROR] ./jgrapht-core/src/main/java/org/jgrapht/util/DoublyLinkedList.java:[59,8] types java.util.Deque<E> and java.util.List<E> are incompatible;
  both define reversed(), but with unrelated return types
```

**Steps to reproduce (small coding example)**

```diff
$ git diff
diff --git a/pom.xml b/pom.xml
index 1d82de46df..0c681446f4 100644
--- a/pom.xml
+++ b/pom.xml
@@ -232,7 +232,7 @@
                     <artifactId>maven-compiler-plugin</artifactId>
                     <version>${maven-compiler-plugin.version}</version>
                     <configuration>
-                        <release>11</release>
+                        <release>21</release>
                         <compilerArgs>
                             <arg>--add-modules</arg>
                                 <arg>java.xml</arg>
```

```
$ cd jgrapht-core
$ JAVA_HOME=${JDK21_HOME?} mvn clean package -DskipTests=true
```

**Other information**

* https://openjdk.org/jeps/431
* https://github.com/openjdk/jdk/commit/17ce0976e442d5fabb14daed40fa9a768989f02e

**Comment by d-michail** [comment]
Hi. 

Can you pinpoint the problem? Is it some change in class `AbstractSequentialList`?  Is there some easy fix?

**Comment by cushon** [comment]
The problem is that `DoublyLinkedList` implements both `java.util.Deque` and `java.util.List`, and that https://github.com/openjdk/jdk/commit/17ce0976e442d5fabb14daed40fa9a768989f02e added `reversed()` methods to both of those interfaces, and they have incompatible return types.

I see at least a couple options

* `DoublyLinkedList` could implement `reversed()`. That change would be compatible with versions of Java before Java 21, it would just have to omit the `@Override` annotation.
* `DoublyLinkedList` could stop implementing the `Deque` interface. I don't see anywhere `DoublyLinkedList` is converted to a `Deque`. It could still define the methods that were being used (the `@Override` annotations would have to be removed).

**Comment by jkinable** [comment]
The issue is that, moving forward,  DoublyLinkedList , cannot implement
both list and deque. We probably need to make a choice which one to
retain,or possibly switch to a different interface.

**Comment by cushon** [comment]
I think it is still possible to implement both `List` and `Deque`, as long as it explicitly overrides `reversed()`

The issue is that if it doesn't implement `reversed()`, it inherits an implementation that returns `List`, and an implementation that returns `Deque`, and they clash. Declaring a covariant override of `reversed()` that returns `DoublyLinkedList` fixes that error.

That said, I think implementing only one of the two interfaces is a good option.
