### ISSUE TITLE
K-vertex cover (or range) for RecursiveExactVCImpl

### ISSUE THREAD

**Issue by tulliopizzuti** [jgrapht/jgrapht#1155]
Dear contributors,
I'm working on my thesis and I need to check if there are vertex covers in a given range. I'm trying to edit the code but to no avail. Could you give me some advice on how to modify the code?

**Comment by jsichi** [comment]
https://github.com/jgrapht/jgrapht/wiki/Dev-guide%3A-How-to-setup-your-development-environment-for-JGraphT

**Comment by jkinable** [comment]
I assume this issue has been resolved. Feel free to re-open or ask on stackoverflow if not.
