### ISSUE TITLE
edgeWeight is not Generic/Typesafe

### ISSUE THREAD

**Issue by adambourke** [jgrapht/jgrapht#116]
Setting the edge weight (in the abstractBaseGraph) does not use generics, despite taking a generic parameter. The first line of the method checks that the incoming edge is of type "DefaultWeightedEdge."

To make matters worse, DefaultWeightedEdge is not an interface, which means that to use a weighted edge with any information other than source and target we have to write a new class that extends DefaultWeightedEdge, and probably contains the object we wanted to use as the edge in the first place.

> public void setEdgeWeight(E e, double weight)
>     {
>         assert (e instanceof DefaultWeightedEdge) : e.getClass();
>         ((DefaultWeightedEdge) e).weight = weight;
>     }

My Suggestions: The graph already keeps edge data in a map - either extend this map to include weight information, or create a separate one for edge weights. This shouldn't be too complicated for maintaining backwards compatibility.

Minimum suggestion: Make the assertion check for an interface, so we can simply implement it in the class we wanted to use in the first place. (Actually though - this would likely be more work than adding the map!)

**Comment by neidro** [comment]
Please fix this! It's horrible! And so Easy!
It seems to me you just have to change the two methods to 

public void setEdgeWeight(E e, double weight)
{
    getIntrusiveEdge(e).setWeight(weight)
}

... and ...

public double getEdgeWeight(E e) {
    return getIntrusiveEdge(e).weight;
}

... I hope anybody reads this ...

**Comment by d-michail** [comment]
Fixed in #366. 

Thanks for reporting!
