### ISSUE TITLE
GraphFactory class?

### ISSUE THREAD

**Issue by jtatria** [jgrapht/jgrapht#119]
Hello. Just started playing with Jgrahpt, and inmediately wandered if it owuld be possible to include a GraphFactory class/interface that takes a number of parameters (like allow multiple, allow loops, etc) and gives you back the corresponding implementing instance of a graph.

Is there some reason why this would not be advisable/some caveats against it?

I already have a very navie implementation locally, but I was wondering if I'm missing some critical aspect that has prevented inclusion of such a feature thus far...

**Comment by jkinable** [comment]
Various classes which automatically generate graphs are now available. Have a look at the org.jgrapht.generate package. Creating a factory class based on these generators should be relatively straightforward. Feel free to ask if you have any additional questions/problems. 

Given the age of this question (almost a year old), I'll for now close this question.
