### ISSUE TITLE
Subgraph: why iterate over all edges of supergraph when we can iterate over the filter set?

### ISSUE THREAD

**Issue by Suseika** [jgrapht/jgrapht#120]
https://github.com/jgrapht/jgrapht/blob/dc8d31acfddb13ddf1b46040c3b2521d74fbde4f/jgrapht-core/src/main/java/org/jgrapht/graph/Subgraph.java#L444

My understanding is that filter set tends to be a subset of parent graph's edges, so wouldn't it be more efficient to iterate over the filter set? Of course, filter set may only intersect the supergraph's edges set, and then iterating can get less efficient, but I think it is the API user's responsibility to provide a "good" filter set.

**Comment by jkinable** [comment]
This issue has been resolved in pull request #307 . Thanks for reporting.
