### ISSUE TITLE
Start vertex for TopologicalOrderIterator

### ISSUE THREAD

**Issue by Spliterash** [jgrapht/jgrapht#1207]
I need to get a topological sort similar to the TopologicalOrderIterator iterator, but with the ability to specify a start vertex.
It will only contain the elements that can be reached from the start vertex, but with topological sorting

How can I achieve this ?

**Comment by jsichi** [comment]
1) Collect the vertices you want (e.g. by using a DepthFirstIterator starting from the vertex); see the code in ConnectivityInspector.connectedSetOf for an example

2) Create an induced subgraph using the AsSubgraph class and the vertex subset you obtained in (1)

3) Use TopologicalOrderIterator on the subgraph

**Comment by Spliterash** [comment]
Thanks
