### ISSUE TITLE
Contributor Guidelines Wiki update

### ISSUE THREAD

**Issue by atombrella** [jgrapht/jgrapht#121]
The link to LucidDB is dead, as LucidDB stopped future development, and gave up their website.

https://github.com/jgrapht/jgrapht/wiki/Contributor-Guidelines

Coding Conventions

In general, JGraphT follows the coding conventions from LucidDB. Specific refinements include project file headers; please follow the pattern set by existing source files. Also, be sure to preserve existing authorship attribution, and give due credit to all contributors and external sources. And set your editor to use spaces only, never tabs.

**Comment by jsichi** [comment]
Thanks, I've updated our wiki page.
