### ISSUE TITLE
`AsUnmodifiableGraph` Does Not Block Edge Weight Modification

### ISSUE THREAD

**Issue by syoon2** [jgrapht/jgrapht#1216]
* JGraphT version: 6a6f167

**Description**

`AsUnmodifiableGraph.setEdgeWeight` method allows modification of the weight _and_ "writes through" to the backing graph.

**Steps to reproduce (small coding example)**

```java
Graph<String, DefaultWeightedEdge> g = new DefaultUndirectedWeightedGraph<>(DefaultWeightedEdge.class);
g.addVertex("v1");
g.addVertex("v2");
g.addEdge("v1", "v2");
Graph<String, DefaultWeightedEdge> ug = new AsUnmodifiableGraph<>(g);

ug.setEdgeWeight("v1", "v2", 0d); // should throw UnsupportedOperationException
g.getEdgeWeight(g.getEdge("v1", "v2")); // should return Graph.DEFAULT_EDGE_WEIGHT
```

**Actual behaviour**

`ug.setEdgeWeight("v1", "v2", 0d);` runs without error
`g.getEdgeWeight(g.getEdge("v1", "v2"));` returns `0d`

**Comment by jsichi** [comment]
Heh, whoops.
