### ISSUE TITLE
Where can I find the documentation about the layout behaviour and configuration?

### ISSUE THREAD

**Issue by ppazos** [jgrapht/jgrapht#1226]
```
 * JGraphT version:
 * Java version (java -version)/platform:  
```

**Issue**
I'm trying to render a simple graph and I'm having some issues with the layout not adjusting to the frame size correctly. I have tested other layouts than the circle one, but all break the graph, so I'm not sure if there is any missing configuration or is just the default behavior. Looking into the user guide, there is no documentation about how layouts work, so I'm wondering if there is another place that I might not see that has such info, Thanks!

**Steps to reproduce (small coding example)**

**Expected behaviour**

**Other information**

**Comment by ppazos** [comment]
Just found the layouts depend on jgraphx and that depends on mxgraph, which are both dead projects.

Is there a way to use this library without depending on those projects?

**Comment by jsichi** [comment]
JGraphT is a graph data structure library, not a visualization library.  The adapters to projects such as JGraphX are optional components.

**Comment by ppazos** [comment]
Thanks for the clarification @jsichi
