### ISSUE TITLE
Unexpected Behavior of DOTImporter with Backslashes

### ISSUE THREAD

**Issue by fwhdzh** [jgrapht/jgrapht#1228]
```
 * JGraphT version: 1.5.2
 * Java version (java -version)/platform:  21
```

**Issue**

It appears that the DOTImporter incorrectly interprets a Java string containing double backslashes (`"\\\\"`) as a single backslash (`\`) instead of the expected double backslash (`\\`).

**Steps to reproduce (small coding example)**

Below is an example test case that demonstrates this issue.

```
        String input = "digraph sample {\n" + "  a -> b; \n" + "  a [ label=\" /\\\\n \"];\n"
                + "  b [ label=\"Test\"];\n"  + "}";
        Map<String, Map<String, Attribute>> attrs = new HashMap<>();
        DOTImporter<String, DefaultEdge> importer = new DOTImporter<>();
        importer.addVertexAttributeConsumer((p, a) -> {
            Map<String, Attribute> map = attrs.get(p.getFirst());
            if (map == null) {
                map = new HashMap<>();
                attrs.put(p.getFirst(), map);
            }
            map.put(p.getSecond(), a);
        });

        DirectedMultigraph<String, DefaultEdge> result = new DirectedMultigraph<>(
                SupplierUtil.createStringSupplier(), SupplierUtil.DEFAULT_EDGE_SUPPLIER, false);
        importer.importGraph(result, new StringReader(input));

        System.out.println(attrs.get("0").get("label"));
```

**Expected behaviour**

Expected output: `\\n`
Actual output: `\n`

**Other information**

Since I've written my DOT file as `a label = "/\\n"`, I expect JGraphT to import it without any modifications.

**Comment by fwhdzh** [comment]
Hi,

Is there any update or thoughts regarding this issue? If it turns out to be a bug, I would be interested in submitting a pull request to address it.

Thank you!

**Comment by jsichi** [comment]
Yes, please go ahead with a PR.  The lookupMap seems to have other things wrong too, since https://graphviz.org/doc/info/lang.html clearly states:  In quoted strings in DOT, the only escaped character is double-quote ". That is, in quoted strings, the dyad \" is converted to "; all other characters are left unchanged. In particular, \\ remains \\. Layout engines may apply additional escape sequences.

@d-michail let us know if you disagree

**Comment by fwhdzh** [comment]
Hi, I have made a pull request [#1231](https://github.com/jgrapht/jgrapht/pull/1231)  for this issue. Please let me know if there is any problem.
