### ISSUE TITLE
Snapshot Updates Failing

### ISSUE THREAD

**Issue by syoon2** [jgrapht/jgrapht#1234]
<https://github.com/jgrapht/jgrapht/actions/runs/10906157484/job/30267277579>
<https://github.com/jgrapht/jgrapht/actions/runs/11354445411/job/31582064036>

Upstream change: <https://support.sonatype.com/hc/en-us/articles/360049469534-401-Content-access-is-protected-by-token-when-accessing-repositories>

**Comment by jsichi** [comment]
Thanks, I've set up the tokens correctly to fix it.

**Comment by jsichi** [comment]
Closing now.
