### ISSUE TITLE
Feature request - add Eppstein's k-shortest paths

### ISSUE THREAD

**Issue by eranation** [jgrapht/jgrapht#131]
Eppstein's k-shortest paths is an efficient algorithm for finding k-shortest paths (http://static.aminer.org/pdf/PDF/001/059/121/finding_the_k_shortest_paths.pdf) 

It would be nice to have it as part of the core library. (I'll send a pull request if I end up implementing it)

What I really like about it is the ability to provide a minimal path length

**Comment by kevemueller** [comment]
I have committed an implementation of Eppstein in my fork at https://github.com/kevemueller/jgrapht/tree/eppstein.
I am not yet happy with it, but plan to get it into a state that can be pulled.
Any comments/testing/... welcome.

**Comment by simlu** [comment]
@kevemueller Sweet! I'm interested in this as well. What's left before this can be considered for merging into master?

**Comment by kevemueller** [comment]
First pull request #413 needs to be merged. I might find some time this week to reflect on the comments of @jkinable. Then I will create pull request for eppstein. The code is laying around unchanged for two months.
In the meantime you can just checkout kevemueller@7aa8f9244f2fa157f05e2aa6ecec96bcdf035527 and give some feedback.

**Comment by jkinable** [comment]
Implemented in #755.
