### ISSUE TITLE
Question - Usable with transport network data structures?

### ISSUE THREAD

**Issue by cryo75** [jgrapht/jgrapht#133]
I have the following data structures:

public class Node {
    public int id;
    public int level;
}

public class Edge {
    public int fromNodeId, toNodeId;
    public double distance;
    public double time; //might be used for quickest route
}

The edges are for a directed graph (as found in the table). For searches I need to duplicate and invert the edges for undirected graphs.

I need to search k-shortest paths and also have transit node routing with contracting hierarchies. Node.Level describes node hierarchy (1=hub, 2=main 3=other) so I guess contracting hierarchies isn't necessary in this case. 

I need such a search algorithm because, even though my current implementation searches the shortest paths, there might be too many changes/hops.

Does JGraphT have the ability to search k-shortest paths with transit node routing?

**Comment by jkinable** [comment]
You are better off asking your questions on the mailing lists... 
No, JgraphT currently doens't have an algorithm which does routing at different levels. It's probably not very difficult to create a data structure which implements what you want using JgraphT.
