### ISSUE TITLE
Undirected weighted graph?

### ISSUE THREAD

**Issue by cryo75** [jgrapht/jgrapht#134]
Which graph class do I need to use for an undirected weighted graph?

Also, if my edges are directed, should I add a reverse edge manually to the graph, or does the graph itself take care of this when adding an edge?

**Comment by jkinable** [comment]
Please use the mailing list for these questions. This is not really an 'issue' which should be tracked. Also check some of the examples. Undirected weighted graph: SimpleWeightedGraph. For your second question: if you add a directed edge (i,j) to a directed graph, you need to add the directed edge (j,i) yourself if that's what you want.
