### ISSUE TITLE
JgraphT Blossom Algorithm (Infinite Loop)

### ISSUE THREAD

**Issue by syed070** [jgrapht/jgrapht#139]
Hi Experts,
I am trying to test Edmonds Blossom Shrinking, but it is going into inifinite loop for my graph: Do you have any idea why?

        DefaultEdge e12 = g.addEdge(v1, v2);
        DefaultEdge e13 = g.addEdge(v1, v3);
        DefaultEdge e23 = g.addEdge(v2, v3);
        DefaultEdge e24 = g.addEdge(v2, v4);
        DefaultEdge e34 = g.addEdge(v3, v4);
        DefaultEdge e35 = g.addEdge(v3, v5);
        DefaultEdge e45 = g.addEdge(v4, v5);

Regards,

**Comment by alexeykudinkin** [comment]
That's due to the fact that current Edmonds blossom implementation is 'poorly' pulling some transient stuff into its state. Will try to send PR with the fix today.
