### ISSUE TITLE
Maven central artifact corrupted

### ISSUE THREAD

**Issue by Gnappuraz** [jgrapht/jgrapht#147]
Every time I try to get the jgrapht (parent) or even core i get a corrupted jar.
On mac the zip command give me this a "Missing end (EOCDR) signature" error. Idea where to get a working artifact cause I would really like to include the library as a maven dep.

**Comment by jsichi** [comment]
Are you using this configuration?

  <groupId>org.jgrapht</groupId>
  <artifactId>jgrapht-core</artifactId>
  <version>0.9.1</version>

**Comment by Gnappuraz** [comment]
I was using :
<dependency>
            <groupId>org.jgrapht</groupId>
            <artifactId>jgrapht</artifactId>
            <version>0.9.1</version>
        </dependency>
and the same with jgrapht-core, today the jgrapht-core is working while the parent (jgrapht) is still corrupted.

**Comment by jsichi** [comment]
Nothing has changed recently on the Maven Central side, so I think you were probably having internet or some other configuration issues.  We don't publish any artifacts for the parent, only for the subprojects.
