### ISSUE TITLE
How to find a FibonacciHeapNode in a FibonacciHeap ?

### ISSUE THREAD

**Issue by xavierwoo** [jgrapht/jgrapht#156]
I do not find a method to search for a certain FibonacciHeapNode in a FibonacciHeap.
So I have to build a map to record the relationship between the datas and the FibonacciHeapNodes when i build the FibonacciHeap, if I want to use the method decreaseKey() during my program.
Is there any more elegant ways to do so?

**Comment by d-michail** [comment]
Closing this one, as it is self-contained. Fibonacci heaps do not support search, see CLRS for details.
