### ISSUE TITLE
Bug in MaskEdgeSet and VertexEdgeSet

### ISSUE THREAD

**Issue by mkrutsky** [jgrapht/jgrapht#161]
In [MaskEdgeSet](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/graph/MaskEdgeSet.java#L103) and identically in [MaskVertexSet](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/graph/MaskVertexSet.java#L97) size is computed only once and never again. This behaviour doesn't reflect changes in base graph, although iterator() method returns correct result.

**Comment by jsichi** [comment]
https://github.com/jgrapht/jgrapht/pull/185
