### ISSUE TITLE
Allow DirectedSubgraph (etc) to accept Set<? extends V> not just Set<V>

### ISSUE THREAD

**Issue by shevek** [jgrapht/jgrapht#164]
Since DirectedSubgraph treats the given set as read-only, it should accept `Set<? extends V>` and `Set<? extends E>` in the constructor. This change is backwards compatible with existing code, but will allow additional compatibility with code which uses generics to indicate mutability, such as Google's Guava library.

Thank you.

**Comment by d-michail** [comment]
Would it be possible to demonstrate a use case where such a change would be necessary?

**Comment by jkinable** [comment]
This issue has been resolved in pull request #307 . Thanks for reporting.
