### ISSUE TITLE
JGraphModelAdapter not in 0.9.1

### ISSUE THREAD

**Issue by rafael-alcantara** [jgrapht/jgrapht#173]
Hi,

I found JGraphT looking for an algorythms library, and I found it really cool, especially the ability to use any classes as vertices and edges. Thanks for that.
I started testing it as a maven dependency, as described in the project web, and tried to display a graph using JGraph following directions from the link I found there too, using JGraphModelAdapter. However this class - the whole ext package actually - is not found in the jar file downloaded by maven?

Besides, the JGraph project seems to have moved to JavaScript completely, I could not find the old Java thing anywhere...

Is there an easy way to display a JGraphT graph?

Thanks again,

Rafa

**Comment by besza** [comment]
If you want to use the extension features make sure to add the corresponding dependency to your POM file:
```
<dependency>
    <groupId>org.jgrapht</groupId>
    <artifactId>jgrapht-ext</artifactId>
     <version>0.9.1</version>
</dependency>
```
Also check out [https://github.com/jgrapht/jgrapht/blob/master/jgrapht-demo/src/main/java/org/jgrapht/demo/JGraphAdapterDemo.java](JGraphAdapterDemo)
