### ISSUE TITLE
Finding all paths between 2 nodes in a directed graph

### ISSUE THREAD

**Issue by roniko1994** [jgrapht/jgrapht#178]
Hello!

Is there an implemented algorithm which finds all paths(not shortest paths) between 2 nodes in a directed graph?

Thanks!

**Comment by agdphd** [comment]
I recently cooked up a reasonably performant algorithm for generating all (non-self-intersecting) paths between two (sets of) nodes in a digraph for another project. I can have a go at implementing it in JGraphT, but I'm just getting familiar with the project so it may take a while for me to get the hang of the codebase and there's no guarantee that I'll manage to produce something worth including here.

How large are the graphs you'll be computing this for?

**Comment by jsichi** [comment]
The pull request has been merged.
