### ISSUE TITLE
MaskSubgraph.containsEdge returns true for edges where one vertex is masked

### ISSUE THREAD

**Issue by shevek** [jgrapht/jgrapht#182]
If I make a MaskFunctor where isEdgeMasked always returns false, and isVertexMasked sometimes returns true, then most manipulations on the MaskSubgraph will behave as if edges where one vertex is masked are also implicitly masked.

However, MaskSubgraph.containsEdge() appears not to honour this, and merely returns true if the underlying (unmasked) graph contains the edge.

I suspect a simple test with a two-node graph and one edge will exhibit the behaviour: If one of the nodes is masked, the MaskSubgraph will still return true on containsEdge()

**Comment by jsichi** [comment]
Dup of #160?  Maybe one day someone will submit a pull request to fix this.

**Comment by shevek** [comment]
I like your optimism. :-) I run my own open source projects the same way.

**Comment by jsichi** [comment]
Amazing.

https://github.com/jgrapht/jgrapht/pull/185
