### ISSUE TITLE
JGraphT: kshortestpaths not responding

### ISSUE THREAD

**Issue by Jonas1234567890** [jgrapht/jgrapht#187]
I would like to use jgrapht to build graphs with java and find the k-shortestPaths in the graph.

The graph is of the form

`private final DefaultDirectedWeightedGraph<Vertex, DefaultWeightedEdge> ourGraph = new DefaultDirectedWeightedGraph<Vertex, DefaultWeightedEdge>(DefaultWeightedEdge.class);`

For edges, I use the DefaultWeightedEdge, while for vertices, I created a tailored class
`public class Vertex implements Iterable<Vertex> {`
`private int t;`
`private int tOn;`
`private String name;`

`public Vertex (int t, int tOn) {`
`this.t = t;`
`this.tOn = tOn;`
`this.name = "Vertex_" + t + "_" + tOn;`
`}`

`public String getName() {`
`return name;`
`}`

`public int getT() {`
`return t;`
`}`

`public void setT(int t) {`
`this.t = t;`
`}`

`public int getTOn() {`
`return tOn;`
`}`

`public void setTOn(int tOn) {`
`this.tOn = tOn;`
`}`

`@Override`
`public boolean equals(Object o) {`
`if ( o == null ||  ! o.getClass().equals(getClass())) {`
`return false;`
`}`
`if ( o == this ) {`
`return true;`
`}`
`Vertex that = (Vertex) o;`
`return this.getName().equals(that.getName());`
`}`

`@Override`
`public int hashCode() {`
`return t*1000 + tOn;`
`}`

`@Override`
`public Iterator<Vertex> iterator() {`
`// TODO Auto-generated method stub`
`return null;`
`}`

`}`

I succeed in building the graph, setting edge weights, etc. I would like to calculate the k shortest paths using the following jgrapht method, which I call in the Graph class:
`private List<GraphPath<Vertex, DefaultWeightedEdge>> paths = new LinkedList<GraphPath<Vertex, DefaultWeightedEdge>>();`
`public void calculateKShortestPaths(int k) {`
`KShortestPaths<Vertex, DefaultWeightedEdge> ksp = new KShortestPaths<Vertex, DefaultWeightedEdge>(ourGraph, getStartVertex(), k);`
`paths = ksp.getPaths(getEndVertex());`
`}`

However, nothing happens. The error must be here:
`paths = ksp.getPaths(getEndVertex());`

There is no error message thrown etc, so the program keeps running. It should not take that long to find the shortest path.

My guess is that there is something wrong with the Vertex-Class that I implemented. Maybe I am missing something that KShortestPaths builds on.

Did anybody of you experience something comparable? Any help is highly appreciated!

Thanks and best regards, Jonas

**Comment by jkinable** [comment]
Hi Jonas,

For future reference, consider asking your questions on the JGraphT mailing list. The response rate there is much higher and generally faster than here. Furthermore, the mailing list is indexed, so your questions/answers may benefit other people.

I went over your Vertex implementation. Here's one possible cause of the issue you are experiencing. JGraphT heavily relies on Sets and Maps, which in turn rely on the hashCode() implementation of both Vertices and Edges. Imagine you do the following:
1. Create a vertex and add it to the graph
2. invoke your setT(int... ) method. Which changes the t value of your vertex.
3. By performing (2), you changed the hashCode of your Vertex (see your hashCode() implementation). 

By doing so, you violate this principle (see [javadoc](https://docs.oracle.com/javase/7/docs/api/java/util/Set.html) Set interface):

> Note: Great care must be exercised if mutable objects are used as set elements. The behavior of a set is not specified if the value of an object is changed in a manner that affects equals comparisons while the object is an element in the set. A special case of this prohibition is that it is not permissible for a set to contain itself as an element.

Consequently, the graph may no longer be able to find your vertex even though it's in some set/map.  All sorts of unpredictable behavior may happen. I would recommend making the fields in Vertex final. You may want to have a look at the SimpleIdentityDirectedGraphTest.java class in jgrapht's test suite. This stuff is however quite tricky and I wouldn't recommend it.

That being said, I'm not the developer of the kShortestPath implementation, so I'm not claiming that there's not bug in the code. :)

**Comment by Jonas1234567890** [comment]
Dear Joris,

thank you very much for your answer. In the meantime, I updated the graph so that I replaced my own Vertex class with vertices as Strings. However, the problem persists. So, I suppose the bug must be somewhere else - maybe in the ksp algorithm.

However, I will follow your advise to add my question to the jgrapht mailing list.

Thank you & best regards,
Jonas

**Comment by jkinable** [comment]
I'm closing this issue as it has been inactive for quite some time. Feel free to re-open if the issue hasn't been resolved.
