### ISSUE TITLE
Incorrect Free Software Foundation address

### ISSUE THREAD

**Issue by puntogil** [jgrapht/jgrapht#190]
Seem the license-LGPL.txt file report the old address of GNU Free Software Foundation
59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
can you correct with
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301
for Fedora is considered as a bug, see https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address
Thanks in advance
Regards

**Comment by jsichi** [comment]
Done.  Interestingly, the FSF's own contact page has a slightly different ZIP+4 code (02110-1335):

http://www.fsf.org/about/contact/

Tell us FSF! We demand to know...what is the *real* address?  Is it a secret???  Don't make me sing the free software song just to find out.

**Comment by puntogil** [comment]
sorry, ... perhaps they were evicted ...
