### ISSUE TITLE
Unequal number of S and T in KuhnMunkresMinimalWeightBipartitePerfectMatching

### ISSUE THREAD

**Issue by arjunvijayvargiya** [jgrapht/jgrapht#194]
How to solve for Unequal number of S and T in KuhnMunkresMinimalWeightBipartitePerfectMatching

https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/alg/KuhnMunkresMinimalWeightBipartitePerfectMatching.java

**Comment by jkinable** [comment]
you'll have to be more precise: what exactly do you want to know? Given the date of this question, I presume you've resolved the issue yourself.
