### ISSUE TITLE
Bug in graph.removeAllEdges?

### ISSUE THREAD

**Issue by rykelly** [jgrapht/jgrapht#196]
Hi there,

I'm testing out jgrapht for an agent-based modeling project, and think I found a bug. The demo code below reproduces it. As you can see we're modeling a graph of connected rooms, and I want the ability to close one room, forcing agents to choose a different path if their preferred path would involve a closed room. My idea was to simply remove edges connected to a room when it's closed, and then I could replace them later if the room opens up again. 

However, `removeAllEdges()` only removes one of the two edges connected to my closed room in this example. And in preparing the demo code I discovered that if I try the same operation again, this time it throws a ConcurrentModificationException. 

I can work around this, but wanted to let you know, and find out if maybe I'm just not using the function as intended. 

```java
import java.util.*;
import org.jgrapht.graph.*;

public class GraphBugDemo {
  private SimpleWeightedGraph<Room, DefaultWeightedEdge> graph =
      new SimpleWeightedGraph<>(DefaultWeightedEdge.class);


  private static class Room {
    private String id;


    public void setId(String id) {
      this.id = id;
    }


    @Override
    public String toString() {
      return id;
    }
  }


  private void addEdge(Room room1, Room room2, double distance) {
    graph.addVertex(room1);
    graph.addVertex(room2);
    DefaultWeightedEdge edge = graph.addEdge(room1, room2);
    graph.setEdgeWeight(edge, distance);
  }


  private void closeRoom(Room room) {
    Set<DefaultWeightedEdge> edgesToRemove = graph.edgesOf(room);
    System.out.println("Initial graph: " + graph.toString());
    System.out.println("Edges to remove: " + edgesToRemove);
    graph.removeAllEdges(edgesToRemove);
    System.out.println("Final graph: " + graph.toString());

    boolean ans = false;
    for (DefaultWeightedEdge e : edgesToRemove)
      ans |= graph.containsEdge(e);
    System.out.println("Contains edges that should have been removed? " + ans);
  }


  public static void main(String[] args) {
    GraphBugDemo roomGraph = new GraphBugDemo();
    Room room1 = new Room(), room2 = new Room(), hallA = new Room(), hallB = new Room();
    room1.setId("Room1");
    room2.setId("Room2");
    hallA.setId("HallA");
    hallB.setId("HallB");

    roomGraph.addEdge(room1, hallA, 1);
    roomGraph.addEdge(room1, hallB, 1);
    roomGraph.addEdge(room2, hallA, 2);
    roomGraph.addEdge(room2, hallB, 1);

    System.out.println("First try:");
    roomGraph.closeRoom(hallB);

    System.out.println();
    System.out.println("Second try:");
    roomGraph.closeRoom(hallB);
  }

}

```

**Comment by jsichi** [comment]
You need to make a copy of edgesToRemove before passing it to removeAllEdges.  If you look in the source for AbstractBaseGraph.removeVertex, you'll see it doing that to avoid similar problems.

**Comment by rykelly** [comment]
Thanks for the response and solution.

[ mobile ]
