### ISSUE TITLE
Only one shortest path is returned when there are more than one exists in graph?

### ISSUE THREAD

**Issue by cyu021** [jgrapht/jgrapht#199]
Hi there,

Say we have a graph composed of:
wp1, wp2, wp3, wp4
and the following edges exists:
wp1 -- wp2
wp1 -- wp4
wp2 -- wp3
wp4 -- wp3

So we have 2 shortest paths in this graph when traversing from wp1 to wp3, and they are:
wp1 -- wp2 -- wp3
wp1 -- wp4 -- wp3

However, the "DijkstraShortestPath" only returns one of them at all time.
If this is the designed behaviour, can we have another method to return all possible choices?

Thank you for your time.

**Comment by jkinable** [comment]
You could implement that. Finding all of these paths may actually be a hard problem (need to look that up). There's quite a lot of literature on finding edge or vertex disjoint shortest paths. Or, more general, finding k edge/vertex disjoint shortest paths, in decreasing order of cost e.g. the cheapest path, the second cheapest path and so on. Have a look at the book Survivable Networks: Algorithms for Diverse Routing by Bhandari, Ramesh. We welcome all contributions :)

**Comment by assimiz** [comment]
Consider using KShortestPaths algorithm. It can find all parhs from source to target on decreasing order. They will no necessarilly be diversed though, but you can tweak the graph to achieve that.
