### ISSUE TITLE
DirectedAcylicGraph#removeAllVertices(Collection) incorrectly clears topological ordering

### ISSUE THREAD

**Issue by rdicroce** [jgrapht/jgrapht#200]
DirectedAcylicGraph#removeAllVertices(Collection) is supposed to remove the given vertices from the graph. It does that, but then removes ALL vertices from the topological ordering, leaving the graph in an inconsistent state and causing iterator() to be empty even if there are still vertices in the graph.

It looks to me like the method should just be removed altogether, as the superclass's implementation just calls removeVertex(V) for each vertex, which results in the correct behavior.

**Comment by besza** [comment]
The naming is also ambiguous I'd say, it should simply be removeVertices(Collection).
A quick fix to the main issue  could be a TopoOrderMap<V>.removeVertices(Collection) method, which handles this properly or as @rdicroce mentioned call removeVertex for each vertex in the collection.

**Comment by besza** [comment]
@jsichi I believe this issue can be closed.
