### ISSUE TITLE
CharikarDensestSubgraph  for weighted graph

### ISSUE THREAD

**Issue by TamouzeAssi** [jgrapht/jgrapht#205]
I want to find the Densest Sub-graph for a weighted graph using CharikarDensestSubgraph class.

Question:

How can modify the code to select the vertex that have the lowest weighted degree (sum of the weights of the node’s incident edges).

Thank you in advance for your apprecite help

**Comment by besza** [comment]
Jgrapht has no such implementation, this issue should be closed.
