### ISSUE TITLE
DOTImporter implementation not suitable for large graphs

### ISSUE THREAD

**Issue by aleSuglia** [jgrapht/jgrapht#206]
Hi to all,

I am using JGrapht for a university project in which I work with large network data which contains about 8000 nodes. I am looking for a way to serialize the generated graph in order to re-use it. 

I have seen that you support the default Java serialization mechanism and the DOT serialization format.  I have tried the latter because for my application could be interesting to plot the graph too. Unfortunately, if you work with large graphs your implementation of the DOTImporter it is not appropriate because the _read_ method expects the whole file content in input as a string. In my opinion the DOTImporter should provide a _read_ method which reads from a _Reader_ or _BufferedReader_, in order to incrementally build the graph. 

Do you think that this solution is possible or am I missing something?

Thank you in advance for your answer.

Alessandro

**Comment by jkinable** [comment]
Yep, sounds like a good idea. It would be great be great if you could add this functionality and test it on your large graphs.

**Comment by jkinable** [comment]
This issue should be resolved in our next release, due to the inclusion of a brand new DOT importer/exporter (see pull request #358). 

@aleSuglia feel free to give the new importer a try. The new DOT importer is now merged into the master branch. If you can, let us know how the new importer scales!
