### ISSUE TITLE
How to copy a graph?

### ISSUE THREAD

**Issue by yaitskov** [jgrapht/jgrapht#21]
I've spent 1 hour to get way to copy a graph.

I've found graph generator package but It seems it doesn't have such feature.

**Comment by galpsten** [comment]
If addGraph is called with an empty graph as destination, it will only do a shallow copy, right? Is it possible to easily do deep copies in any other way?

**Comment by jsichi** [comment]
http://jgrapht-users.107614.n3.nabble.com/Troubless-with-references-td107944.html
