### ISSUE TITLE
Allow setting the max-flow implementation for min s-t cut

### ISSUE THREAD

**Issue by neverfox** [jgrapht/jgrapht#231]
Edmonds-Karp is a good default, but I don't believe there's anything special about it that makes it particularly suited for the rest of the min s-t cut algorithm, which should be able to run with any max-flow output. If I'm right about that, are you open to it?

**Comment by jkinable** [comment]
We recently revised some of the max flow algorithms. In the upcoming version of jgrapht (1.0.0) there will be a new max-flow algorithm. In addition, There's an interface for max flow algorithms (MaximumFlowAlgorithm). It would make sense to update the Min s-t cut algorithm thereby replacing
EdmondsKarpMaximumFlow<V, E> ekMaxFlow= .... by MaximumFlowAlgorithm algorithm= .... Finally one could add an additional constructor to specify which max flow algorithm should be used.
Finally, the default algorithm in Min st cut should probably be PushRelabelMaximumFlow.java, as this is likely the fastest.

Feel free to submit a pull request :).

**Comment by neverfox** [comment]
Cool, and yes, using PushRelabelMaximumFlow instead was exactly my motivation.

**Comment by jkinable** [comment]
Fixed. Thanks for suggesting.
