### ISSUE TITLE
NullPointerException in HopcroftKarpBipartiteMatching<V,E>

### ISSUE THREAD

**Issue by nolberg** [jgrapht/jgrapht#233]
I use the following code to generate a random bipartite graph:

    UndirectedGraph<Integer, DefaultEdge> g = 
        			new SimpleGraph<Integer, DefaultEdge>(DefaultEdge.class);
        	
    int n = rnd.nextInt(TEST_GRAPH_SIZE) + 2;
    int seperate = rnd.nextInt(n - 1) + 1;

    Set<Integer> left = new HashSet<Integer>();
    Set<Integer> right = new HashSet<Integer>();
            
    for (int j = 0; j < n; j++) {
        g.addVertex(j);
        if (j < seperate) left.add(j);
        else right.add(j);
    }
        	
    for (Integer l : left) {
         for (Integer r : right) {
              if (Math.random() > 0.35) g.addEdge(l, r);
         }
    }

When I call 

`
HopcroftKarpBipartiteMatching<Integer, DefaultEdge> matching = 
        			new HopcroftKarpBipartiteMatching<Integer, DefaultEdge>(g, left, right);`

it gives me the following error from time to time:

> 
Exception in thread "main" java.lang.NullPointerException
	at org.jgrapht.util.UnorderedVertexPair.hashCode(UnorderedVertexPair.java:71)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:556)
	at org.jgrapht.graph.specifics.FastLookupUndirectedSpecifics.getEdge(FastLookupUndirectedSpecifics.java:91)
	at org.jgrapht.graph.AbstractBaseGraph.getEdge(AbstractBaseGraph.java:159)
	at org.jgrapht.alg.HopcroftKarpBipartiteMatching.symmetricDifference(HopcroftKarpBipartiteMatching.java:182)
	at org.jgrapht.alg.HopcroftKarpBipartiteMatching.maxMatching(HopcroftKarpBipartiteMatching.java:158)
	at org.jgrapht.alg.HopcroftKarpBipartiteMatching.<init>(HopcroftKarpBipartiteMatching.java:84)

**Comment by d-michail** [comment]
@jkinable the following test case reproduces the above null pointer exception without any randomization

```
public void testBipartiteMatchingIssue233()
    {
        UndirectedGraph<Integer, DefaultEdge> g = new SimpleGraph<Integer, DefaultEdge>(
            DefaultEdge.class);

        Random rnd = new Random(4);
        int n = rnd.nextInt(3) + 2;
        int separate = rnd.nextInt(n - 1) + 1;

        Set<Integer> left = new HashSet<Integer>();
        Set<Integer> right = new HashSet<Integer>();

        for (int j = 0; j < n; j++) {
            g.addVertex(j);
            if (j < separate)
                left.add(j);
            else
                right.add(j);
        }

        for (Integer l : left) {
            for (Integer r : right) {
                if (rnd.nextDouble() > 0.35)
                    g.addEdge(l, r);
            }
        }

        HopcroftKarpBipartiteMatching<Integer, DefaultEdge> matching = new HopcroftKarpBipartiteMatching<Integer, DefaultEdge>(
            g,
            left,
            right);
        Set<DefaultEdge> m = matching.getMatching();
        assertTrue(m.contains(g.getEdge(1, 2)));
        assertTrue(m.contains(g.getEdge(0, 3)));
        assertEquals(2, m.size());
    }
```

The problem seems to be located at [HopcroftKarpBipartiteMatching:180](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/alg/HopcroftKarpBipartiteMatching.java#L180). 

As augmentingPath contains vertices, the condition should probably be ``while (augmentingPath.size() > 1)``.

**Comment by nolberg** [comment]
@d-michail I just ran a few tests with your suggestion and this seems to fix the problem.

**Comment by jkinable** [comment]
Can you provide a simplified test case without the randomization, thereby specifying just a simple graph, a left and a right partition, e.g.:
Graph g=...
Set<Integer> left=new HashSet<>(Arrays.asList(....));
Set<Integer> right=new HashSet<>(Arrays.asList(....));

**Comment by d-michail** [comment]
@jkinable simplified without the random number generator
```
public void testBipartiteMatchingIssue233()
    {
        UndirectedGraph<Integer, DefaultEdge> g = new SimpleGraph<Integer, DefaultEdge>(
            DefaultEdge.class);

        Set<Integer> left = new HashSet<Integer>();
        Set<Integer> right = new HashSet<Integer>();

        g.addVertex(0);
        left.add(0);
        g.addVertex(1);
        left.add(1);
        g.addVertex(2);
        right.add(2);
        g.addVertex(3);
        right.add(3);

        g.addEdge(0, 2);
        g.addEdge(0, 3);
        g.addEdge(1, 2);

        Set<DefaultEdge> m = new HopcroftKarpBipartiteMatching<Integer, DefaultEdge>(
            g,
            left,
            right).getMatching();
        assertTrue(m.contains(g.getEdge(1, 2)));
        assertTrue(m.contains(g.getEdge(0, 3)));
        assertEquals(2, m.size());
    }
```

**Comment by jkinable** [comment]
@nolberg thanks for reporting this, and @d-michail thanks for providing the simplified example. This is indeed a bug.

**Comment by jkinable** [comment]
Fixed
