### ISSUE TITLE
AllDirectedPaths . getAllPaths() not working for 1 edge

### ISSUE THREAD

**Issue by NelsonBurton** [jgrapht/jgrapht#234]
My test case is below, but the short of the issue is that if I have a graph of 
A -> B
A -> C
and try to find all paths from A to B,C, the algorithm returns 0 when it should return 2. 

`
public class Main {
    public DirectedGraph<String, DefaultEdge> g2 =
            new DefaultDirectedGraph<>(DefaultEdge.class);

    public DirectedGraph<String, DefaultEdge> g3 =
            new DefaultDirectedGraph<>(DefaultEdge.class);
    @Test
    public void testSmallExampleGraph () {

        String I1 = "I1";
        String I2 = "I2";
        String A = "A";
        String B = "B";
        String C = "C";
        String D = "D";
        String E = "E";
        String F = "F";
        String O1 = "O1";
        String O2 = "O2";

        g2.addVertex(I1);
        g2.addVertex(I2);
        g2.addVertex(A);
        g2.addVertex(B);
        g2.addVertex(C);
        g2.addVertex(D);
        g2.addVertex(E);
        g2.addVertex(F);
        g2.addVertex(O1);
        g2.addVertex(O2);

        g2.addEdge(I1, A);
        g2.addEdge(I1, B);

        g2.addEdge(I2, B);
        g2.addEdge(I2, C);

        g2.addEdge(A, B);
        g2.addEdge(A, D);
        g2.addEdge(A, E);

        g2.addEdge(B, E);

        g2.addEdge(C, B);
        g2.addEdge(C, F);

        g2.addEdge(D, E);

        g2.addEdge(E, O1);

        g2.addEdge(F, O2);

        AllDirectedPaths<String, DefaultEdge> pathFindingAlg =
                new AllDirectedPaths<>(g2);

        Set<String> sources = new HashSet<>();
        sources.add(I1);
        sources.add(I2);

        Set<String> targets = new HashSet<>();
        targets.add(O1);
        targets.add(O2);

        List<GraphPath<String, DefaultEdge>> allPaths =
                pathFindingAlg.getAllPaths(sources, targets, true, null);

        assertEquals("Toy network should have correct number of simple paths", 7, allPaths.size());

//        KeyValue kv1 = new KeyValue('a');
//        KeyValue kv2 = new KeyValue('b');
//        KeyValue kv3 = new KeyValue('c');

        String kv1 = "kv1";
        String kv2 = "kv2";
        String kv3 = "kv3";
        String kv4 = "kv4";

        g3.addVertex(kv1);
        g3.addVertex(kv2);
        g3.addVertex(kv3);
        g3.addVertex(kv4);

        g3.addEdge(kv1, kv2); // a->b
        g3.addEdge(kv1, kv3); // a->c

        g3.addEdge(kv2, kv4); // b->d
        g3.addEdge(kv3, kv4); // c->d

        AllDirectedPaths<String, DefaultEdge> pathFindingAlg1 =
                new AllDirectedPaths<>(g3);
        // now for graph traversal
        Set<String> startNodes = new HashSet<>();
        startNodes.add(kv1);

        Set<String> endNodes = new HashSet<>();
        endNodes.add(kv2);
        endNodes.add(kv3);

        List<GraphPath<String, DefaultEdge>> allPaths1 =
                pathFindingAlg1.getAllPaths(startNodes, endNodes, true, null);

        System.out.println(allPaths1.size());
    }
`

**Comment by jsichi** [comment]
@agdphd any comments on this?

**Comment by jsichi** [comment]
Looks like this has already been reported as #198

**Comment by jsichi** [comment]
Thanks!
