### ISSUE TITLE
AStarShortestPath.getShortestPath will use equal to compare currentNode and targetVertex

### ISSUE THREAD

**Issue by zgce** [jgrapht/jgrapht#236]
jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/AStarShortestPath.java:151

AStarShortestPath.getShortestPath will use equal to compare currentNode and targetVertex
-  if (currentNode.getData() == targetVertex) {
+ if (currentNode.getData().equals(targetVertex)) {

**Comment by jkinable** [comment]
Good point. Please submit a pull request.

**Comment by jkinable** [comment]
Fixed. Thanks for reporting.
