### ISSUE TITLE
isChordal() enhancement

### ISSUE THREAD

**Issue by hamadmarri** [jgrapht/jgrapht#255]
The function below is in this class "org/jgrapht/alg/CliqueMinimalSeparatorDecomposition.java"
```
    public boolean isChordal()
    {
        if (chordalGraph == null) {
            computeMinimalTriangulation();
        }

        return (chordalGraph.edgeSet().size() == graph.edgeSet().size());
}
```

I am not sure if this code is correct since it only compares the size of edges between the given graph and the chordalGraph of the given graph. The definition of chordal graph is that for any more than 3 connected nodes there should be a chord which is an edge connect 2 non adjacent nodes.

I believe the best way is to iterate to find 4 connected nodes and test if there is only one chord. I have sample code for different graph library I made it may help.
```
	boolean isChordal(Graph<Variable> graph) {
		for (GraphNode<Variable> gn1 : graph.getGraphNodes()) {
			for (Edge<Variable> e1 : gn1.getEdges()) {
				GraphNode<Variable> gn2 = e1.getTo();
				for (Edge<Variable> e2 : gn2.getEdges()) {
					GraphNode<Variable> gn3 = e2.getTo();
					if (gn3 == gn1) {
						continue;
					}

					for (Edge<Variable> e3 : gn3.getEdges()) {
						GraphNode<Variable> gn4 = e3.getTo();
						if (gn4 == gn2 || gn4 == gn1) {
							continue;
						}

						for (Edge<Variable> e4 : gn4.getEdges()) {
							GraphNode<Variable> gn5 = e4.getTo();
							if (gn5 == gn1) {
								if (!fourCyrcleWithChordal(gn1, gn2, gn3, gn4)) {
									return false;
								}
							}
						}
					}
				}
			}
		}
		return true;
	}

	boolean fourCyrcleWithChordal(GraphNode<Variable> gn1, GraphNode<Variable> gn2, GraphNode<Variable> gn3,
			GraphNode<Variable> gn4) {

		boolean gn1_gn3 = (gn1.getEdges().stream().filter(e -> e.getTo() == gn3).findFirst().orElse(null) != null);

		boolean gn2_gn4 = (gn2.getEdges().stream().filter(e -> e.getTo() == gn4).findFirst().orElse(null) != null);

		return (gn1_gn3 ^ gn2_gn4);
	}
```

I want to thank you for this amazing work. JGraphT really helped me a lot.

**Comment by jkinable** [comment]
I don't think this is necessary. 
computeMinimalTriangulation() constructively builds a chordal graph (minimum triangulation). If the constructed graph is identical in size to the input graph, then the input graph must be chordal.
