### ISSUE TITLE
Travis CI is failing due to failure to access GraphML xsd

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#260]
I hit this running tests locally as well, because the following URL stopped being accessible:

http://graphml.graphdrawing.org/xmlns/1.0/graphml-structure.xsd

Is there a way the importer can use a local copy of the resource instead of relying on this network resource?  This is important for both tests and production use.

**Comment by jsichi** [comment]
@d-michail could you please look into this?  For the moment, I'm going to disable the failing test.

**Comment by jsichi** [comment]
I've temporarily disabled the test with an Ignore annotation.  Remember to remove the annotation as part of the pull request for the fix.

(github won't let me assign this issue to you until you accept the invitation I sent you.)

**Comment by jsichi** [comment]
I would guess the xsd unavailability is temporary, so to repro the problem, disable your network .

**Comment by d-michail** [comment]
I need to wait until their server is up, to download two more xsd files locally.

**Comment by d-michail** [comment]
Now the two missing xsd files can be found in the classpath.

**Comment by jkinable** [comment]
Issue has been resolved in pull request #261. Thanks again for addressing this.
