### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by kibertoad** [jgrapht/jgrapht#274]
Last release was in April, and many things changed with that, and consuming snapshots is obviously not very convenient. Maybe it would be possible to release 1.0.0 at some point already, or at least publish at maven central RC of some kind?..

**Comment by jkinable** [comment]
Hi Igor,

yes we are currently working on finalyzing release 1.0. I expect that it
will be available within the next 2 weeks. Today we received an important
bugfix for the max-flow algorithm which has been extended considerably in
this release. Obviously, we don't want to release something that contains
known bugs :). (I'm a bit swamped with work, so I'm trying to put in every
available bit of time I have...)

**Comment by kibertoad** [comment]
Thank you very much for clarifying that!

**Comment by jsichi** [comment]
In preparation for the release, I've updated 1.0.0-SNAPSHOT with the latest code.

https://oss.sonatype.org/content/repositories/snapshots/org/jgrapht/

**Comment by jkinable** [comment]
JGraphT version 1.0.0 has been released and is available for download from our main page: http://jgrapht.org/

**Comment by kibertoad** [comment]
Great news! What is the ETA for Maven Central release?

**Comment by jkinable** [comment]
It's already there :-)

**Comment by jkinable** [comment]
let me know if anything went wrong, that is, if for some reason you cannot
access jgrapht 1.0.0 through maven.

Joris
