### ISSUE TITLE
Remove underscore identifiers KuhnMunkresMinimalWeightBipartitePerfectMatchingTest

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#290]
For the next release, we should remove the underscore identifiers from KuhnMunkresMinimalWeightBipartitePerfectMatchingTest
as they became deprecated in JDK 1.8 and will no longer be allowed in JDK 1.9
https://bugs.openjdk.java.net/browse/JDK-8061549

**Comment by jkinable** [comment]
Note: Anyone is invited to complete this task :)

**Comment by d-michail** [comment]
Fixed in pull request #328.
