### ISSUE TITLE
TODO: remove deprecated code from jgrapht-ext package

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#291]
@d-michail : would you mind to remove all deprecated code from the jgrapht-ext package? Some of the deprecated code still seems to be in use, so I don't want to break stuff by simply deleting it. Would be great if you could have a look. I would like to finish the removal of *all* deprecated code from jgrapht before we accept any new contributions.

**Comment by d-michail** [comment]
@jkinable I somehow did that in pull request #288. I will try to do it again separately as there seems to be a debate there.

**Comment by jkinable** [comment]
Resolved in pull request #293
