### ISSUE TITLE
HOW TO DISPLAY EDGES AND REMOVE COMPONENTS USING JGRAPHT

### ISSUE THREAD

**Issue by gentlemanjos1** [jgrapht/jgrapht#304]
Hello

I am working with JGRAPHT and based on the visualization demo I managed to add and also display vertexes or nodes in a JFrame using JGRAPHT; but when I try to display edges after adding them in JFrame canvas, I doesn´t work and even qhen I try to graphically remove a component from the Graph, I just does not remove anything.

So please, I need to be explained and guided about graphically (canvas) removing graph componets (edges and vertexes) and about displaying edges betwween vertexes in canvas.

Thank you everyone for your help

**Comment by jkinable** [comment]
JGraphT is an algorithmic library. For questions about graph visualization, please refer to the documentation of  jgraph/jgraphx. JGraphT only offers an adapter class to convert a JGraphT graph into jgraph/jgraphx graphs.
Also: it's ok to state your question in lower case ;)

**Comment by gentlemanjos1** [comment]
I understand.

Thanks for answering my issue.

However, could you please explain me how to work with the adapter, maybe it could help me to solve my problem.

Thanks once again for your help
