### ISSUE TITLE
Add addEdge(V sourceVertex, V targetVertex, E e) method to AbstractGraphBuilder

### ISSUE THREAD

**Issue by SSNikolaevich** [jgrapht/jgrapht#315]
Graph interface provides method, which allows to add the specified edge to graph. It's very useful in case of complex graph building. Absence of similar method in AbstractGraphBuilder class limits its and derived classes usability.

**Comment by d-michail** [comment]
Would you consider submitting a pull-request with this? 

As a sidenote, a possible conflict here is that the weighted graph builders contain a method
 `addEdge(V source, V target, double weight)`
which could cause trouble if someone does something like
`WeightedPseudograph.builder(Double.class).addEdge(1, 2, Double.valueOf(1d));`

**Comment by SSNikolaevich** [comment]
Yes, I can submit a pull-request.

Possible conflicts could be solved by changing name of proposed method. For example, to addSpecifiedEdge.
