### ISSUE TITLE
AStarShortestPath.buildPath will use equal to compare nodes

### ISSUE THREAD

**Issue by myueho** [jgrapht/jgrapht#324]
jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/AStarShortestPath.java:209
--   while (v != startVertex) {
++  while (!v.equals(startVertex)) {

**Comment by myueho** [comment]
From c408a7fa5c8f429a6a203b3870392296d2b132ad Mon Sep 17 00:00:00 2001
From: "hugo.we" <hugo.we@kakaocorp.com>
Date: Fri, 4 Nov 2016 18:19:35 +0900
Subject: [PATCH] fixes: AStarShortestPath.buildGraphPath will use equal to
 compare nodes

---
 .../java/org/jgrapht/alg/AStarShortestPath.java    |  2 +-
 .../org/jgrapht/alg/AStarShortestPathTest.java     | 64 ++++++++++++++++++++--
 2 files changed, 61 insertions(+), 5 deletions(-)

diff --git a/jgrapht-core/src/main/java/org/jgrapht/alg/AStarShortestPath.java b/jgrapht-core/src/main/java/org/jgrapht/alg/AStarShortestPath.java
index d893f79..362642d 100644
--- a/jgrapht-core/src/main/java/org/jgrapht/alg/AStarShortestPath.java
+++ b/jgrapht-core/src/main/java/org/jgrapht/alg/AStarShortestPath.java
@@ -206,7 +206,7 @@ public class AStarShortestPath<V, E>
         vertexList.add(targetVertex);
 
         V v = targetVertex;
-        while (v != startVertex) {
+        while (!v.equals(startVertex)) {
             edgeList.add(cameFrom.get(v));
             v = Graphs.getOppositeVertex(graph, cameFrom.get(v), v);
             vertexList.add(v);
diff --git a/jgrapht-core/src/test/java/org/jgrapht/alg/AStarShortestPathTest.java b/jgrapht-core/src/test/java/org/jgrapht/alg/AStarShortestPathTest.java
index 904fa13..36ec508 100644
--- a/jgrapht-core/src/test/java/org/jgrapht/alg/AStarShortestPathTest.java
+++ b/jgrapht-core/src/test/java/org/jgrapht/alg/AStarShortestPathTest.java
@@ -17,11 +17,16 @@
  */
 package org.jgrapht.alg;
 
-import org.jgrapht.*;
-import org.jgrapht.alg.interfaces.*;
-import org.jgrapht.graph.*;
+import org.jgrapht.GraphPath;
+import org.jgrapht.Graphs;
+import org.jgrapht.WeightedGraph;
+import org.jgrapht.alg.interfaces.AStarAdmissibleHeuristic;
+import org.jgrapht.graph.DefaultWeightedEdge;
+import org.jgrapht.graph.SimpleGraph;
+import org.jgrapht.graph.SimpleWeightedGraph;
+import org.jgrapht.graph.WeightedMultigraph;
 
-import junit.framework.*;
+import junit.framework.TestCase;
 
 /**
  * .Test class for AStarShortestPath implementation
@@ -172,6 +177,35 @@ public class AStarShortestPathTest
         assertEquals((int) path.getWeight(), 6);
         assertEquals(path.getEdgeList().size(), 2);
     }
+    
+    /**
+     * node equality should be checked by equals method instead of (== or System.identityHashCode)
+     */
+    public void testNodeEquality()
+    {
+        SimpleGraph<Node, DefaultWeightedEdge> graph =
+            new SimpleGraph<>(DefaultWeightedEdge.class);
+        Node n1 = new Node(0, 0);
+        graph.addVertex(n1);
+        Node n2 = new Node(1, 0);
+        graph.addVertex(n2);
+        Node n3 = new Node(2, 0);
+        graph.addVertex(n3);
+        Graphs.addEdgeWithVertices(graph, n1, n2);
+        Graphs.addEdgeWithVertices(graph, n2, n3);
+        AStarShortestPath<Node, DefaultWeightedEdge> aStarShortestPath =
+            new AStarShortestPath<>(graph);
+        // n4 equals n1.
+        Node n4 = new Node(0, 0);
+        assertEquals(n4, n1);
+        GraphPath<Node, DefaultWeightedEdge> path =            
+            aStarShortestPath.getShortestPath(n4, n3, new ManhattanDistance());
+        assertNotNull(path);
+        assertEquals(path.getEdgeList().size(), 2);
+        assertEquals(path.getStartVertex(), n1);
+        assertEquals(path.getStartVertex(), n4);
+        assertEquals(path.getEndVertex(), n3);
+    }
 
     private class ManhattanDistance
         implements AStarAdmissibleHeuristic<Node>
@@ -211,5 +245,27 @@ public class AStarShortestPathTest
         {
             return "(" + x + "," + y + ")";
         }
+        
+        @Override
+        public int hashCode()
+        {
+            return 59 * x  + y;
+        }
+
+        @Override
+        public boolean equals(Object obj)
+        {
+            if (this == obj) {
+                return true;
+            }
+            if (obj == null) {
+                return false;
+            }
+            if (!(obj instanceof Node)) {
+                return false;
+            }
+            Node node = (Node) obj;
+            return x == node.x && y == node.y;
+        } 
     }
 }
-- 
2.8.1

**Comment by d-michail** [comment]
This has been fixed in pull-request #317 currently discussed.

**Comment by jkinable** [comment]
This issue has been fixed in pull req #317. Thanks for reporting. Let us know if you encounter any other issues.
