### ISSUE TITLE
Using jgrapht in android

### ISSUE THREAD

**Issue by abangkis** [jgrapht/jgrapht#330]
Hi i'm interested in using jgrapht in my android app to replace our home made shortest path engine. 

I notice that jgrapht requires java 8, which the support is still very limited and experimental in android. Any advice to tackle this?

Thanks

**Comment by jkinable** [comment]
Unfortunately, there are only 2 options that I'm aware of:
1. Use jgrapht 0.9.1: this version still relies on Java 7
2. Wait until there's proper java 8 support in android.

Neither of these options seem very attractive to me. If you learn about
better alternatives, please let us know.

Joris Kinable

**Comment by abangkis** [comment]
Is there a big difference between 0.9.1 and 1.0.0

I will let you know if I found better alternatives.

**Comment by jkinable** [comment]
yes there's a considerable difference (mainly in terms of functionality).
Refer to the change log for details:
https://github.com/jgrapht/jgrapht/blob/master/HISTORY.md
Also note that 1.0.0 is not backward compatible with 0.9.1.

Joris Kinable

**Comment by abangkis** [comment]
Okay. So here what I've tried. 

- I download jgrapht-core source from github. 
- Add retrolambda gradle plugin on it. 
- Set source and target to java 1.8
- Rebuild
- Generate the jar.
- Include the jar in Android Project. 

I tinker with the android project here and there, see different error message, but haven't found the correct one yet. The closest one i get is to pass all build. And then get this error message:

Error:Uncaught translation error: com.android.dx.cf.code.SimException: com.android.dx.rop.cst.CstInterfaceMethodRef cannot be cast to com.android.dx.rop.cst.CstMethodRef

I feel like I'm missing a single step here.

**Comment by jkinable** [comment]
were you able to resolve this in the end?

**Comment by abangkis** [comment]
Sadly no. I had to fall back to version 0.9.2 to make it work with android.

**Comment by d-michail** [comment]
Related to #312. 

Would be interesting if someone tried to compile using the [jack](https://developer.android.com/guide/platform/j8-jack.html) compiler.
