### ISSUE TITLE
Does jgrapht support <port> elements from GraphML?

### ISSUE THREAD

**Issue by slaufmann** [jgrapht/jgrapht#332]
Hi, we are considering using jgrapht in an academic research project and were wondering whether your data structures, importers and exporters support the <port> element of the GraphML specification?

**Comment by d-michail** [comment]
Hi, 

the importer uses the 1.0 GraphML so it parses ports and hyperedges. However, as the importer constructs a graph and not a hypergraph, it ignores them. 

If you decide to test the current functionality, use the latest version from the master branch, as the importer in the 1.0 release had a bug with the xsd resolution.

**Comment by slaufmann** [comment]
Thanks for the hint.
Even though I don't need hyperedge support (or hypergraphs) I am unsure wether hierarchical graphs are supported. I tested this by using the GraphMLDemo and it seems like the importer just flattens a hierarchy of nodes.
But maybe I just did not provide a suitable Vertex class to the importer?

**Comment by d-michail** [comment]
I got confused by the title, you probably mean support for nested graphs. 

The current behaviour is indeed what you observe, we just flatten the hierarchy. However, I think the naming is kept together with the port, meaning that you can probably distinguish between the nodes.

**Comment by slaufmann** [comment]
Thanks for the clarification. Indeed I meant nested graphs.

It is sad though that importing from GraphML does not support it. Does the underlying data structure of jgrapht support nested graphs? Then it would only take changes on the XML parsing part to support this nice feature.

**Comment by d-michail** [comment]
The data structure is powerful enough to represent nested graphs. The infrastructure is all there, maybe you need try to create a custom GraphML parser.
