### ISSUE TITLE
JGRAPHT MALFUNCTION

### ISSUE THREAD

**Issue by Joseph880929** [jgrapht/jgrapht#334]
Hello

I am using JGraphT and I was doing well until three problems came up:

1. I wish to create edges without arrow shape, I wish just the line shape only, is that possible in a ListenableUndirectedWeightedGraph<String,Double>(edge class)? How to change a cell style using JGrapht?

2. When I start creating edges, the program does well until I try to create a new edge from the first N1 edge; please watch the following screenshot so you can understand better the situation:

We have 3 nodes here:
![image](https://cloud.githubusercontent.com/assets/24527472/21265834/3ebe104e-c371-11e6-982d-35dbcaeca6e5.png)

As you can see, two edges have been created without any problem:
![image](https://cloud.githubusercontent.com/assets/24527472/21265850/5621e292-c371-11e6-9fa8-01b4cc293b23.png)

But when I try to create an edge between N1 and N3 or viceversa, it doesn´t create anything:
![image](https://cloud.githubusercontent.com/assets/24527472/21265857/5ef857a2-c371-11e6-9890-5b2dcd46acf1.png)

For some reason, the program alloed me to create some edges, but when I try to create more between the not communicated nodes, it just doesn´t create anything between them: for example:
N2-N4=nothing.
N5-N4=nothing
etc...
It just stops allowing the creation of edges.
![image](https://cloud.githubusercontent.com/assets/24527472/21265868/7cfa593a-c371-11e6-915e-779e13fcfe88.png)
So I ask, what is going on here?

3. I am trying to use the DijkstraShortestPath<String,Double> in order to make a calculation, but for that I need to access and work with the edges values; I have tried using the functions:
**getPathEdgeList()**=it is supposed to return the list of edges making upthe path, but when I try to sotre it in a List<Double>, it turns into error; I have tried casting, getting array index, iterator, but nothing works forwaht I need.
**getPathLenght()**=the API says that it returns the weighted length of the path, but it only returns the number of edges that make up the path, so what is the meaning of "weighted" in this function?

I appreciate all help and guidance you can privide in order to solve these problems.

Thank you very much for your attention and sooner answer.

**Comment by jkinable** [comment]
Welcome & thanks for using JGraphT. 
A few issues:

1. Graph visualization is not part of JGraphT. This is performed by jgraph/jgraphX. Both are different projects, independent of JGraphT. JGraphT offers only basic adapter classes. Make sure that the problem doesn't reside in these projects.
2. 

> I wish to create edges without arrow shape, I wish just the line shape only, is that possible in a ListenableUndirectedWeightedGraph<String,Double>(edge class)? How to change a cell style using JGrapht? 
The ListenableUndirectedWeightedGraph is just a data structure which stores the structure of the graph, e.g. the vertices and edges. It doesn't store any graphical information. Graphical stuff is handled by jgraph/jgraphX. You need to consult the documentation of those projects to find out how to change the cell type.

3. Without seeing code I have no idea why you couldn't add an edge. There are many possible reasons. I would recommend to get rid of the interface and simply add the edge in your code: graph.addEdge(sourceVertex, targetVertex); Next you print the edges in your graph System.out.println(graph.edgeSet()); and verify whether the edge has been added. If this is the case, then the problem must lie somewhere in your visualization. Have a look at the Hello World JgraphT example: https://github.com/jgrapht/jgrapht/wiki/HelloWorld

4. Your DijkstraShortestPath problem: again, a minimal working example in code, I have no clue what might be wrong. Mentioning that "it turns into error" is not particularly useful if you don't tell us what the error is... Btw, why would you sort the Path Edge list? The first edge in the list is the first edge traversed in a path from u to v, the 2nd edge in the list is the 2nd edge in the path from u to v, and so on.

5. 

> getPathLenght()=the API says that it returns the weighted length of the path, but it only returns the number of edges that make up the path, so what is the meaning of "weighted" in this function?

This method, as correctly stated by the API, returns the weighted length of the path, that is, it returns the sum of edge weights of all the edges in the path. Obviously, if all your edges have an edge weight equal to 1, then the returned value equals the number of edges in your path. 
Note that the Dijkstra implementation also retuns a GraphPath. GraphPath records both the length (number of edges) and the weight of a path (sum of edge weights). For more details, see: http://jgrapht.org/javadoc/org/jgrapht/GraphPath.html

**Comment by jkinable** [comment]
Closing this issue. Feel free to open a new one in case you believe the issue hasn't been resolved.
