### ISSUE TITLE
possible A* bug

### ISSUE THREAD

**Issue by d-michail** [jgrapht/jgrapht#335]
@jkinable I think I came across a bug in the current A* implementation.

See the following  [branch](https://github.com/d-michail/jgrapht/tree/astarbugtest) for a simple test which fails to compute the proper shortest path.

It manifested when testing that all shortest path algorithms return the same results. I simplified it as much as possible.

**Comment by jkinable** [comment]
Meh, I don't like bugs...
I'll have a look tonight or tomorrow :).


Joris

On Mon, Dec 26, 2016 at 6:21 AM, Dimitrios Michail <notifications@github.com

**Comment by jkinable** [comment]
Confirmed bug. 
The original authors implemented this algorithm using the pseudo code from [wikipedia.](https://en.wikipedia.org/wiki/A*_search_algorithm) 
Wiki states the following:

> Remark: the above pseudocode assumes that the heuristic function is monotonic (or consistent, see below), which is a frequent case in many practical problems, such as the Shortest Distance Path in road networks. However, if the assumption is not true, nodes in the closed set may be rediscovered and their cost improved. In other words, the closed set can be omitted (yielding a tree search algorithm) if a solution is guaranteed to exist, or if the algorithm is adapted so that new nodes are added to the open set only if they have a lower f value than at any previous iteration.

This is exactly the problem. The heuristic provided is an admissible heuristic, but NOT a monotonic heuristic!
1. a heuristic is admissible if it never overestimates the cost
2. a heuristic is monotonic if for every edge (u,v) we have: h(u) <= d(u,v)+h(v).

The example you provided violates property 2. For instance, for edge: (0 : 1) with weight 0.5822723681370429, h(0): 0.7354582373430361 h(1): 0.0, we violate:
0.7354582373430361 <= 0.5822723681370429 + 0.0

Possible solutions to this bug fix:
1. Require that the heuristic provided is BOTH admissible and monotonic
2. Modify the algorithm such that it also works with admissible heuristics which are not monotonic. Ideally the user indicates whether the provided heuristic is monotonic or not. The algorithm is more efficient if a monotonic heuristic is used.

I personally prefer fix number 2.

**Comment by jkinable** [comment]
side note: most admissible heuristics are actually monotonic. As Russel and Norvig point out in Artificial Intelligence: A Modern Approach (the most commonly used AI textbook) it is challenging to come up with a heuristic that is admissible but not consistent.

**Comment by d-michail** [comment]
I also prefer fix number 2. Maybe by adding a method `boolean isMonotonic()` to the `AStarAdmissibleHeuristic` interface. 

I came across this by using the [ALT](https://www.microsoft.com/en-us/research/publication/computing-the-shortest-path-a-search-meets-graph-theory/) heuristic (pull request #317), which is a nice preprocessing technique to create an admissible function. It uses landmarks and the triangle-inequality with respect to the shortest path distances in the graph, not an embedding into Euclidean space or some other metric, which need not be present. Russel and Norvig mention this technique at the end notes of Chapter 3 (3rd edition).

My guess is that the ALT heuristic is not monotonic.

**Comment by d-michail** [comment]
I will try to incorporate a fix in pull-request #317, to handle both cases, hopefully in the next few weeks.

**Comment by jkinable** [comment]
Don't worry, I've already implemented it. Did not submit a new pull request
yet... (cooking for new years eve dinner...). I'll make it my new year's
resolution ;)

Joris

On Fri, Dec 30, 2016 at 9:17 AM, Dimitrios Michail <notifications@github.com

**Comment by d-michail** [comment]
For future reference, this pull-request triggered a bug in `FibonacciHeap` since the new implementation is reusing deleted `FibonacciHeapNode`s and the implementation of `removeMin()` in `FibonacciHeap` was not reseting the node's internal state. 

Bug fixed in pull-request #317.
