### ISSUE TITLE
Generate a random graph that's connected

### ISSUE THREAD

**Issue by jaabio** [jgrapht/jgrapht#348]
I'd like to use jgrapht to generate a random simple graph that's connected.  
I've been able to build a random simple graph using `GnmRandomGraphGenerator`, but I don't see a way to require that it be connected.  I'd be grateful for any suggestions on a good way to achieve this.  Thanks!

**Comment by d-michail** [comment]
If the number of edges is not large enough, the graph can be disconnected. You need to implement a different algorithm. 

See [http://stackoverflow.com/questions/2041517/random-simple-connected-graph-generation-with-given-sparseness](http://stackoverflow.com/questions/2041517/random-simple-connected-graph-generation-with-given-sparseness). The answer of Wesley Baugh is quite informative, containing useful links.

**Comment by jaabio** [comment]
Awesome!  Thanks for the response, and the link.
