### ISSUE TITLE
Exclude an edge in shortest path search

### ISSUE THREAD

**Issue by btcontract** [jgrapht/jgrapht#362]
When finding a shortest path (for example `DijkstraShortestPath.findPathBetween`) is it possible to instruct an algorithm to exclude an edge without removing that edge from an underlying graph?  

Something like this:

```
a -- b -- c = a,b,c
     |    |
     s -- k

now, disregard "b -- c"

a -- b -- c = a,b,s,k,c
     |    |
     s -- k
```

**Comment by jkinable** [comment]
Here are 4 different options:

1. Just delete the edge, reconstruct an instance of DijkstraShortestPath, rerun the algorithm, get the result and add the edge back. Any information stored on the edge will still be available.

2. Create a  `MaskSubgraph` which contains all the edges from the original graph except the edge you wanted to exclude. Run DijkstraShortestPath on top of the MaskSubgraph.

3. Create a regular `Subgraph`. The remaining steps are the same as under (2).

4. Set the cost of the edge you want to exclude at a very high value, rerun the ShortestPath algorithm. If the resulting path still includes the edge you wanted to exclude, then that means there's no feasible shortest path from source to sink if you exclude that edge, that is, the source and sink are in different components. 

These are the easiest solutions I can come up with.

**Comment by btcontract** [comment]
Thanks! `MaskSubgraph` fits my case best.
