### ISSUE TITLE
Feature Request: AsUnweightedGraph subclass implementing UndirectedGraph

### ISSUE THREAD

**Issue by shevek** [jgrapht/jgrapht#364]
AsUnweightedGraph implements neither DirectedGraph nor UndirectedGraph, therefore it is impossible to apply a FloydWarshallShortestPaths to it. Please make a variant of AsUnweightedGraph which implements UndirectedGraph.

**Comment by jkinable** [comment]
I don't have the code with me at the moment, but if I recall
correctly, FloydWarshallShortestPaths
takes a Graph as input. It doesn't care whether it's directed or
undirected. AsUnweightedGraph implements the Graph interface. Make sure you
are using the latest version of jgrapht though. We made some major changes
to the shortest path algorithms in the latest release.

**Comment by d-michail** [comment]
Inside the implementation of `FloydWarshallShortestPaths`, the code works only for undirected or directed graphs. Maybe we can adjust the implementation to also work in this case.

However, the following two classes would be useful:
- `AsUnweightedUndirectedGraph`
- `AsWeightedUndirectedGraph`

On a somehow unrelated issue, the following two interfaces would also be helpful in reducing unnecessary casting:
- WeightedDirectedGraph
- WeightedUndirectedGraph

**Comment by d-michail** [comment]
Actually, the `AsWeightedUndirectedGraph` is already implemented in proposed pull-request #359.

**Comment by d-michail** [comment]
I added the `AsUnweightedUndirectedGraph` in the same proposed PR. 

However, if your graph is sparse and since your weights are 1, check whether running Dijkstra multiple times is better than running Floyd-Warshall. Or even you may try running BFS multiple times.

**Comment by jkinable** [comment]
You are right, FloydWarshallShortestPaths doesn't work on graphs which are not implementing either the Directed or Undirected interface. I've merged pull request #359 , so this issue should be fixed now. Seems you are in luck @shevek :) `AsUnweightedUndirectedGraph ` and `AsWeightedUndirectedGraph` will be part of the next release. If you want them quicker, just compile a package from our master branch.
