### ISSUE TITLE
Doubt regarding serialVersionUID in IntrusiveEdge.java and DefaultEdge.java

### ISSUE THREAD

**Issue by apoorv-mishra** [jgrapht/jgrapht#375]
Hi, I read the code in IntrusiveEdge.java and DefaultEdge.java under the package ```org.jgrapht.graph```. I found that both classes have a variable ```serialVersionUID``` declared as ```private static final long``` and **contains the same value** even though the class DefaultEdge is a sublass of IntrusiveEdge class. Couldn't we declare ```serialVersionUID``` to be ```protected``` in IntrusiveEdge class and remove it from the DefaultEdge class?

**Comment by jkinable** [comment]
@jsichi any comments on this? If not, could you close this one?

**Comment by jsichi** [comment]
https://stackoverflow.com/questions/23465613/is-serialversionuid-inherited-by-subclasses-if-i-have-default-serialversionuid
