### ISSUE TITLE
How do I use this in Android / Android Studio?

### ISSUE THREAD

**Issue by Carpetfizz** [jgrapht/jgrapht#380]
The latest version of Android Studio supports Java 8 and my `build.gradle` file has

```gradle
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
How can I import this library into my project?

**Comment by d-michail** [comment]
The current version does not build for android, as the android compiler still has a few bugs.

The version in #376 works. You need to checkout that branch and build a jar. Then follow the instructions of gradle on how to include a custom jar into your project. Probably just copying the jar into the application's `libs` folder will do.

**Comment by Carpetfizz** [comment]
How do I build a jar? Sorry, I'm a Java newbie!

**Comment by d-michail** [comment]
`git clone ...`  
if the above does not make any sense, read the [documentation](https://help.github.com/articles/cloning-a-repository/)
cd to the new folder
`mvn install` 
if the above does not make any sense, read the [documentation](https://maven.apache.org/guides/getting-started/)

the jar is then located in `~/.m2/repository/org/jgrapht/jgrapht-core/1.0.2-SNAPSHOT/` or similar for other subpackages

**Comment by Carpetfizz** [comment]
Thank you for the instructions, they seemed to have worked, except for this error on compile:

![error](http://i.imgur.com/K8TN5A7.png)

**Comment by d-michail** [comment]
We just merged the android fix, which means that the master branch should also work. 

The above setup works fine in my case, I justed tested it with Android Studio 2.3. 

You should double-check that you are using the correct jar. I would propose to 
 - delete the old jar from `.m2/` 
 - run `mvn clean install` 
 - copy the jar from the `.m2/`

**Comment by Carpetfizz** [comment]
Upgraded to Android Studio 2.3 and followed above instructions, this is what I'm seeing a bunch of these errors now:

> Error:BarabasiAlbertGraphGenerator.java:138-139: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Predicate
Error:MaskEdgeSet.java:75-76: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Predicate
Error:BarabasiAlbertGraphGenerator.java:138-139: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer
Error:GusfieldGomoryHuCutTree.java:319-320: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:MaskEdgeSet.java:89-90: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Predicate
Error:AsSubgraph.java:167-168: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:AsSubgraph.java:322-323: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:AsSubgraph.java:363-364: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier
Error:AsSubgraph.java:388-389: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Supplier

**Comment by Carpetfizz** [comment]
This worked fine after setting my `minSdkVersion` to `24`. Thank you so much for your help!

**Comment by Carpetfizz** [comment]
.jar generated from latest master branch results in the following compilation error:

> Error:Execution failed for task ':app:transformClassesWithPreJackPackagedLibrariesForDebug'. > com.android.build.api.transform.TransformException: com.android.builder.core.JackToolchain$ToolchainException: Jack compilation exception

**Comment by d-michail** [comment]
The problem is that the Android compiler is buggy w.r.t. Java 8 features. However, we cannot check every time we do some changes if the Android compiler works! 

Your best option is to find a previous version that works and checkout that commit.

I will make an effort to check, before the next official release, whether the project works on Android but cannot really promise anything.

**Comment by Carpetfizz** [comment]
Okay, thank you for your help.
