### ISSUE TITLE
MaximumWeightBipartiteMatching behaves incorrectly for fractional weights

### ISSUE THREAD

**Issue by ImLiar** [jgrapht/jgrapht#384]
If edge weight is < 1 `MaximumWeightBipartiteMatching` drops first(?) edge from matching.

I believe it happens because of following cast:
https://github.com/jgrapht/jgrapht/blob/0f95bc63b501b4d521dd80412ba0add685ae617b/jgrapht-core/src/main/java/org/jgrapht/alg/matching/MaximumWeightBipartiteMatching.java#L120

It's very confusing because method `setEdgeWeight` accepts doubles:
https://github.com/jgrapht/jgrapht/blob/0f95bc63b501b4d521dd80412ba0add685ae617b/jgrapht-core/src/main/java/org/jgrapht/graph/AbstractBaseGraph.java#L497

**Comment by jkinable** [comment]
Looks indeed awkward: edge weights are doubles, not longs. 
Can you post a code example where the result is wrong (also state the correct result)? I'll give it a try when I get home.

**Comment by jkinable** [comment]
@gahokas could you look into this?

Another issue: the Runtime complexity you mentioned in your description (O(V|E|^2)) seems off. Nowhere in the LEDA documentation I could find a runtime complexity of O(V|E|^2). In fact, wikipedia states that Max weight bipartite matchings can be solved in O(EV^2), so your runtime complexity doesn't seem very good?

**Comment by gahokas** [comment]
Yes, a restriction of the current implementation is that the edge weights must be positive integers. This is stated in the Javadoc but I agree it's not obvious. We could add some error checking to the constructor to help enforce this.

The algorithm as implemented is not the most efficient known version of Maximum Weight Bipartite matching. However, it was the most straightforward to implement, still polynomial time, and was sufficiently fast enough for my purposes when I wrote it. I don't know of any publicly available implementation of the fastest (or any other) version of the algorithm.

**Comment by d-michail** [comment]
The LEDA book has a very nice algorithm which uses a Dijkstra-like implementation in order to find tight edges (zero reduced cost) paths. It would be nice to implement that one in the future.

The current implementation is somewhat inefficient, especially method 'isVertexMatched()' which iterates over the whole matching in order to check whether a vertex is matched or not.
