### ISSUE TITLE
Iterable algorithm return objects

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#386]
Several algorithms return objects over which we could iterate, e.g.:

- Matching
- SpanningTree
- VertexCover

Instead of writing: for(E e : matching.getEdges()), it would be intuitive and more concise to simply write for(E e : matching). To do this however, `MatchingAlgorithm.Matching` would have to implement `Iterable`. Problem is that `MatchingAlgorithm.Matching` is an Interface and hence cannot implement another interface (it can only extend an interface, but it would be ugly to extend the iterable interface). The solution to this would be to make `MatchingAlgorithm.Matching` an Abstract class instead. Similar for other return object classes.

Any opinions on this matter?

**Comment by jsichi** [comment]
I don't think having an interface which extends Iterable is ugly, so if we want this, then we should just do that.

**Comment by d-michail** [comment]
I agree with John, extending an `Iterable` is not ugly. You can even override the `iterator()` method in order to adjust its javadoc.
