### ISSUE TITLE
Depth-Limited DepthFirstIterator

### ISSUE THREAD

**Issue by nathanila** [jgrapht/jgrapht#391]
I would like to specify a minimum and maximum depth for DepthFirstIterator.  Any node which is greater than the maximum depth from the start vertex will not be visited.  Any node which is less than the minimum depth from the start vertex will not be reported as visited (but of course has to be visited in order to arrive at vertexes that meet the minimum depth constraint).

**Comment by jkinable** [comment]
First define depth. Are you talking about tree graphs or general graphs? For general graphs, 'depth' is not well-defined. Either way, what you are asking cannot be done with the default DepthFirstIterator. It's not hard to implement this yourself though.

1. Create a depth map `Map<V,Integer> depth` which records for each vertex its depth (starting from some SOURCE vertex). Computing this map is easy. Simply use the `DijkstraShortestPath` algorithm on your graph, with all edge weights equal to 1. `DijkstraShortestPath` can give you a `SingleSourcePaths` object which gives you all the shortest paths from your SOURCE vertex to any other vertex. Notice that your graph doesn't need to be 'weighted': the edge weights of any graph are 1 by default.
2.  Implement a custom iterator which uses the `DepthFirstIterator`. Something like this:

```
public class BoundedDFSIterator implements Iterator<V>{
  Map<V,Integer> depthMap=...;
  DepthFirstIterator<V> dfs=...;

  /* Next vertex to return */
  V next=null;

  public BoundedDFSIterator(Map<V,Integer> depthMap){ 
    ...
    next=getNext();
  }

  public V hasNext(){
    return next != null;
  }

  public V next(){
    V v=next;
    next=getNext();
    return v;
  }

  private V getNext(){
    next=null;
    while(next==null && dfs.hasNext()){
      V v =dfs.next();
      if(deptMap.get(v) >= MIN_DEPTH && deptMap.get(v) <= MAX_DEPTH)
        next=v;
    }
  }
}
```

**Comment by nathanila** [comment]
Depth is the number of edges traversed to get from some SOURCE vertex to the given vertex.  Consider a depth-first search starting from a SOURCE vertex.  While the depth-first search is traversing the graph, each time it encounters a vertex, the vertex is given a depth based on how many vertexes are in the LIFO queue of the depth-first search.

My thought is to override `DepthFirstIterator` and then check `getStack().size()` to enforce the minimum and maximum depth.

**Comment by jkinable** [comment]
This doesn't sound like a good idea. Take for example the following cyclic graph with vertex set V={1,2,3,4} and edge set E={(1,2),(2,3),(3,4),(4,1)}. Let's assume that the dfs iterator starts at vertex 1 and encounters the vertices in the order 1,2,3,4. In this case, vertex 4 would be at 'depth' 3. If by chance the dfs iterator would have walked the vertices in the reverse order, namely 1,4,3,2 then vertex 4 would be at 'depth' 1. This is not consistent. Therefore I suggested to use the shortest path metric with edge costs equal to 1. Using a shortest path metric starting at vertex 1, vertices 2 and 4 are both at depth 1, and vertex 3 is at depth 2 (here the depth equals the number of hops on the shortest path to the source node).
