### ISSUE TITLE
Unspecified Vertex Graph

### ISSUE THREAD

**Issue by nathanila** [jgrapht/jgrapht#392]
Please create a graph which doesn't require specifying all of the vertexes or edges in advance.  The graph must have at least 1 vertex specified.  The graph calls a supplied `Function<V, Set<E>>` to obtain the edges for a given vertex.  Thus, one can create a (infinite) graph without having to use a lot of memory.  Of course, some methods will require traversing all of vertexes in the graph in order to return a result (e.g. containsVertex(), vertexSet()).

One could implement Graph; however, depending upon the implementation this may or may not be compatible with a lot of algorithms.

**Comment by jkinable** [comment]
I'm afraid I don't understand what you need. None of the graphs requires you to specify all vertices/ edges upfront. 
`Graph<Integer,DefaultEdge> graph=new SimpleGraph<>(DefaultEdge.class);`
This simply creates an empty graph. No need to specify vertices/edges. You can add those later whenever you want.

**Comment by nathanila** [comment]
Here's an example that you can probably relate to.  It is not my current use case.

Let's say I were to create a graph of all of the pages on a website.  With my current understanding of the JGraphT objects, I would have to add to the graph all of the pages as vertexes and add to the graph all of the links as edges.  Depending on the size of the website, it could take a long time and a lot of memory to create such a graph.

Instead, I would like to add 1 (or more) webpages as a vertexes to the graph.  I would also like to specify a `Function<URL, Set<URL>>` which takes the `URL` of a webpage and returns a `Set` of `URL`s which that webpage links to.  Then, `DepthFirstIterator` will trigger the crawling of the site as edges are discovered and traversed.  The graph should optionally remember the vertexes discovered and the edges.

I figure I could write such a graph object and implement `Graph` or some other class.  I just thought this would be a useful addition to the library.

**Comment by jkinable** [comment]
I see your point now. This seems to be very hard to capture in some generic sense. There's no apparent class template we can build for that. You can however easily implement your own graph class, which extends the super class `Graph`. All our algorithms are guaranteed to run on a `Graph`, so your earlier statement, 

> however, depending upon the implementation this may or may not be compatible with a lot of algorithms
is not correct :). Obviously, depending on how you implement your graph, the performance will be lower than using any of our build-in graph types.
