### ISSUE TITLE
incomingVertexesOf(V vertex) and outgoingVertexesOf(V vertex)

### ISSUE THREAD

**Issue by nathanila** [jgrapht/jgrapht#393]
Similar to `incomingEdgesOf` and `outgoingEdgesOf`, please add methods `Set<V> incomingVertexesOf(V vertex)` and `Set<V> outgoingVertexesOf(V vertex)`.  `incomingVertexesOf` returns a `Set` of all the vertexes which are the target of an edge from the given vertex.  `outgoingVertexesOf` returns a `Set` of all the vertexes which are the source of an edge towards the given vertex.

**Comment by jkinable** [comment]
These function names don't make sense. There's no definition of a 'incoming vertex of another vertex' in graph theory. 
Have a look at the `Graphs` class. This class contains a number of functions that you may find useful, including:

- `neighborListOf`
- `successorListOf`
- `predecessorListOf`

**Comment by nathanila** [comment]
Those are what I am looking for.  Thanks!
