### ISSUE TITLE
Does jgrapht support Suurballe's algorithm?

### ISSUE THREAD

**Issue by BoyuanYan** [jgrapht/jgrapht#405]

**Comment by jkinable** [comment]
Use the KShortestPath algorithm. It's been a while since I looked at the
implementation of this algorithm, but it will do what you need. Reminds me
that I need to revise the K-{vertex/edge} disjoint shortest path algorithms.

br,

Joris

**Comment by BoyuanYan** [comment]
And another question, What is the classic algorithm to find two disjoint paths between two pairs of vertices in a graph. I've searched scholar.google, and found a paper named "197801-JACM-Finding Two Disjoint Paths Between Two Pairs of Vertices in a Graph", but don't know how to judge if it is classic enough.

**Comment by jkinable** [comment]
I'm not sure what you mean by "classic enough"? Why would that be relevant?
Suurballe's algorithm is indeed a well-known algorithm to find vertex
disjoint paths of minimum total sum in a graph. If you want to know more
about this subject, I would recommend reading the book Survivable Networks:
Algorithms for Diverse Routing by Ramesh Bhandari. It's actually a very
nice, easily readable book. It gives various algorithms for this particular
problem, their history, and some pro's/con's to each algorithm.

br,

Joris Kinable
