### ISSUE TITLE
NeighborIndex needs revisions

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#411]
NeighborIndex and DirectedNeighborIndex need to be revised in the same way Graph was revised. I would propose to have a single NeighborCache with functions such as neighborsOf() successorsOf() and predecessorsOf(), similar to the functions `neighborListOf()`, `successorListOf()` and `predecessorListOf()` in `Graphs`.

**Comment by jsichi** [comment]
Makes sense.  Feels like we ought to move to package alg.util as well, since this indexing is intended to support algorithm implementations.

**Comment by jkinable** [comment]
Thanks to @besza, this got fixed in PR #438
