### ISSUE TITLE
Inefficient Map operations in FastLookupDirectedSpecifics

### ISSUE THREAD

**Issue by shevek** [jgrapht/jgrapht#415]
https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/graph/specifics/FastLookupDirectedSpecifics.java#L127
https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/graph/specifics/FastLookupDirectedSpecifics.java#L139

Don't do a `containsKey()` followed by a `get()`. Do a `get()` followed by a `!= null`

**Comment by jkinable** [comment]
Fixed in #418. Thanks for reporting.
