### ISSUE TITLE
Specify DOTExporter graph attributes

### ISSUE THREAD

**Issue by hadronzoo** [jgrapht/jgrapht#421]
It would be useful to be able to specify global graph attributes (like `overlap = false` and `splines = true`) in the DOTExporter. Currently, it appears that it only supports vertex and edge attributes.

**Comment by shevek** [comment]
https://github.com/shevek/graphviz4j is fully featured graphviz builder for jgrapht. There are lots of them. Mine is clearly the best for reasons I can't quite articulate.

**Comment by hadronzoo** [comment]
@shevek thanks for the library! I'll try it out. Since JGraphT supports dot export, I think it would still be useful to add graph properties.

**Comment by d-michail** [comment]
Basic support added in #428.
