### ISSUE TITLE
Identify the vertices whose removal will make the graph unconnected

### ISSUE THREAD

**Issue by huanfachen** [jgrapht/jgrapht#422]
I am working with a SimpleWeightedGraph, which contains of several connected subgraphs. For each subgraph, I want to know the vertices whose removal will make the subgraph unconnected. Is there an efficient way to achieve this goal in jgrapht?
I am considering using AsSubgraph, ConnectivityInspector and GraphListener. For each subgraph, remove each vertex and check ConnectivityInspector.isGraphConnected(). However, I am not sure how to implement this, and how efficient it is.
Thanks for any suggestions!

**Comment by jkinable** [comment]
What you are looking for is an algorithm which finds articulation points,
also known as cut vertices. An articulation point is a vertex, such that
removal of that vertex increases the number of connected components in the
graph. A typical algorithm to find articulation points in a graph, is a
simple, modified DFS which runs in O(V+E).
So here's what you could do:
1. Use the ConnectivityInspector to find all connected components
2. For each connected component, run a modified DFS to find the
articulation points.
The resulting runtime complexity is O(V+E), so very efficient. Even better
would be to combine step 1 and 2 into one The latter can be achieved by
modifying the ConnectivityInspector.

I would not use the approach you describe: removing each vertex one by one,
and checking whether the graph is still connected. This would take
O(V*(V+E)) time, which is quite a waste.

We currently don't have an algorithm to find articulation points (this
would actually be useful to have). Implementing the modified DFS is however
easy. See for instance:
-http://www.eecs.wsu.edu/~holder/courses/CptS223/spr08/slides/graphapps.pdf
-
https://stackoverflow.com/questions/15873153/explanation-of-algorithm-for-finding-articulation-points-or-cut-vertices-of-a-gr
-
http://www.geeksforgeeks.org/articulation-points-or-cut-vertices-in-a-graph/

just for reference: in graph theory, the edge equivalent to articulation
points is called a bridge. A bridge in a graph is an edge such that
deleting the edge increases the number of connected components.

**Comment by jkinable** [comment]
It turns out, this functionality is already present in jgrapht! Simply use:

BiconnectivityInspector.getCutpoints().

That's all there is to it :).


br,


Joris Kinable

**Comment by huanfachen** [comment]
Thanks for the great suggestion! This function works in my code. BiconnectivityInspector.getCutpoints()

**Comment by jkinable** [comment]
Pull request #424 addresses an enhancement related to the cut vertices. The BiconnectivityInspector can now iterate over a variety of graphs (including directed and disconnected graphs). Moreover, the BiconnectivityInspector computes both bridges and cut vertices.
