### ISSUE TITLE
Feature Suggestion: Minimum cost perfect matching algorithm

### ISSUE THREAD

**Issue by simlu** [jgrapht/jgrapht#426]
I've ported EdmondsBlossom algorithm with Maximum Weighted Matching to Java here:
https://github.com/simlu/EdmondsBlossom

Should not be too hard to bring this over into jgrapht now.

I'm also looking for advice on how we can implement the optimizations mentioned in Blossom V:
https://cstheory.stackexchange.com/questions/38897/optimizing-maximum-weighted-matching-edmonds-blossom

**Comment by jsichi** [comment]
@Toptachamann is currently working on this for his Google Summer of Code project.

You can find his WIP here:  https://github.com/jgrapht/jgrapht/pull/595
