### ISSUE TITLE
Enable parsing of non fully graphml schema compliant files

### ISSUE THREAD

**Issue by dadrus** [jgrapht/jgrapht#434]
I'm using jgrapht to manage contents of a Neo4j instances (see [dadrus/jpa-unit](https://github.com/dadrus/jpa-unit/tree/7bebbea753bd3e614c7e02d27058589d04e4f58b)) and would like to use the `GraphMLImporter` directly instead of an own implementation. This is unfortunately not possible due to multiple limitations of the current  jgrapht `GraphMLImporter` implementation. One of these is the graphml schema verification which is always on. The tools around Neo4j however, most prominent one is [APOC](https://neo4j-contrib.github.io/neo4j-apoc-procedures/), do not strictly comply to the graphml schema (APOC adds additional xml attributes to the elements, e.g. like `label`). This way usage of the corresponding graphml files is not possible with jgrapht `GraphMLImporter`.

My suggestion here is to add a configuration parameter to `GraphMLImporter` to enable or disable the schema verification. Disabling schema verification would also boost the performance  of the importer for bigger graphml files (may address #417).

**Comment by d-michail** [comment]
I will take a look. Could you provide me with a small example (perhaps a link) of APOC's graphml output?

**Comment by dadrus** [comment]
Sure. Given a graph created using the following cypher query  to create a small graph consisting of three nodes and two edges

```bash
create (d:Person:ENTITY {id: 1, name: "Dimitrij"})-[:daughter]->(:Person:ENTITY {id: 2, name: "Milana"}), (d)-[:daughter]->(:Person:ENTITY {id: 3, name: "Daliah"});
```
and then exporting it with the following APOC command
```bash
call apoc.export.graphml.all("/tmp/db.graphml", {useTypes:true});
```

one will get the following (not fully compliant) graphml document:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		 xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
	<key id="name" for="node" attr.name="name" attr.type="string"/>
	<key id="id" for="node" attr.name="id" attr.type="long"/>
	<graph id="G" edgedefault="directed">
		<node id="n45" labels=":Person:ENTITY">
			<data key="labels">:Person:ENTITY</data>
			<data key="name">Dimitrij</data>
			<data key="id">1</data>
		</node>
		<node id="n46" labels=":Person:ENTITY">
			<data key="labels">:Person:ENTITY</data>
			<data key="name">Milana</data>
			<data key="id">2</data>
		</node>
		<node id="n47" labels=":Person:ENTITY">
			<data key="labels">:Person:ENTITY</data>
			<data key="name">Daliah</data>
			<data key="id">3</data>
		</node>
		<edge id="e34" source="n45" target="n46" label="daughter">
			<data key="label">daughter</data>
		</edge>
		<edge id="e35" source="n45" target="n47" label="daughter">
			<data key="label">daughter</data>
		</edge>
	</graph>
</graphml>
```

As you can see, there are two issues:
* `label` attribute is present on the edge and `labels` attribute on the node element. This is not defined by the GraphML format. And will definitely lead to schema validation errors.
* `<data>` elements with a `key=label`, respectively `key=labels` attribute is present on `<node>` and `<edge>` elements for which no `<key>` elements are present.

The second issue can easily be solved by just adding the two lines shown below regardless the size of the graph. The first one will however need a change on each and every element in the GraphML file if the parser is strict in its behavior and performs a schema validation.

```xml
<key id="label" for="edge" attr.name="label" attr.type="string"/>
<key id="labels" for="node" attr.name="labels" attr.type="string"/>
```

**Comment by dadrus** [comment]
Following change to `GraphMLImporter.createXMLReader` would solve the issue:

```java
private XMLReader createXMLReader(final boolean withSchemaValidation) throws ImportException {
        try {
            // create parser
            final SAXParserFactory spf = SAXParserFactory.newInstance();
            spf.setNamespaceAware(true);
            if (withSchemaValidation) {
                spf.setSchema(createSchema());
            }
            final SAXParser saxParser = spf.newSAXParser();

            // create reader
            return saxParser.getXMLReader();
        } catch (final Exception se) {
            throw new ImportException("Failed to parse GraphML", se);
        }
}

private Schema createSchema() throws ImportException, SAXException {
        final SchemaFactory schemaFactory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);

        // load schema
        final InputStream xsdStream = Thread.currentThread().getContextClassLoader().getResourceAsStream(GRAPHML_SCHEMA_FILENAME);
        if (xsdStream == null) {
            throw new ImportException("Failed to locate GraphML xsd");
        }
        final InputStream xlinkStream = Thread.currentThread().getContextClassLoader().getResourceAsStream(XLINK_SCHEMA_FILENAME);
        if (xlinkStream == null) {
            throw new ImportException("Failed to locate XLink xsd");
        }
        final Source[] sources = new Source[2];
        sources[0] = new StreamSource(xlinkStream);
        sources[1] = new StreamSource(xsdStream);
        return schemaFactory.newSchema(sources);
}
```

Then, to retain API compatibility, one could introduce an additional constructor, which would take an additional `boolean` argument and use the corresponding variable in a call to `createXMLReader`  in the `importGraph` method.

**Comment by d-michail** [comment]
I updated PR #436 with support for disabling the validation. I had to add a few more checks for null, etc to at least handle some common errors. Test it and let me know. Thanks

**Comment by dadrus** [comment]
Since the PR #436 has been integrated and already contains the requested functionality, I'm closing this one
