### ISSUE TITLE
jgrapht import functionality does not implement type awareness

### ISSUE THREAD

**Issue by dadrus** [jgrapht/jgrapht#435]
I'm using jgrapht to manage contents of a Neo4j instances (see [dadrus/jpa-unit](https://github.com/dadrus/jpa-unit/tree/7bebbea753bd3e614c7e02d27058589d04e4f58b)) and would like to use the `GraphMLImporter` directly instead of an own implementation. This is unfortunately not possible due to multiple limitations of the current  jgrapht `GraphMLImporter` implementation (see also #434) and the interfaces around it. One of these is the inability of `GraphMLImporter` to preserve the data types as defined in `attr.type` attribute of a `<key>` element. Actually `GraphMLImporter` does not support them at all, thus all attributes of any graph element are of type `String`. And since both `VertexProvider` and `EdgeProvider` do not enable to address any type awareness in their `buildVertex`, respectively `buildEdge` methods, the corresponding information is lost. Without type information however, import into Neo4j results in a graph with all attributes being of type String, which breaks the entire model and makes imports through jgrapht incompatible with command line tools around Neo4j.

One approach to address this limitation would be to change the `VertexProvider` and `EdgeProvider`  interfaces from

```java
public interface VertexProvider<V> {
    V buildVertex(String label, Map<String, String> attributes);
}

public interface EdgeProvider<V> {
    V buildEdge(String label, Map<String, String> attributes);
}
```

to

```java
public interface VertexProvider<V> {
    V buildVertex(String label, Map<String, Object> attributes);
}

public interface EdgeProvider<V> {
    V buildEdge(String label, Map<String, Object> attributes);
}
```

and let the `GraphMLImporter` handle the `attr.type` attributes. You can find a working implementation in [dadrus/jpa-unit GraphMLReader](https://github.com/dadrus/jpa-unit/blob/7bebbea753bd3e614c7e02d27058589d04e4f58b/neo4j/src/main/java/eu/drus/jpa/unit/neo4j/graphml/GraphMLReader.java). Same limitations apply to all other `GraphImporter` implementations (not all formats define the possibility to describe attribute types. This however can be the addressed as well). 

That means, at least for my project, each new format I would like to support for Neo4j (or other graph db, to be supported in the future), I will have to copy&paste parts of jgrapht implementation and maintain it by myself. I hope the suggested enhancements will however be of value for the community as well.

**Comment by d-michail** [comment]
Thanks for the suggestions. 

Note however that copy-pasting code from open source projects without at least keeping the copyright notice is definitely not the right way to go. You should keep the original copyright and also document that you have performed additional changes.

**Comment by dadrus** [comment]
Copy&paste was maybe the wrong wording. Because of the modifications made it is by far not the original code any more. But I fully agree with you.

Coming back to this request. How viable do you see my request? If you like I can file pull request to discuss the idea. I cannot however foresee how wide the suggested enhancement would reach (thus the above question about the viability)

**Comment by d-michail** [comment]
I added a PR with support for types. We prefer to keep the value as String and provide an additional field for the type and let the user do any parsing.

In case you decide to keep your version of the code, please use our copyright notice and additionally add your own which states clearly that you have done significant changes. The quantity of the change does not alter the copyright.

**Comment by dadrus** [comment]
The approach to keep the value as String and provide additional field for type gives the user more freedom on how to convert the Stirng value to the required type. I like this approach even more than my suggestion.

As long as this PR has not found its way into an official release, I will have to keep my version of the code. Your copyright notice is included.

Thank you again.
