### ISSUE TITLE
Multigraph should allow adding an edge which is equal to an existing edge

### ISSUE THREAD

**Issue by patric-r** [jgrapht/jgrapht#437]
Currently, calling `addEdge()` on a `Multigraph `invokes `containsEdge()` which is based on `equals()/hashCode()` of the edge. If this method returns true, the adding is rejected.

As a result you can only use a `Multigraph `with edge instances which are not equal
which seems to be an unnecessary limitation for a `Multigraph `(while it's perfect for a `SimpleGraph`).

**Comment by d-michail** [comment]
The implementation follows standard definitions in graph theory. It is not a limitation. Try using edge weights (weighted graphs) if you feel that a certain edge is more important than others.

**Comment by patric-r** [comment]
In my case, edges should be treated equal if they're connecting the same vertices. They do not have any other property which distinct them from other edges (connecting the same vertices).

Citing [Wikipedia - Multigraph article](https://en.wikipedia.org/wiki/Multigraph):

_"Edges without own identity: The identity of an edge is defined solely by the two nodes it connects. In this case, the term "multiple edges" means that the **same edge can occur several times between these two nodes**."_

IMHO, as result, such an "Multigraph with edges without own identity" cannot be fully modeled with jgrapht.

**Comment by jkinable** [comment]
Can you give an example of something you cannot do algorithmically? Often
there are many trivial workarounds. For instance, if you are having edges
without identity, you could simply add a single edge (u,v) once, and then
have a counter on this edge which counts how often that edge is present. If
that doesn't suffice, then there may be various ways to transform a
multigraph where edges do not have an identity to an equivalent version
where the edges do have an identity.

Bear in mind that a generic graph library is designed to handle the most
commonly occurring cases as efficient as possible. Obviously, this comes
with limitations. It unfortunately is impossible to have a generic library
which can handle every possible situation, and which is also highly
efficient. A classical example would be the representation of mixed graphs
(graphs with both edges and arcs).

**Comment by d-michail** [comment]
As @jkinable points out, there are quite a few definitions and would complicate matters to actually try to support all of them. 

Moreover, there are standard reductions between the different definitions. For example representing multi-sets can be done by keeping each element together with a count of its multiplicity. In the multi-graph case, you can use an edge and use its weight to keep the multiplicity (hence weighted graphs). Or you can define a custom edge class which would contain the multiplicity as a field.

**Comment by patric-r** [comment]
Thank you for your comments.
If we all agree that such kind of a Multigraph is currently not supported with jgrapht, I'm fine with it.
Please consider this as an enhancement request instead. At least, this limitation should be documented somewhere.


Now I'd like to discuss my workaround options.
I experimented with the @jkinable 's approach that my custom edge class should include a counter to reflect the multiplicity/cardinality. 

If I implement `hashCode()`/`equals()` to cover this counter field I'm still not able to model such a Multigraph, e.g.:
`a<--2-->b<--2-->c`

Because edge `(a,b,2)` is equal to edge `(b,c,2)` (in the sense of `equals()`), jgrapht rejects the adding of `(b,c,2)`.
So beside the "multiplicity"-limitation, jgrapht does not allow to add an edge which is "equal" to an existing edge - even if it's connecting different vertices.

**Comment by d-michail** [comment]
Can you please describe your use case? 

As I pointed out in both my previous comments, a possible solution is to use a weighted graph. There are classes in jgrapht like [WeightedMultigraph](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/graph/WeightedMultigraph.java) where together with an edge you also have a double value which is called the edge weight. You can get and set that value using methods `graph.getEdgeWeight(e)` and `graph.setEdgeWeight(e, weight)`.

A second approach is to use a custom edge class which would contain an extra counter, but do not override equals. If you want to add an edge a second time, you just increment the counter. If you want to remove it you decrease the counter. If the counter drops to zero, then you also remove the edge from the graph.

A third way is to externally map (using a [Map](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html)) between having and not having an identity. 

There are probably many other ways depending on your exact use case.

**Comment by jensdietrich** [comment]
As @d-michail  asked for a use case, here is mine:  build a graph for static program analysis to model dependencies between classes. Dependencies are labelled by types (an enum): SUPERCLASS, RETURN_OF_A_METHOD, TYPE_OF_A_FIELD etc.  This is then modelled by a custom edge class that has one of those values as a label.  The graph is a multigraph (it is of interest for the analysis that the same pair of classes can have dependencies of several types).  

A possible solution to the problem discussed in this thread is to implement a custom edge class subclassing DefaultEdge with equals / hashCode using the label, the source and the target, using the references the superclass provides to source and target.
