### ISSUE TITLE
GmlImporter is incomplete

### ISSUE THREAD

**Issue by sbaier1** [jgrapht/jgrapht#439]
The GmlImporter does not satisfy the entire specification of the format. The Lexer seems to properly recognize the language, however the GmlImporter does not fill the attribute map (it creates an empty HashMap). It is legal to define additional attributes like so: 
```
graph [
   node [ 
     id 1
     myAttribute "value"
   ]
   node [
     id 2
     anotherAttribute "anotherValue"
   ]
   edge [
     source 1
     target 2 
     weight 2.0
     edgeAttribute "anotherValue"
   ]
 ]
```

**Comment by d-michail** [comment]
Hi!  What you are describing is supported by the importer but restricted to string values. See [GmlImporterTest#testAttributesSupport](https://github.com/jgrapht/jgrapht/blob/133769f25e6cd6f02c3daf1060f5ea9e51b53dd3/jgrapht-io/src/test/java/org/jgrapht/io/GmlImporterTest.java#L599). Do you need it also for integer values?

**Comment by d-michail** [comment]
Added the necessary changes along with some unit tests in #436. Thanks for reporting this.

**Comment by d-michail** [comment]
Closing this one since #436 was merged.
