### ISSUE TITLE
Please publish Automatic-Module-Name manifest entries

### ISSUE THREAD

**Issue by io7m** [jgrapht/jgrapht#448]
Hello!

It'd be great if `jgrapht` published `Automatic-Module-Name` entries in the jar manifest for each module. This would assign the modules stable names to be used in (modular) Java 9 projects.

**Comment by jkinable** [comment]
Although I'm not familiar yet with Java 9 modules, this should be relatively easy (simply add one line to our pom files): http://branchandbound.net/blog/java/2017/12/automatic-module-name/
For the module name, I think org.jgrapht makes sense?
Any idea which POM files we should include this module name code (all?)?

**Comment by jkinable** [comment]
@io7m would you be willing to submit a pull request which takes care of this issue?

**Comment by io7m** [comment]
Hi.

Apologies, it seems like your response got buried in amongst all of the noise I receive from GitHub. I can certainly submit a PR that should address your questions.

**Comment by io7m** [comment]
To clarify: I originally mentioned adding `Automatic-Module-Name` entries, but I think that full modularization is possible once a couple of your dependencies have been updated.

**Comment by jkinable** [comment]
@io7m the issue with the `javax.annotation.Generated` has been fixed. The project now builds correctly using JDK9. It still seems a little early to enforce JDK9 to build the project (after all, JDK9 was only officially released a few months ago). Would it be possible to implement the full modularization without requiring JDK9?

**Comment by io7m** [comment]
@jkinable Yes, modularization is possible without requiring JDK 9, it's just slightly more complicated. Not a problem!
