### ISSUE TITLE
Regarding paths obtained from getAllPaths - not getting paths of shorter lengths

### ISSUE THREAD

**Issue by karanthpallavi** [jgrapht/jgrapht#451]
Hello,

In my application, have called getAllPaths with maxPathLength to be 8,
Am not getting paths of length 4,
Only when i call with maxPathLength parameter to be 4,
i get paths of length 4.
May i know how to fix this?
Thanks

**Comment by karanthpallavi** [comment]
Can i get some help on this?
Urgent please

**Comment by jkinable** [comment]
You'll have to be a lot more specific:
- which class are you using?
- what code do you have?
I presume you are using `AllDirectedPaths`? Note that the length of the path equals the number of edges in the path, not the sum of the weights of the edges in that path.
I recommend to create a test class in which you test the behavior of this class on a small test graph to see whether the results are confirm your expectations.

**Comment by karanthpallavi** [comment]
Yes, am using AllDirectedPaths, and i assume maxPath length is the maximum number of edges which can be a path. Thanks, will check with a small graph...
