### ISSUE TITLE
Feature Request: lowest common ancestor algorithms for trees

### ISSUE THREAD

**Issue by AlexandruValeanu** [jgrapht/jgrapht#453]
I have noticed that Tarjan's algorithm is implemented but that is not very efficient if you run the queries one by one. There are some nice algorithms for solving the lca problem for trees that provide O(log n) or even O(1) per query.

I was thinking about implementing some and I was curious if this is something that would be interesting to have.

**Comment by d-michail** [comment]
Definitely! We are also missing some cleanup and unification work (interface design, etc) regarding LCA algorithms.

**Comment by AlexandruValeanu** [comment]
Great! I'll start working on that.

Yes, I've seen that there is no `LcaAlgorithm` interface but adding one is not hard. 
The problem is that all lca algorithms should be in some package. But this would mean that `Naive` and `Tarjan` has to move which  is a major problem. Do you have any suggestions on how to structure all lca-related stuff?

**Comment by rahul6789sharma** [comment]
HI 
Recently i have started using this great library in my project. LCA algorithm is good to have. and even it is better can we have some algorithm to find all the leaf nodes of given vertex.
i am not sure if it is already available

**Comment by d-michail** [comment]
@AlexandruValeanu We are slowly moving stuff into their respective packages. If you contribute more LCA algorithms, it would definitely make sense to have a separate `lca` package. 

Note that we use a strict 2 releases deprecation policy. We first deprecate a class in one release, and then remove it in the next. If you want to move a class, you deprecate the class and add a new class at the other location. After the next release, we will remove the deprecated class.

**Comment by LightnessOfBeing** [comment]
Hi @d-michail. I'm interested to resolve that issue. I wanted to ask: what methods except findLca(V a, V b) and findAllLcas(V a, V b) should be presented in the LCA interface? 

About additional LCA algorithms: I want to implement Binary Lifting algorithm with O(nlogn) on preprocessing and O(logn) on query. Are you interested in it? Or it would be better to implement Farach-Bender first (because it's faster <O(n), O(1))?

**Comment by AlexandruValeanu** [comment]
Hi Kirill,
I am writing to let you know that I have already started working on that idea and I'll soon be sending a comprehensive proposal to explain my ideas on that topic.
Best regards, 
Alexandru Văleanu 

   On Tuesday, February 13, 2018, 5:55:33 PM GMT, Kirill Vishnyakov <notifications@github.com> wrote: 
 
 
Hi @d-michail. I'm interested to resolve that issue. I wanted to ask: what methods except findLca(V a, V b) and findAllLcas(V a, V b) should be presented in the LCA interface?

About additional LCA algorithms: I want to implement Binary Lifting algorithm with O(nlogn) on preprocessing and O(logn) on query. Are you interested in it? Or it would be better to implement Farach-Bender first (because it's faster <O(n), O(1))?
