### ISSUE TITLE
getting All parents and child nodes of given vertex 

### ISSUE THREAD

**Issue by rahul6789sharma** [jgrapht/jgrapht#456]
HI 
I want to know is there any API available to get all the parents of child nodes of a given vertex?

**Comment by AlexandruValeanu** [comment]
It is not really an issue.

Check `incomingEdgesOf` and `outgoingEdgesOf`.

**Comment by rahul6789sharma** [comment]
HI
Yes this is not an issue, my question is can we find all the successor (not only immediate successor ) or predecessor (not only immediate successor).
I know that there is api to find this "

> org.jgrapht.Graphs.successorListOf

"  and "

> org.jgrapht.Graphs.predecessorListOf

but all this api will return only immediate parent or child.
i am asking about getting all the parent's parents node of vertex

**Comment by AlexandruValeanu** [comment]
I believe that there is no such API provided but you can 'simulate' it:

- For successors, simply use a `BreadthFirstIterator` to iterate through them
- For predecessor, we could do the same thing (but on the transposed graph) or do something similar to [this](https://github.com/jgrapht/jgrapht/blob/e322c86fb9d67c9e6e6e9155d0f9cf64f1b78914/jgrapht-core/src/main/java/org/jgrapht/alg/NaiveLcaFinder.java#L157).

**Comment by rahul6789sharma** [comment]
That's great 
for predecessor i am using like

> 	protected static List<Vertex> getAllParents(DefaultDirectedWeightedGraph<Vertex, IACEdge> graph, Vertex vertex) {
		List<Vertex> parents = new ArrayList<>();
			EdgeReversedGraph<Vertex, IACEdge> reversedGraph = new EdgeReversedGraph<>(graph);
			BreadthFirstIterator<Vertex, IACEdge> breadthFirstIterator = new BreadthFirstIterator<>(reversedGraph, vertex);
			while (breadthFirstIterator.hasNext()) {
				parents.add(breadthFirstIterator.next());
			}
		return parents;
	}

    

BreadthFirstIterator  on reversed graph
