### ISSUE TITLE
JohnsonSimpleCycles throws IllegalArgumentException no such edge in graph

### ISSUE THREAD

**Issue by fredshevek** [jgrapht/jgrapht#474]
Hi,
I'm experimenting with `jgrapht` particularly with simple cycle finders.
In my particular setup, switching all `XSimpleCycles` algorithms works except Jonhson's, throwing:

```
[org.jgrapht.graph.BaseIntrusiveEdgesSpecifics getEdgeTarget "BaseIntrusiveEdgesSpecifics.java" 111]
[org.jgrapht.graph.AbstractBaseGraph getEdgeTarget "AbstractBaseGraph.java" 289]
[org.jgrapht.alg.cycle.JohnsonSimpleCycles findSimpleCycles "JohnsonSimpleCycles.java" 119]
```
I'm using a `DefaultDirectedWeightedGraph` with `DefaultWeightedEdge`. For the particular edge it reports, `g.getEdgeTarget` works if called manually. As vertices I'm using [this class](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/PersistentVector.java), where [`equals`](https://github.com/clojure/clojure/blob/ebfdbca535b81808b3ddc369d4a4e98b8f1524c7/src/jvm/clojure/lang/APersistentVector.java#L129) and [`hashCode`](https://github.com/clojure/clojure/blob/ebfdbca535b81808b3ddc369d4a4e98b8f1524c7/src/jvm/clojure/lang/APersistentVector.java#L141) are defined.

My wild guess, as I'm calling` jgrapht` from Clojure land, there might be something funny going on with generics but that seems highly unlikely since they are not a runtime concept.

**Comment by d-michail** [comment]
Hi, 

could you provide a few more details. What version of the library are you using? Does the problem manifest if you use directly the master branch? Would it be possible to isolate a simple example where the problem occurs? Could it be written directly in Java, instead of Clojure? Could you replace your vertex with an Integer?

I took a quick look at our implementation and there might be a small bug. Could you replace your use of "DefaultWeightedEdge" with a "DefaultEdge" instead (without changing the graph type) and report back if it works?

**Comment by fredshevek** [comment]
Hi,

I did try your branch and yes, it fixed the issue.
Thank you very much for taking care of this so quickly.

Cheers

**Comment by fredshevek** [comment]
Hi,

Sorry I was quick to respond. Yes the fix doesn't throw the exception but something else is going wrong.
Remember I'm using a directed weighted graph. JohnsonSimpleCycles finds me circles which is not on the graph.

There is an edge A -> B on the graph, and not the other way around. JohnsonSimpleCycles finds a circle which contains B -> A

**Comment by d-michail** [comment]
There might be yet another bug involved. I would suggest to create a simple example with a small graph where this behavior is happening and post it here, so that we can debug it.

**Comment by d-michail** [comment]
Took a quick look (I haven't written that algorithm myself) and noticed that it is returning the whole cycle backwards. 

I did some further changes in my branch, could you check that now cycles are returned in proper edge direction?

I have only changed `JohnsonSimpleCycles`. If you experiment with some other simple cycles algorithm, something similar might also happen. We plan to cleanup these algorithms and unify a little bit their behavior in the near future.

**Comment by fredshevek** [comment]
Thanks a lot, that seems to fix it.

Sorry for letting you do all the troubleshooting. I've tried to build a simple example in Java but interoping with Clojure data structures from Java proved to be quite cumbersome.
