### ISSUE TITLE
Dinic Maximum Flow algorithm

### ISSUE THREAD

**Issue by LightnessOfBeing** [jgrapht/jgrapht#486]
Hi!

I've been browsing on flow package and saw that there is no implementation for Dinic Maximum Flow algorithm. I want to implement Dinic algorithm, since it outperforms Edmonds-Karp and Push–relabel algorithm on the most of inputs. 

Do you think it would be useful?

**Comment by jsichi** [comment]
That sounds great, we'll look forward to reviewing your pull request.

**Comment by jkinable** [comment]
I'd be interested to see how DInic's algorithm compares against the other algorithms that are already present. This reference may be of interest as it compares various flow algorithms: 
Friis, Olesen,.An experimental comparison of max flow algorithms, http://www.cs.au.dk/~gerth/advising/thesis/jakob_mark_friis_steffen_beier_olesen.pdf

**Comment by jkinable** [comment]
PR has been merged. Closing this issue.
