### ISSUE TITLE
Breadth First Search on Tree ,Linearisation of tree and Binary Lifting 

### ISSUE THREAD

**Issue by dragonzurfer** [jgrapht/jgrapht#493]
Would it help to implement a Breadth First Search on Tree to support Binary Lifting and Linearisation of Tree.
Since Binary Lifting can be used to find ancestors in **O(log N)** time and the dynamic programming states calculated will be useful for node to root queries example problem [LINK](https://www.codechef.com/problems/POSTTREE) .

Tree Linearisation or Euler Tour on a Tree is useful for checking if a node A is ancestor to some node B in tree in O(1) . It is also useful for supporting path queries(Max valued node from u-v or xor of values from u-v) in **O(Q*root(N))** where Q is the number of queries and N the number of nodes. This can be achieved by implementing MO's algorithm (my blog link for [MO's algorithm](https://medium.com/@harryjobz/range-based-query-ec052edbf326)) on the linearized Tree array.

Looking forward to writing some code :)

**Comment by arnav-mandal1234** [comment]
I am a beginner. I would love to take up this task.I want some to more about how should I approach this issue and understand the codebase as well.

**Comment by dragonzurfer** [comment]
I am already working on this. Race against time :p Or make an issue of your own
