### ISSUE TITLE
DOTImporter doesn't read node attributes properly

### ISSUE THREAD

**Issue by SimoV8** [jgrapht/jgrapht#508]
I'm trying to parse a simple graph stored in dot format. 
The graph has some attributes linked to the nodes and some to the edges, but the former are not parsed correctly. 
The example graph I'm using is this one:
    
    digraph G {
    rankdir=LR
    node [shape="circle"]
    I [label="", style=invis, width=0]
    I -> 0
    0 [label="0", peripheries=2]
    0 -> 0 [label="!a | b"]
    0 -> 1 [label="a & !b"]
    1 [label="1"]
    1 -> 0 [label="b"]
    1 -> 1 [label="!b"]
    }

In this example the attributes linked to `node` and `I` are correctly parsed, but not the one linked to nodes `0` and `1`. When I say that the attributes are not correctly parsed I mean they are ignored, but no exception is thrown. 
On the other hand, I noticed that if I move on the top (before edges) the declaration of all the nodes, the attributes are parsed correctly.

I'm using version `1.1.1-SNAPSHOT` from the snapshot maven repository.

**Comment by d-michail** [comment]
Hi, 

the parser has the notion of a [ComponentUpdater](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-io/src/main/java/org/jgrapht/io/ComponentUpdater.java) for out-of-order attributes. You need to give one more callback function called `vertexUpdater` to the constructor of the `DotImporter`. 
 
https://github.com/jgrapht/jgrapht/blob/233d01210a76e04592cf34c17c3748dfc9b55354/jgrapht-io/src/main/java/org/jgrapht/io/DOTImporter.java#L78

**Comment by SimoV8** [comment]
Thank you, it worked! 

If I may suggest, do you think it makes sense to include a default implementation of vertex, edge, vertexProvider, edgeProvider, etc. for Dot graphs in the library? It is a widespread standard and I think the API is a little bit verbose and cumbersome for someone who just need to parse the graph and do some standard graph traversal. If you think it is a good idea I can create a pull request with this feature.
