### ISSUE TITLE
[FeatureRequest]Add a method getAllMutualPath  in ShortestPathAlgorithm

### ISSUE THREAD

**Issue by jiming** [jgrapht/jgrapht#510]
Hi,

When I wanted to resolve TSP, I wanted to cache distances of any two vertex. When the vertex is big, calculate the path take a long time. I guess the following two methods might be very helpful. Could you please consider to add them?

```
Set<GraphPath<V, E>> getAllMutualPath();

SingleSourcePaths<V, E> getPaths(V source, Set<v> excludeTarge);
```

Thanks and have a nice day!
Jiming

**Comment by NorahS** [comment]
Hello, what do you mean by "the vertex is big"?

and can you elaborate more on both methods?

**Comment by jiming** [comment]
Hi @NorahS,

I mean the count of vertex is big.

For example, I have a graph with 600 verteies, when I calculate mutaul distance between all vertex pair by using DijkstraShortestPath. Which will calculate 600 * 599 / 2 times. It takes a couple of minutes.

If you could consider supply a method to calculate all mutual vertex distance and path inside core lib, which could be much more faster since some path can be reused. ex.  if A to Z result is A -> S -> U -> Z, I do not need calculate A to S and A to U and S to U any more. 

Thanks!
Jiming

**Comment by jkinable** [comment]
It would be a bad idea to use Dijkstra to compute an all pair shortest path. Use FloydWarshall or related algorithm instead. Much more efficient. Have a look at the allpair shortest path algorithms already present in the library.

**Comment by jiming** [comment]
Cool, thank you @jkinable
