### ISSUE TITLE
Bug in AbstractBaseGraph

### ISSUE THREAD

**Issue by Yimismi** [jgrapht/jgrapht#512]
Hi, while I used some named graphs, I found that when degreeOf(V vertex) method called, the method will add the vertex into the graph if the vertex has not been added into the graph.  This is because that AbstractBaseGraph does not check if the vertex already exists before calling the method of underlying data structure.
```
    public void test()
    {
        Graph<Integer, DefaultEdge> g = new DefaultDirectedGraph<Integer, DefaultEdge>(DefaultEdge.class);
        g.degreeOf(1);
        System.out.println(g.containsVertex(1));
    }
```
This code should have thrown an exception or printed false (because the exception is not mentioned in Graph) , but it printed true.

**Comment by jsichi** [comment]
Good catch.  Wow, looks like this has been broken since like forever.  Do you want to open a pull request?

For all methods that call assertVertexExist, the interface Javadoc ought to be updated too with "@throws IllegalArgumentException if vertex is not found in the graph"

**Comment by Yimismi** [comment]
I'd like to do this. But the pull request I opened before is my master branch. I can't do it right now.

**Comment by d-michail** [comment]
Indeed, nice catch. 

Just add an `assertVertexExist(vertex);` in the method call. 

You can do that by (a) cloning the master branch, (b) create a new branch with whatever name you like, (c) change the method, (d) commit, (e) push the new branch on your fork, (f) create a pull-request from your branch to the master branch of the jgrapht project.

**Comment by Yimismi** [comment]
@d-michail Thinks for your guidance very much. I have pulled request.
