### ISSUE TITLE
GraphML import

### ISSUE THREAD

**Issue by ghost** [jgrapht/jgrapht#52]
Hi,

I have seen that this library delivers an GraphML-Export functionality, but I wasn't able to find an import.

Short: Is it possible to read a graphML-File (as a string) and get an Graph-Object(-hierarchy)?

Thanks a lot.

**Comment by d-michail** [comment]
Supported in release [1.0.0](https://github.com/jgrapht/jgrapht/releases/tag/jgrapht-1.0.0).
