### ISSUE TITLE
License files should be explicit in all uber jars produced by mvn package

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#534]
Currently, it's a hodgepodge; some dependency jars contain a pom.xml with a link to the license; others have a copy of their license; others reference it from the manifest.  And after being combined into an uber jar, there may be conflicts, with only one included.

We should clean this up for the next release and make sure that all uber jars we produce contain one license file per dependency, clearly marked by filename, e.g. JGraphX-license.txt, with a complete copy of the notice or full license as required.

https://stackoverflow.com/questions/22968266/maven-shade-plugin-and-licenses

For our full distribution tarball, we should also do something similar as an index for the lib directory.

**Comment by d-michail** [comment]
This has been addressed in #532.
