### ISSUE TITLE
runtime limit on unit tests

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#536]
Most of our unit tests run through in under a second or two each.  However, recently I've noticed some newer tests which take quite a bit longer on my laptop (up to 15 seconds) due to testing on large randomized input graphs:

HeldKarpTSPTest
PalmerHamiltonianCycleTest
MaximumWeightBipartiteMatchingTest (this one has been slow for a while)

I'm wondering whether we should put together some guidelines on this (distinguishing between unit tests and scale-up testing), and move the slower tests to an optional section (like we did for perf tests already).  It's not really a problem right now, but if the trend continues, eventually we'll end up with the full unit test suite taking a long time, which isn't great for activities such as quickly verifying a fix, bisecting to find where a problem was introduced, etc.

If we do this, we would want to make sure that Travis still runs the full suite for checkin acceptance.

@d-michail @jkinable @AlexandruValeanu any opinions on this?

**Comment by tibrewalpratik17** [comment]
@jsichi I would also like to present my views. Truly speaking even I have observed this and found it a bit annoying when I wanted to verify minor changes in my code. Well I even experienced this while adding the automorphism check for the named graphs and hence omitted it for some graphs for which the value was quite high. I really like your suggestion. With this we can include heavier unit-tests too and not affect the time of compiling it locally.

**Comment by jkinable** [comment]
Travis does not seem to impose a strict time limit: https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts

The algorithms that have been added more recently to jgrapht are getting more complicated. In some cases, bugs may only appear in larger graphs (e.g. some rounding error in some algorithm that uses dual values). So I think it's certainly valuable to include larger tests in the regular test suite.

Personally I don't find the longer tests a big problem. As long as they are relevant for bug identification (not scale testing), and not exorbitantly long, I would prefer to keep them in the main tests. For quick development purposes, it it always possible to (1) run an individual test or (2) run all tests in a specific package. Nevertheless, it would be good to include a few notes about this in our Dev Guidelines.

**Comment by AlexandruValeanu** [comment]
I have nothing against long tests (as I am the author of two of the classes used as examples). I think it's better to run against a lot of random instances. You never know what finally fails. 

I don't think that we have to separate plain unit tests from benchmarking tests. This way we don't introduce new packages, new documentation and all tests related to an implementation can be found in just one place. I like the idea of adding a few notes in the Dev Guidelines

**Comment by d-michail** [comment]
I am also fine with keeping the long running tests. 

 - From inside an IDE I usually invoke only a subset of the tests. 
 - When testing packaging, etc. I usually call maven with -DskipTests

The surefire plugin can also be [configured](http://maven.apache.org/plugins-archives/maven-surefire-plugin-2.12.4/examples/single-test.html) to execute only a few tests from the command line.

Anyway, in a Travis build we want every test running.

**Comment by d-michail** [comment]
So the idea would be to call `mvn test` for short and `mvn verify` for longer tests?

**Comment by jsichi** [comment]
Right, and we would use mvn verify for Travis.

**Comment by d-michail** [comment]
One additional task that could be accompanied with this, is to refactor the way we call the performance tests (and maybe even their location). They are somehow buried deep inside the packages now. 

Perhaps, adding a maven profile where the performance tests are executed, or something along these lines.

**Comment by jsichi** [comment]
That would be great.  Figuring out a place to have them run asynchronously after each commit to master and then publishing the results over time would also be a great way to be able to detect/investigate performance regressions.  A bare metal server would be best for this for consistent timing reports.

**Comment by jsichi** [comment]
I merged #566 from @d-michail and submitted my own PR #567 for the remainder of the work (providing suite options from IDE's, as well as being able to run the perf tests from mvn).

**Comment by jsichi** [comment]
I've updated the Eclipse setup instructions on the development environment wiki page, and also added a section on running tests from the command line.  Closing this one out now.
