### ISSUE TITLE
How get a vertex with his degree

### ISSUE THREAD

**Issue by destroyxx** [jgrapht/jgrapht#537]
Hello,
How can I get a vertex with his degree. For exemple : 
`g.addVertex(1);
g.addVertex(2);
g.addVertex(3);
g.addEdge(1, 2);
g.addEdge(1, 3);`

The vertex are 1,2,3 and the degree are 1 = 2, 2 = 1 and 3 = 1 (a degree is a link with a vertex)
I must be able to put these vertices and their degrees in a list for the sorting.

**Comment by jkinable** [comment]
See the degreeOf method in the Graph interface: http://jgrapht.org/javadoc/org/jgrapht/Graph.html#degreeOf-V-
