### ISSUE TITLE
Digital library

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#539]
Several classes contain links to external documents, e.g. someone's dissertation, or some graph format (e.g. DIMACS format). Unfortunately, it does happen that those links get broken. This obviously is very annoying. Would it make sense to maintain our own little repository with material and reference directly to this repository? For instance, PR #533 contains a rather essential link to a thesis. Would it make sense to maintain a copy of this thesis in our repository? Obviously, the repository can only hold publicly available material, so no articles behind a paywall (e.g. sciencedirect).

**Comment by d-michail** [comment]
Not sure how to solve this problem, while respecting copyrights. Most of the time you are not even allowed to host your own published paper at your website (at least the official copy).

I think the safest approach is to include a proper citation to the resource, and the interested party can use  Google Scholar to find it.
