### ISSUE TITLE
GMLImporter fails to handle lists inside attributes

### ISSUE THREAD

**Issue by pmarches** [jgrapht/jgrapht#543]
According to the [GML specification](http://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf), the GMLImporter does not handle list of items correctly. If an attribute is present more than once, it should transform the attribute into a list. The current behavior is to keep only the last value encountered.

```
someAttribute: [
 listOfStrings "a"
 listOfStrings "b"
]
```

In this example, the correct behavior would be to create a list attribute. Instead, jgrapht keeps only "b" as a string attribute.

**Comment by d-michail** [comment]
Yes, there is no support for lists. Currently lists are flattened which means that only the last entry is kept.

A full working parser of GML is out-of-scope here, as GML can represent arbitrary nested structures. Having said that, I am adding this as a feature request, to support lists inside an edge or inside a vertex.

Possible workarounds are to use a string attribute and parse the list in user code.

**Comment by jsichi** [comment]
@pmarches could you confirm that the pull request from @d-michail is sufficient for you?  Then I'll merge it.

**Comment by pmarches** [comment]
Yes, it covers my use case. Thank you!
