### ISSUE TITLE
Random StackOverflowError when building a DAG

### ISSUE THREAD

**Issue by gilles-gosuin** [jgrapht/jgrapht#556]
I'm using JGraphT to create a DAG with about 20,000 vertices and 20,000 edges and I'm facing random StackOverflowErrors in method "DirectedAcyclicGraph.dfsF" when adding a new edge.

It sounds understandable, since this method uses recursion to perform its job and my graph is quite simple but very "deep".

What I'm not sure I understand is that the error is random, which means that I cannot find a hard limit on the graph size (relative to the stack size of course) that I could use to execute the whole process as batches.

Do you have any plans on removing recursion from this method (and from "dfsB" as well, for that matter)?

**Comment by jkinable** [comment]
Not an answer to your question, but perhaps a work-around: Use the `DefaultDirectedGraph` class (or the `DefaultDirectedWeightedGraph` class, in combination with the `DepthFirstIterator`. This might give you significantly better performance as this DFS is non-recursive. The `DirectedAcyclicGraph` is mainly there to ensure that all operations performed on the graph, still result in a DAG (throws an error if you do something that produces a graph which is not a DAG)

**Comment by gilles-gosuin** [comment]
Thanks ! A good suggestion indeed !

I've forked the repo and tried implementing the recursion removal - I might have a PR to submit very soon, if you're interested.

**Comment by jkinable** [comment]
Sounds good. Looking forward to your PR.

The DAG class is mainly there to ensure that whatever operation you
perform, the graph remains a DAG. This obviously comes with a computational
penalty. The DefaultDirectedGraph is the opposite: it does not offer any
guarantees at all. You could use the `CycleDetector.detectCycles()` to
verify whether your graph is still acyclic after a number of modifications.
Also note that the DFSIterator works directly on top of the DAG, so for a
PR it might be sufficient to simply return a DFSIterator.

**Comment by d-michail** [comment]
The two dfs traversals in the DAG implementation are a little bit specialized. Try to use a stack for the state of the iteration but keep the notion of affected regions as is.
