### ISSUE TITLE
VF2 subgraph detection

### ISSUE THREAD

**Issue by d-cap** [jgrapht/jgrapht#558]
Hello,
I'm using jgrapht to study how the VF2 algorithm works. Maybe I found an inconsistency, the following code return false:

```java
Graph<Integer, DefaultEdge> g1 =
    new DefaultListenableGraph<>(new SimpleGraph<>(DefaultEdge.class));
g1.addVertex(1);
g1.addVertex(2);
g1.addVertex(3);
g1.addEdge(1, 2);
g1.addEdge(2, 3);
g1.addEdge(3, 1);

Graph<Integer, DefaultEdge> g2 =
    new DefaultListenableGraph<>(new SimpleGraph<>(DefaultEdge.class));
g2.addVertex(1);
g2.addVertex(2);
g2.addVertex(3);
g2.addEdge(1, 2);
g2.addEdge(2, 3);

return new VF2SubgraphIsomorphismInspector<>(g1, g2)
    .isomorphismExists();
```
but should return true, am I wrong?

**Comment by jsichi** [comment]
Actually, I take it back.  The VF2SubgraphIsomorphismInspector only finds mappings between g2 and induced subgraphs of g1 (not arbitrary subgraphs of g1).

I think the correct resolution for this issue is to make that clear in the documentation.

**Comment by jsichi** [comment]
Proposed doc update in #564

**Comment by d-michail** [comment]
Thanks for reporting. We updated the documentation to make the distinction clear.
