### ISSUE TITLE
FloydWarshall performance optimizations

### ISSUE THREAD

**Issue by shevek** [jgrapht/jgrapht#563]
1. Exit the final loop early if no edges are added for a given `k` - this is *HUGE*
1. Sort the nodes by degree, low to high, before numbering them and starting the algorithm. This is probabilistic, but seems to be a big deal. I can construct a probabilistic proof that this is optimal.
1. Compute the `first_i` as the index of `i` such that graph.degreeOf(indexToVertex.get(i)) >= 1 and start iteration of `i` at that index, not at `0`. (Only matters for very sparse, large graphs.)
1. Skip the inner loop if (i == k), correspondingly if (i == j) or (j == k) before doing the object lookups.

I confess I didn't bother running any test cases which took longer than a minute, but this did make N=8000 tractable in a couple of seconds, which it wasn't previously.

I think I'm going to leave this alone now and take your advice to try Johnson's.

**Comment by shevek** [comment]
ref #561 and #562

**Comment by d-michail** [comment]
Most of these are done in #632.
