### ISSUE TITLE
IllegalArgumentException via Graphs#addEdgeWithVertices

### ISSUE THREAD

**Issue by Toptachamann** [jgrapht/jgrapht#571]
Hi, 
I have the following code:
``` java
Graph<Integer, DefaultEdge> graph = new DefaultUndirectedWeightedGraph<>(DefaultEdge.class);
Graphs.addEdgeWithVertices(graph, 1, 2, 3);
```
and I get
``` java
Exception in thread "main" java.lang.IllegalArgumentException: no such edge in graph: (null : null)
	at org.jgrapht.graph.WeightedIntrusiveEdgesSpecifics.setEdgeWeight(WeightedIntrusiveEdgesSpecifics.java:81)
	at org.jgrapht.graph.AbstractBaseGraph.setEdgeWeight(AbstractBaseGraph.java:469)
	at org.jgrapht.Graphs.addEdge(Graphs.java:56)
	at org.jgrapht.Graphs.addEdgeWithVertices(Graphs.java:127)
	at org.jgrapht.alg.blossom.Test.main(Test.java:15)
```

I've tried to used custom edge type and create graph with a custom edge factory, but this dosn't help.

From the Graphs class:

``` java
public static <V, E> E addEdge(Graph<V, E> g, V sourceVertex, V targetVertex, double weight)
    {
        EdgeFactory<V, E> ef = g.getEdgeFactory();
        E e = ef.createEdge(sourceVertex, targetVertex);

        // we first create the edge and set the weight to make sure that
        // listeners will see the correct weight upon addEdge.
        g.setEdgeWeight(e, weight);

        return g.addEdge(sourceVertex, targetVertex, e) ? e : null;
    }
```
The exception is thrown after a call to `g.setEdgeWeight(e, weight);`. I debugged the code and it turned out, that `WeightedIntrusiveEdgesSpecifics` doesn't contain this edge (logical). 
___
On the other hand, this code works fine. 
``` java
Graph<Integer, DefaultEdge> graph = new DefaultUndirectedWeightedGraph<>(DefaultEdge.class);
DefaultEdge edge = Graphs.addEdgeWithVertices(graph, 1, 2);
graph.setEdgeWeight(edge, 5);
```
___
Is it an expected behaviour or is it a bug?

**Comment by d-michail** [comment]
Nice catch. If your edge type is `DefaultWeightedEdge`, then it works fine. Some versions back, you could only instantiate a weighted graph with a `DefaultWeightEdge`.

I guess the bug is in the `Graphs.addEdge()` method. @jsichi @jkinable Since now we can instantiate weighted graphs with any edge type, we should swap the order of the operations. If we want to fully support listeners, maybe we can also introduce an event about edge weight change.

**Comment by jkinable** [comment]
@d-michail I would have to have a look at the code.
slightly unrelated: we could consider removing the DefaultWeightedEdge and only have the DefaultEdge which could extend IntrusiveWeightedEdge.

**Comment by jsichi** [comment]
I agree with @d-michail.  It's unacceptable that we're calling setEdgeWeight on an edge which isn't yet part of the graph (even for DefaultWeightedEdge, it's arguable that this should trigger an assertion failure, likewise for getEdgeSource and getEdgeTarget on intrusive edges).  

GraphEdgeChangeEvent.EDGE_WEIGHT_UPDATED would be a good addition in general.

I can't think of any clean way to preserve the existing atomic listener invocation (it would be nice to do so, although I don't know whether any apps actually rely on it).
