### ISSUE TITLE
Travis timeouts

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#579]
One of the tests in `BergeGraphInspectorTest` is taking too long to complete; this occasionally causes travis to time out. Need to find out which test this is, and tune it down a notch. 
@PhilippKaesgen ?

**Comment by PhilippKaesgen** [comment]
Removing the <code>checkPappusGraph</code> method should do the trick. If this issue persists, I would recommend removing all the tests flagged as SlowTest step by step.

**Comment by d-michail** [comment]
Maybe we can introduce another test category which will not be triggered automatically, but only if the user requests it explicitly through a test suite?

**Comment by d-michail** [comment]
We already have several randomized tests in the library, either with a fixed seed, or even with a time based generated seed. This does not pose a problem as long as we also have a "verifier" for the result. 

For really long running tests that force Travis to timeout, we can (a) delete them or (b) introduce a category such as `OptionalTest` or something similar. @jsichi Any opinion on this?

**Comment by jsichi** [comment]
I think an OptionalTests category would be good.  All that's required is excluding it in jgrapht-core/pom.xml (under both surefire and failsafe), and also in IntegrationTestSuite and FastTestSuite.

Let's do this after the dust settles on #580

**Comment by jsichi** [comment]
#580 has been merged.  @PhilippKaesgen could you submit a followup pull request which adds the OptionalTests category and applies it to the tests that Joris commented out?

**Comment by jsichi** [comment]
I've merged #581 and updated the wiki at

https://github.com/jgrapht/jgrapht/wiki/Unit-testing

So now we can close this one out.
