### ISSUE TITLE
Graph.equals() does not work in some cases

### ISSUE THREAD

**Issue by bcrocus** [jgrapht/jgrapht#589]
When comparing two identical graphs (which have edges) using the DefaultEdge with .equals (i.e. graph1.equals(graph2)), the comparison fails because IntrusiveEdge (from which DefaultEdge is derived) is missing equals and hashcode methods. Adding the equals and hashcode methods to IntrusiveEdge will make the comparison work properly (i.e. identical graphs are equal to each other).

**Comment by jsichi** [comment]
This is expected behavior.

https://github.com/jgrapht/jgrapht/wiki/EqualsAndHashCode

You're free to use your own custom edge class which overrides equals/hashCode.
