### ISSUE TITLE
BUG: Suspected integer overflow in RandomGraphGenerator

### ISSUE THREAD

**Issue by ckapop** [jgrapht/jgrapht#60]
When generating a random SimpleDirectedGraph with "aNumOfVertexes" =  50000 and "aNumOfEdges" = 150000 we get the exception below. It appears there might be some integer overflow issues. We tried changing to double in the code and it seemed to work fine. Is this a known issue and is there an official patch for this?

Exception in thread "main" java.lang.IllegalArgumentException: numOfEdges is not valid for the graph type 
-> Invalid number Of Edges=150000 for: graph type=class org.jgrapht.graph.SimpleDirectedGraph ,number Of Vertexes=50000
-> Advice: For the Max value , check the javadoc for org.jgrapht.generate.RandomGraphGenerator.DefaultEdgeTopologyFactory

**Comment by jkinable** [comment]
Fixed. Thanks for reporting this.
