### ISSUE TITLE
MathWorld reference for SimpleGraph does not match our definition

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#601]
We provide http://mathworld.wolfram.com/SimpleGraph.html as a reference for our org.jgrapht.graph.SimpleGraph class, but that page says "A simple graph, also called a strict graph (Tutte 1998, p. 2), is an unweighted, undirected graph containing no graph loops or multiple edges...", whereas we do not require SimpleGraph instances to be unweighted.

The wikipedia definition matches ours:

https://en.wikipedia.org/wiki/Graph_(discrete_mathematics)#Simple_graph

(but wikipedia references aren't terribly stable).

**Comment by jkinable** [comment]
I would clarify this in the class description. We can keep the wolfram reference, with the additional note that we do allow edge weights. Personally I would prefer to marginally extend the class description (i.e. add a few lines explicitly defining a simple graph). I can submit a PR for that. It unfortunately happens a lot that graph definitions differ in different books/articles.

**Comment by jsichi** [comment]
Sounds good.
