### ISSUE TITLE
DefaultAttribute null pointer exception

### ISSUE THREAD

**Issue by oliluc** [jgrapht/jgrapht#611]
Class: jgrapht/jgrapht-io/src/main/java/org/jgrapht/io/DefaultAttribute.java

getValue() is same of  toString().
I think that could be a copy/paste issue.

/**
     * Get the string value of the attribute
     * 
     * @return the string value of the attribute
     */
    @Override
    public String getValue()
    {
        return value.toString();
    }

    @Override
    public String toString()
    {
        return value.toString();
    }

I think that a getValue needs to return a T value or if you want that returns a string then you need to check the nullness of value because can be null. Indeed constructors have parameter as Integer, Boolean etc. that allow null value.

In the other methods of DefaultAttribute class  value is every time checked (hashcode, equals), then I think than should be fixed.

**Comment by d-michail** [comment]
The `getValue()` method returns a String on purpose. As for the null values, if you create an attribute with a null value you will get a `NullPointerException`.

We could add a check for null in the constructor, but you will still get a `NullPointerException`.

**Comment by oliluc** [comment]
Could be a fix 

public String getValue()
{
return String.valueOf(value); //it is usually used for cases of this kind, in order to preserve the String type
}

or

public String getValue()
{
return value == null ? null : value.toString(); 
}

because it seems drastic to trigger an exception if the null value is allowed in the constructor

**Comment by d-michail** [comment]
Yep, `String.valueOf()` is another solution.

**Comment by oliluc** [comment]
Bye, thanks for your time and for your work

**Comment by jsichi** [comment]
Fix for this is coming in #612
