### ISSUE TITLE
shortestpath algorthim AllDirectedPaths 

### ISSUE THREAD

**Issue by Nordicus** [jgrapht/jgrapht#617]
When finding all paths using this algorithm, all returned GraphPath have a weight equal to the number of edges in the GraphWalk. This ignored the actual weights of the edges, and makes this unsuitable for use on directed weighted graphs. Having looked at the source code, there doesn't seem to be a good reason to set the weight of the graph walk to this instead of the actual weight of the graph walk in terms of Graph.getEdgeWeight(Edge).

**Comment by jsichi** [comment]
@agdphd any comment on this?

**Comment by agdphd** [comment]
Thanks for flagging this! Sure, this sounds like an easy fix; just need to update the weight calculation at [1] to sum the edge weights. I should be able to get a PR out later in the week.

[1] https://github.com/jgrapht/jgrapht/blob/11132e62d9f2c601d0837ef2e3295d5408497a28/jgrapht-core/src/main/java/org/jgrapht/alg/shortestpath/AllDirectedPaths.java#L300

**Comment by jsichi** [comment]
@Nordicus I've merged the fix from Andrew...let me know if that satisfies your requirement.

**Comment by Nordicus** [comment]
This has fixed the issue perfectly, thank you.
