### ISSUE TITLE
Generate Release Files?

### ISSUE THREAD

**Issue by simlu** [jgrapht/jgrapht#621]
What is the recommended way to generate the files listed under [release contents](https://github.com/jgrapht/jgrapht#release-contents)?

Is this documented somewhere? I'm mainly interested in an easy way to generate the jar files.

**Comment by jsichi** [comment]
`mvn package`

I've added a note for that in the Release Contents section.

After running that, you'll find the .zip and .tar.gz archives in jgrapht-dist/target.

**Comment by simlu** [comment]
That worked perfectly. Thank you for the quick reply!

Closing this.
