### ISSUE TITLE
coding convention followups for color refinement

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#624]
These are some leftover issues from #615, which has already been merged.  For the naming convention, please make sure these get applied to other pending pull requests as well.

* Non-obvious data member names such as "k" should have a comment explaining their purpose (regardless of whether they are defined in the paper).  Better would be to use a meaningful name and then make clear the correspondence to variables defined in the paper via a comment at the point of definition.
* Variable names should start with a lowercase letter, and except for local variables such as loop iterators, should have meaningful names.
* Arrays should be 0-based, not 1-based, unless you are programming in FORTRAN :)
* Add the `@throws` Javadoc mentioned by @d-michail to the IsomorphismInspector interface for documentation purposes (making clear that not all inspector implementations are subject to this limitation, so the caller should refer to the Javadoc for the actual implementation used)

**Comment by christophgruene** [comment]
@jsichi Unfortunately, I cannot assign it to me as well, nevertheless, I have it in mind. We will correct this with the individualization refienement PR.

**Comment by jsichi** [comment]
Last remaining item here is to add the `@throws` Javadoc to the IsomorphismInspector interface.  @christophgruene can you take care of that when you rebase?

**Comment by christophgruene** [comment]
I added a PR (#691) for the `@throws`. What about the bug in the CR isomorphism inspector (PR #676)?

**Comment by jsichi** [comment]
Yep, we'll take a look at that next.
