### ISSUE TITLE
add a helper class for managing integer-to-vertex mapping

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#641]
A common pattern we're seeing crop up across many algorithms is an initial step of building a mapping from n vertices to the integer range [0,n), e.g. so that the integers can be used as array indexes.

Instead of repeating this little scrap of code over and over, we should wrap it up into an alg.util class and reuse it.  Later, for jgrapht-opt graphs which are already based on such a mapping, we can arrange for the helper to skip the mapping construction and have it use the one from the underlying graph instead.

**Comment by AlexandruValeanu** [comment]
Wouldn't it be a vertex-to-integer mapping? I can submit a PR for this but I am not sure where should this class be placed.

**Comment by jsichi** [comment]
I was thinking bidirectional, as you have it in HeavyPathDecomposition (vertexMap + indexList).

Let's put it in org.jgrapht.util since it may find uses outside of alg too.

**Comment by AlexandruValeanu** [comment]
@jsichi, please see #642 and let me know if you have any suggestions.

**Comment by AlexandruValeanu** [comment]
@jsichi Please close this (and thank you for correcting the Javadoc).
