### ISSUE TITLE
Other Heaps?

### ISSUE THREAD

**Issue by simlu** [jgrapht/jgrapht#645]
In [Kolmogorov's Blossom V implementation](https://github.com/jgrapht/jgrapht/pull/595) @Toptachamann found that the [PairingHeap](https://github.com/d-michail/jheaps/blob/master/src/main/java/org/jheaps/tree/PairingHeap.java) and the [CostlessMeldPairingHeap](https://github.com/d-michail/jheaps/blob/master/src/main/java/org/jheaps/tree/CostlessMeldPairingHeap.java) which @d-michail implemented in [jheaps](https://github.com/d-michail/jheaps), perform [significantly better](https://github.com/jgrapht/jgrapht/pull/595#issuecomment-408136291) than the currently implemented [FibonacciHeap](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/util/FibonacciHeap.java) (for that specific use case). However they are likely to outperform the FibonacciHeap generally.

Would it be ok to port the implementation @d-michail wrote into this library? What's the general consense here?

**Comment by jsichi** [comment]
I'm fine with adding the dependency, especially given the authorship :)  I think that means we can eliminate our GenericFibonacciHeap, and eventually our FibonacciHeap after performance-testing as suggested by @simlu

**Comment by simlu** [comment]
Thank you for the quick replies! Makes perfect sense to me!

I would really like this to happen before https://github.com/jgrapht/jgrapht/pull/595 get's merged. What would be required here (I'm not that familiar with maven)? Do we just list is as a dependency?

**Comment by jsichi** [comment]
Someone would need to submit a PR to add the dependency in jgrapht-core's pom.xml and replace at least one existing use of GenericFibonacciHeap to exercise the dependency.  There are also some other doc and packaging files that need to be updated to document the new dependency.

**Comment by Toptachamann** [comment]
I've added this dependency to the jgrapht-core pom and used Pairing heaps. Should I modify the maximum weight bipartite matching algorithm?

**Comment by jsichi** [comment]
It would be best to do it in its own PR so we can merge that by itself, and then @Toptachamann can rebase against that.

**Comment by simlu** [comment]
@jsichi is that really necessary? The change seems very minor and is tested in the blossom pr already. Considering its the reason we're adding the dependency.

It really depends on how much work it is to replace fib with pair. If it's a lot of work then I'm against a new pr. Otherwise sure

**Comment by jsichi** [comment]
It's cleaner to keep addition of dependencies from getting entangled with giant PR's, in case one or the other needs to be reverted later for any reason.

**Comment by Toptachamann** [comment]
Don't see any problem with rebasing after PR for dependency addition is merged, especially because in min-cost flow algorithm I use a Fibonacci heap for Dijkstra algorithm and I'd like to replace it with Pairing heap.

**Comment by jsichi** [comment]
@d-michail you are probably the best person to add the dependency, so please go ahead with that

**Comment by jsichi** [comment]
@simlu we can close this one now right?  (#652 has been merged.)  Some followup work is needed for remaining uses of FibonacciHeap (I think we can delete GenericFbionacciHeap already since all uses of that are gone now).

**Comment by simlu** [comment]
@jsichi Do we create a separate ticket for that? If so this can be closed for sure! 

Thanks for the hard work everyone!

**Comment by jsichi** [comment]
Opening #666 for the followup.  :metal: :smiling_imp:
