### ISSUE TITLE
Do we really need multiple uber jars?

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#653]
I think the intention of the original uber jar was to keep it easy for people to use the non-Maven release archive, quickly running the demo or including JGraphT as a dependency in their non-Maven application.

Now we are starting to get a proliferation of uber jars, bloating the release archive, and it's about to get a lot worse with the inclusion of fastutil.

Would it make sense to change the build to produce a single uber jar which rolls together all dependencies, including optional ones?  And is that difficult to do with Maven?

**Comment by jkinable** [comment]
I think that's a good idea.

**Comment by d-michail** [comment]
A possible solution is to have one more "jar" type module called "bundle" (or some other similar name) for the uber jar. In this module, we replace the original jar (which is empty) with the shaded jar.

See this [branch](https://github.com/d-michail/jgrapht/tree/bundle) for a demo.

I excluded the "bundle" jar from the deploy phase. It is there only for the "dist" module to pick it up and include it in the distribution.

**Comment by d-michail** [comment]
Opened up #654.

**Comment by jsichi** [comment]
Resolved by #654
