### ISSUE TITLE
should we drop touchgraph support?

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#656]
It feels like one of those legacy things that we've been wasting cycles maintaining, with no evidence that anyone is actually using it.  And it's not even a proper maven dependency.

**Comment by jsichi** [comment]
And even though it's optional, it has caused needless licensing anxiety/confusion in the past:

https://lists.debian.org/debian-legal/2010/05/msg00004.html

**Comment by d-michail** [comment]
I would be in favor of dropping it completely. If someone indeed uses it, we can create a separate maven project with the adapter classes.

**Comment by jsichi** [comment]
Opened #659

**Comment by jsichi** [comment]
#659 has been merged, so the final answer was yes.
