### ISSUE TITLE
Feature suggestion: delta-stepping single source shortest path algorithm.

### ISSUE THREAD

**Issue by SChudakov** [jgrapht/jgrapht#663]
Hello,

The following algorithm was mentioned as an idea for future development: delta-stepping single source shortest path algorithm by Meyer and Sanders.The algorithm is described in [this paper](https://people.csail.mit.edu/jshun/papers/MS03.pdf) while some useful implementation guidelines can be found [here](https://arxiv.org/pdf/1604.02113v1.pdf). Is this still relevant?

**Comment by jkinable** [comment]
Yes that's still relevant. It hasn't been implemented.

**Comment by jkinable** [comment]
Implemented in #664
