### ISSUE TITLE
Feature suggestion: Christofides algorithm for 3/2-approximation of the metric TSP

### ISSUE THREAD

**Issue by Toptachamann** [jgrapht/jgrapht#669]
Currently, we have 2-approximation algorithm for metric TSP. This can be improved to 3/2-approximation via the Christofides algorithm. What do you think about this?

**Comment by AlexandruValeanu** [comment]
I started working on a PR for Christofides back in December but I soon realized that there was no implementation for `MinimumWeightPerfectMatching`so I decided to drop. I think that it would be a great addition to the library so feel free to work on it.
