### ISSUE TITLE
On account of setting up JGraphT in Windows 10

### ISSUE THREAD

**Issue by atulim** [jgrapht/jgrapht#683]
I am starting up with JGraphT. Can somebody please tell me how to set up my system for JGraphT and use which IDE to run the programs for contributing here.
I want to contribute in JGraphT , kindly help.

**Comment by AlexandruValeanu** [comment]
See https://github.com/jgrapht/jgrapht/wiki/How-to-setup-your-development-environment-for-JGraphT
