### ISSUE TITLE
Matchings in General graphs

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#685]
Recently we have added an implementation for Minimum Weight Perfect Matchings in general graphs (see `KolmogorovMinimumWeightPerfectMatching`). It would be great to have the following two important extensions:

1. Maximum Weight **Perfect** Matching
2. Maximum Weight Matching

Currently there is support for these variants in:
- http://lemon.cs.elte.hu/pub/doc/latest-svn/a00852.html
- http://www.algorithmic-solutions.info/leda_guide/graph_algorithms/matching_overview.html

@Toptachamann could you inventarize how we could implement these 2 variants? Most likely your current implementation can be adapted to accomplish this. For details, see Chapter 5: Optimal Matchings in Combinatorial Optimization
by William J. Cook, William H. Cunningham, William R. Pulleyblank and Alexander Schrijver Copyright © 1998 John Wiley & Sons, Inc.
Perhaps there are alternative ways to accomplish this. It would be useful to check this. 
This paper provides also a useful note on Max Weight matchings:
[Zvi Galil, Efficient algorithms for finding maximum matching in graphs, ACM Computing Surveys, 1986.
](http://www.cs.kent.edu/~dragan/GraphAn/p23-galil.pdf)

**Comment by Toptachamann** [comment]
That's a good idea. I'll find out how to implement these variations. Thanks for articles.

**Comment by jkinable** [comment]
@Toptachamann The 5th Chapter of Optimal Matchings in Combinatorial Optimization
by William J. Cook, William H. Cunningham, William R. Pulleyblank and Alexander Schrijver Copyright I'm referencing was part of the reading package I sent you earlier. In case you don't have that chapter anymore I can resend it to you.

**Comment by Toptachamann** [comment]
@jkinable I still have it, thanks!

**Comment by d-michail** [comment]
Guido's [master thesis](https://homepages.cwi.nl/~schaefer/ftp/pdf/masters-thesis.pdf) page 22 also contain the reductions between maximum weight matching and maximum weight perfect matchings.

**Comment by jkinable** [comment]
Nice reference, thanks!

So it seems that the most common approach to solve Max Weight Matching is by the following reduction:
Take a graph G, add a copy G' of G to G and connect a node u in G with its copy u' in G' with a zero-cost edge. This new graph guarantees that there exists a perfects matching in the resulting graph, so now we can use a Max Weight Perfect matching algorithm on the new graph to solve the Max Weight Matching Problem in the original graph.

@Toptachamann : The above reduction literally doubles the size of a problem instance. Are there other reductions that are less expensive? Are there ways around this?

Obviously I think that this reduction is very easy to implement and gives us immediate support for Max Weight Matching Problems and hence would be a nice addition.

**Comment by Toptachamann** [comment]
It seems like there is no cheaper reduction than this one. Chapter 5 of Optimal Matchings in Combinatorial Optimization by William J. Cook, William H. Cunningham, William R. Pulleyblank and Alexander Shrijver contains the same reduction on page 161. 

I think it is possible to design an algorithm for maximum weight perfect matching that is analogous to the Blossom V. This will require to write new primal and dual updaters with all memory and time optimizations since the LP formulation for maximum weight perfect matching is different => complementary slackness conditions are different. 

So, if we need max weight matching and max weight perfect matching support before the next release, I can add both.

**Comment by jkinable** [comment]
Sounds good. For the max weight perfect matching: can you check whether you
can simply use the min weight perfect matching where with the cost
coefficients multiplied by -1?

**Comment by Toptachamann** [comment]
If we consider the perfect matching costs, then we can see, that their relative order is inverted after we multiply edge costs by -1. Therefore, a max cost perfect matching is transformed into min cost perfect matching relative to this order. 

So, yeap, the reduction from max. cost perfect matching to the min. cost perfect matching is also not very hard.

**Comment by d-michail** [comment]
It would be great if we could add all these reductions plus the reductions for graphs with multiple (parallel) edges.
