### ISSUE TITLE
Hello JGraphT 

### ISSUE THREAD

**Issue by AlexandruValeanu** [jgrapht/jgrapht#686]
Shouldn't we also include the imports in the "Hello JGraphT" sample code from [here](https://github.com/jgrapht/jgrapht/blob/gh-pages/guide/UserOverview.md#hello-jgrapht)?

I think that having a fully functioning and complete "Hello World" solution would be better for first-time users.

**Comment by jsichi** [comment]
Yeah, originally I tried to include imports for all the examples, but it got a little messy so I removed them.  I'll go back and selectively add them in for examples like this one which are self-contained.

**Comment by jsichi** [comment]
I'm addressing this in #689.  The indentation comes out a little weird since the code extractor currently preserves it exactly as it was in the source file, but oh well.

**Comment by jsichi** [comment]
Site updated.
