### ISSUE TITLE
Update JUnit 4 to JUnit5

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#697]
JUnit 5 has been released. Currently jgrapht is using JUnit 4. Let's upgrade to JUnit5. Here's a nice blog on how to accomplish that: https://blog.scottlogic.com/2017/10/10/junit-5.html

**Comment by besza** [comment]
I've started to look into it.

**Comment by jbduncan** [comment]
For parallel execution, JUnit 5 has its own fine-grained mechanism for doing so now. :)

**Comment by jkinable** [comment]
@besza I never saw your question (I don't get an e-mail notification when you edit your post). Quite frankly I have no good suggestion on how to fix this. Can you use the suggestion by @jbduncan ?

**Comment by besza** [comment]
The JUnit Platform now has support for declarative test suites: https://github.com/junit-team/junit5/issues/744.
