### ISSUE TITLE
DOT graph and HTML-Like Labels

### ISSUE THREAD

**Issue by PHaroZ** [jgrapht/jgrapht#698]
Hi,

First of all thanks for this great framework !

I'm working with a graph which I want to export in DOT format but I've an issue with HTML-Like Labels of Edge.
According to [this doc](https://www.graphviz.org/doc/info/shapes.html#html) a node with an HTML-Like label should look like ```myNodeId [ label=<<u>my underlined label</u>> ];``` but when I use the ```org.jgrapht.io.DOTExporter``` I obtain ```myNodeId [ label="<<u>my underlined label</u>>" ];``` (label value is double-quoted).
This cause trouble with all visualization tools I tried (eg xdot, [viz.js](https://github.com/mdaines/viz.js/)).

Can I make a PR to fix that ?

**Comment by d-michail** [comment]
Of course, but note that this is a little bit tricky. I guess you would need to introduce an `HTML` attribute type in enumeration `AttributeType`. Then provide special handling for such attributes in the exporter.

For guidelines on how to become a contributor see [our wiki pages](https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor)

**Comment by PHaroZ** [comment]
I won't introduce an `HTML` attribute type in enumeration `AttributeType` because 
- it's not strictly necessary
- I don't know how it could be handle in other graph language (like gml or visio)
- all are String in DOT attributes so I don't think this would be a good idea to create a new `AttributeType` only for those language

I will do a pull request soon, thanks.

**Comment by d-michail** [comment]
The point of a new attribute type is to allow the user to specify in the exporter whether the exporter should treat the attribute as plain string or as a special html attribute. It is more generic and does not break the existing functionality.

**Comment by PHaroZ** [comment]
I made an alternative PR with this suggested approach.

**Comment by d-michail** [comment]
Resolved in #706.
