### ISSUE TITLE
Reusing edge in another graph replaces source and target

### ISSUE THREAD

**Issue by cdalexndr** [jgrapht/jgrapht#704]
Using method `boolean addEdge(V sourceVertex,
                                V targetVertex,
                                E e)` to add an edge of an existing graph to another graph keeps the edge in the old graph but replaces source and target with vertices from the new graph. 
Thus, when retrieving the edge from the old graph and getting source or target (eg. using `getEdgeSource` graph method), the vertex will not be present in the graph because it has been replaced.

If the edge already has source or target, an exception should be thrown.

**Comment by jkinable** [comment]
The behavior you describe is as intended. You are most likely using DefaultEdge or DefaultWeightedEdge (or an extension thereof) . Both of them are of the type IntrusiveEdge. An intrusive edge stores the source/target/weight information directly on the edge object (as is common for intrusive data types). If you want to avoid this behavior, you should use a non-intrusive edge type, e.g. `Graph<Integer,String> graph=new SimpleGraph<>(String.class);`, or define your own edge type `MyEdge`. The graph will notice that you are using a non-intrusive type, and as a result it will store the information directly in the graph.
Intrusive edge types have some performance and utility advantages over non-intrusive edges.. The disadvantage is that you need to be careful when reusing them in other graphs.

**Comment by jsichi** [comment]
Adding an assert for the invalid reuse case would be nice, but it would require us to consistently null out the vertex references when removing an edge, or even when the user just wanted to "forget" an old graph, so I'm not sure whether it's practical.

**Comment by cdalexndr** [comment]
I already found a workaround (copy the edge), but I reported this issue because I don't think this is valid behavior as it leads to an invalid graph.

**Comment by d-michail** [comment]
This is an optimization. As always optimizations come with trade-offs. You are free to use your own class for the edge.
