### ISSUE TITLE
Feature suggestion: Maximum density subgraphs

### ISSUE THREAD

**Issue by Aimmig** [jgrapht/jgrapht#712]
As a part of my bachelor thesis I implemented an algorithm for finding maximum density subgraphs based on the JGraphT library. As this is now almost finished I'd like to contribute my work.
 
First I'd shortly like to explain the general concept that the algorithm uses:
The idea is described by A. V. Goldberg in "Finding Maximum Density Subgraphs", 1984, University of Berkley, https://www2.eecs.berkeley.edu/Pubs/TechRpts/1984/CSD-84-171.pdf

In most cases the density of a graph could be described as a cost-benefit ratio, considering edge or vertex weights, e. g. the density  could be `|E|/|V|,`  that means you're interested in the subgraph with most edges per vertex.  Usecases include graph/network optimization, e.g social networks or gen networks.

The main idea is to construct a special s-t Network based on the Graph and some guess for the density; this construction (especially the weights of the network) depends on the definition of _density_. Using the Min-Cut of this network, one can decide wether the guess  is too high or low. With a binary search the interval containing the solution can be shrunk, while maintaining a subgraph that has a density at least equal to the current lower bound.

For integer edge weights one can derive, that the correct solution was found, if the interval is smaller than `1/(n(n-1))`. This leads to a runtime of `O(M(n,n+m)log(n))` for the most basic case, where `M(n,m)` is the runtime of the used Min-Cut algorithm. The paper lists some more advanced definitions of density and adjustments to make the generic algorithm work with them, too.

Some implementation details that might be relevant: 

- Since I had to use positive real valued weights (which the original algorithm wouldn't normally terminate with), I shrunk the interval to a given epsilon, such that the maximum density subgraph is found with an error of epsilon.
- Choosing the Min-Cut or Max-Flow-Algorithm was somewhat difficult. For the first try I used Edmonds-Karp for the Min-Cuts, but as it turns out that's a quite bad idea regarding the runtime. So i settled to use the Push-Relabel-Algorithm for the Min-Cuts.
- Because the algorithm works so generically on different definitions of density I could probably make an abstract base class containing all the common stuff that would always be the same. All computations that strictly depend on the density could then be defined in a subclass for just this this density, which would make the code more reusable.

**Comment by d-michail** [comment]
Hi and thanks for your support in JGraphT!  

We are definitely interested in including support for this problem. A few minor comments that will come up when reviewing a pull-request: 

 - We are generally interested for algorithms which can be executed in both undirected and directed graphs. The good news is that in this case, Goldberg states that for directed graphs you can use the associated undirected graph. We have a view called `AsUndirected` for this.
 - When an algorithm can choose among several algorithms for a subproblem (Max-Flow in this case), we usually allow the user to change the algorithm using some constructor parameter (maybe a `Supplier<MaxFlowAlgorithm>`). Of course we also provide a constructor with a sensible default (Push-Relabel) in your case. 
 - We also have a `AsSubgraph` class which might be useful. Unfortunately our current implementation has some drawbacks.
 - As a general principle we try to not modify the user input. For an example of this take a look at `JohnsonShortestPaths`.
 - Consider also including a `MaximumDensitySubgraph` interface. Take a look at shortest paths or maximum flow for examples.
