### ISSUE TITLE
https://jgrapht.org/guide/UserOverview broke

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#713]
Several code blocks in https://jgrapht.org/guide/UserOverview are empty. I wonder whether this is caused by the recent release of jgrapht v1.3.0?

**Comment by d-michail** [comment]
If you try 

```
curl http://code.jgrapht.org/raw/master/jgrapht-demo/src/main/java/org/jgrapht/demo/HelloJGraphT.java?example=findVertex
```
it returns empty.

I think the problem is that there is an extra space between the double slash and the `@` in the following
```
// @example:buildEdges:begin
```
it should be 

```
//@example:buildEdges:begin
```

**Comment by d-michail** [comment]
Probably some scripts that we are running during the deployment changed it.

**Comment by jkinable** [comment]
I suspect that this is caused by the eclipse formatter which we run prior to the release (codeFormatter.sh).

**Comment by jsichi** [comment]
Seems fine; reopen this if there are further problems.
