### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by kanishka-azimi** [jgrapht/jgrapht#715]
I am generally curious about downstream libraries that use graphs, in addition to jgrapht. Whenever I see a downstream library, I look to see how they implemented their graph data structure. Most implement it themselves rather than using a library. This strikes me as bizarre (I don't usually see people inventing their own list or tree data structures). Maybe jgrapht could build a light version, like jgrapht-core-light that provides the bare minimum graph data structure, and see if that gets adopted by more users. I suspect the c igraph library might provide useful API guidance.

**Comment by jsichi** [comment]
You could take a look here:

https://mvnrepository.com/artifact/org.jgrapht/jgrapht-core/usages

**Comment by kanishka-azimi** [comment]
I will update this comment with projects that could use jgrapht:
- graphhopper
- ...
