### ISSUE TITLE
SupplierUtil should get the constructor before execution

### ISSUE THREAD

**Issue by shevek** [jgrapht/jgrapht#717]
```
    public static <T> Supplier<T> createSupplier(Class<? extends T> clazz)
    {
        return (Supplier<T> & Serializable) () -> {
            try {
                return clazz.getDeclaredConstructor().newInstance();
            } catch (Exception ex) {
                throw new RuntimeException("Supplier failed", ex);
            }
        };
    }
```

This should be:
```
    public static <T> Supplier<T> createSupplier(Class<? extends T> clazz)    {
        Constructor<T> constructor = clazz.getDeclaredConstructor();
        return (Supplier<T> & Serializable) () -> {
          return  constructor.newInstance();
      }
    }

```

// Assuming try/catch inserted in the right place. That way the getDeclaredConstructor call is taken out of the main invocation, and errors are discovered earlier. Does the requirement to cast to Serializable break this suggestion?

**Comment by d-michail** [comment]
This will probably make the supplier non-serializable.

**Comment by shevek** [comment]
Oh well, I believe that. One of these days I should see whether that cast-to-& notation really inserts two CHECKCAST instructions. I hope it does. Thank you.

I'll close this issue as we have a good workaround using our own Supplier. I really like the work you are all doing to get the benefit of java 8. It may be worth looking at the Google MapMaker builder as a way to build graphs and escape some of the subclass initialization order nasties with the virtual methods.
