### ISSUE TITLE
On  account of using JGraphT in Ubuntu

### ISSUE THREAD

**Issue by atulim** [jgrapht/jgrapht#724]
Sir,
I am trying to use JGraphT in Ubuntu. I have used -  **mvn archetype:generate -DarchetypeGroupId=org.jgrapht.archetypes -DarchetypeArtifactId=maven-archetype-jgrapht -DarchetypeVersion=1.2.0** code and already installed maven.
I have also created GroupId and other Id. My work Directory is created.
Now can you help me what to do next to use the JGraphT?

**Comment by d-michail** [comment]
Next steps are to read the user overview, the wiki and the javadocs
 - https://jgrapht.org/guide/UserOverview
 - https://github.com/jgrapht/jgrapht/wiki
 - https://jgrapht.org/javadoc/

If you still need help, I would suggest to ask in the users mailing list.

**Comment by atulim** [comment]
Sir,
With due respect , can you mention the steps through which I can run java programs running JGraphT?

Thank you.

**Comment by atulim** [comment]
I am trying this - javac -cp location_name/jgrapht-1.3.0 abc.java. 
But its showing the error that JGraphT doesn't exists.

**Comment by jkinable** [comment]
This does not seem to be a jgrapht issue, but an issue on how to compile java classes which depend on external libraries.
https://stackoverflow.com/questions/9091733/how-do-i-compile-a-java-file-that-has-jar-dependencies
