### ISSUE TITLE
website menu does not render well on mobile

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#727]
The SinglePaged theme we are using is not responsive, so it doesn't fit the menu into the page width on small screens.  Instead, the user has to swipe to pan.

Standard solution would be to use a "hamburger" menu on mobile, or stack it.

**Comment by ksskreddy** [comment]
Can i work on this?

**Comment by jkinable** [comment]
Sure go ahead

**Comment by ksskreddy** [comment]
I added minimum-scale attribute in the view-port meta tag.Now it is perfectly working on the mobile phone.You can check it  [here](https://ksskreddy.github.io/jgrapht/).

Update me if anything else needed for closing the issue.

Thanks,

**Comment by jkinable** [comment]
Looks very nice indeed!

**Comment by jsichi** [comment]
@ksskreddy could you let me know your full name for the credits?

**Comment by ksskreddy** [comment]
Karri Sai Satish Kumar Reddy
