### ISSUE TITLE
Left-right planarity testing algorithm

### ISSUE THREAD

**Issue by Toptachamann** [jgrapht/jgrapht#730]
Hi, 

I'm going to try to add a planarity testing algorithm. [Here](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.217.9208&rep=rep1&type=pdf) I found a description of the left-right planarity test. Also, planarity testing isn't an easy thing, that algorithm is considered easier than, for instance, Hopcroft-Tarjan. Nevertheless, it is one of the fastest algorithms according to this [wiki page](https://en.wikipedia.org/wiki/Left-right_planarity_test). 

Last summer I followed the discussion of adding a planarity testing algorithm and know, that it has to either produce a planar embedding or a certificate of optimality in the form of the Kuratowski subdivision. The extraction of the Kuratowski subdivision is also described in that paper.

**Comment by jkinable** [comment]
Sounds good Timofey!
