### ISSUE TITLE
undirected graph grith 

### ISSUE THREAD

**Issue by Muhammadreda264** [jgrapht/jgrapht#748]
I  implemented and test an algorithm which find the girth of undirected graph based on this https://webcourse.cs.technion.ac.il/234247/Winter2003-2004/ho/WCFiles/Girth.pdf
I have a question .What should i return in case of the graph has now cycle and what should i do before making pull request ?

**Comment by d-michail** [comment]
We already have such an implementation, see class `GraphMetrics`. You should first ask whether a task is still valid, before working on it.
