### ISSUE TITLE
BarabasiAlbertGraphGenerator issue with addVertex()

### ISSUE THREAD

**Issue by emakepuska2** [jgrapht/jgrapht#752]
```
 * JGraphT version:
 * Java version (java -version)/platform:  
```

**Issue**
I am trying to generate graphs with BarabasiAlbertGraphGenerator, the issue is that when creating the V V= target.addVertex() it produces a vertex which is null. The for loop then does not produce the appropriate graph.

**Steps to reproduce (small coding example)**
Is it possible to give me hints or create a Demo as the one you have for CompleteGraphGenerator.

**Expected behaviour**

**Other information**

**Comment by jkinable** [comment]
Did you check the test class:
https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/test/java/org/jgrapht/generate/BarabasiAlbertGraphGeneratorTest.java

Without having more context/code/minimal working example it's impossible to give you more feedback.

**Comment by emakepuska2** [comment]
I will check it out now, thanks!
