### ISSUE TITLE
Feature suggestion: Eppstein`s k shortest paths algorithm

### ISSUE THREAD

**Issue by SChudakov** [jgrapht/jgrapht#754]
I would like to implement the Eppstein`s k algorithm for computing k shortest paths. The algorithm is described in this [article](https://www.ics.uci.edu/~eppstein/pubs/Epp-SJC-98.pdf). Additionally some useful notes can be found [here](https://www.isi.edu/natural-language/people/epp-cs562.pdf).

**Comment by d-michail** [comment]
Related to #131

**Comment by jkinable** [comment]
Completely unrelated, but if you have time/interest, could you have a look at Yen's k-shortest path? There's an abandoned implementation here #413 Based on the conversation in that thread I simply cannot tell whether the implementation is correct or flawed. I do remember there were some potential performance issues with the implementation.

**Comment by SChudakov** [comment]
OK, I will definitely take a look at it.

**Comment by SChudakov** [comment]
Implemented in #755.
