### ISSUE TITLE
ConcurrentModificationException while using outgoingEdgesOf or incomingEdgesOf

### ISSUE THREAD

**Issue by cedric-1** [jgrapht/jgrapht#767]
Hi,

I recently faced an issue using directred graphs in JGraphT. Here are the details : 

```
 * JGraphT version: 1.3.0
 * Java version (java -version)/platform:  1.8.0_144
```

**Issue**

In a directed graph, when I try to use removeAllEdges over a outgoing/incoming EdgesOf call a ConcurrentModificationException is raised.

**Steps to reproduce**

```
import org.jgrapht.graph.SimpleDirectedGraph;

public class JGraphTTest {
	
	public static void main(String[] args) {
		
		final SimpleDirectedGraph<VertexTest,EdgeTest> graph = new SimpleDirectedGraph<VertexTest,EdgeTest>(EdgeTest.class);
		final VertexTest v1 = new VertexTest(1);
		graph.addVertex(v1);
		final VertexTest v2 = new VertexTest(2);
		graph.addVertex(v2);
		final EdgeTest e12 = new EdgeTest(12);
		graph.addEdge(v1, v2, e12);
		final EdgeTest e21 = new EdgeTest(21);
		graph.addEdge(v2, v1, e21);
		
		// graph.removeAllEdges(graph.edgesOf(v1)); // delete both edges, as expected
		// graph.removeAllEdges(graph.outgoingEdgesOf(v1)); // throws java.util.ConcurrentModificationException, expected to delete edge 12
		// graph.removeAllEdges(graph.incomingEdgesOf(v1)); // throws java.util.ConcurrentModificationException, expected to delete edge 21
		
		System.out.println("Vertex list : " + graph.vertexSet());
		System.out.println("Edge list : " + graph.edgeSet());
	}

	private static class VertexTest {
		final int id;
		VertexTest(int id){
			this.id = id;
		}
		@Override
		public String toString(){
			return String.valueOf(this.id);
		}
	}
	
	private static class EdgeTest {
		final int id;
		EdgeTest(int id){
			this.id = id;
		}
		@Override
		public String toString(){
			return String.valueOf(this.id);
		}
	}
}
```

**Expected behaviour**

Just as graph.removeAllEdges(graph.edgesOf(v1)) removes all edges related to v1, I expected graph.removeAllEdges(graph.outgoingEdgesOf(v1)) / graph.removeAllEdges(graph.incomingEdgesOf(v1)) to delete the edges outgoing / incoming from v1. I got a java.util.ConcurrentModificationException instead.

This issue can be avoided by using edgesOf() and selecting only incoming/outgoing edges, but this is less convenient.

Best regards, Cedric

**Comment by jsichi** [comment]
Copy the result to an arraylist and then pass that to removeAllEdges.

**Comment by jsichi** [comment]
We don't make any particular guarantees about these methods; for the default graph implementation, incoming/outgoing happen to return direct views, whereas edgesOf returns a copy, but that behavior can differ for other graph implementations, so you shouldn't rely on it.
