### ISSUE TITLE
JSON Importer/Exporter feature

### ISSUE THREAD

**Issue by spi-x-i** [jgrapht/jgrapht#768]
Hi all.

I'm looking forward to employing jGraphtT in our projects and this is awesome!
Unfortunately, I need a JSON import/export feature and I can't find anything about [importer exporter package](https://jgrapht.org/javadoc/org/jgrapht/io/package-summary.html). 
Somebody has already [asked something similar](https://stackoverflow.com/questions/39438962/how-can-i-serialize-a-jgrapht-simple-graph-to-json) about it on _stackoverflow_. 

So my question is:
Are you planning to add this importer exporter? Did you guys avoid this for any issues related either you won't this?

Thank you for your great work.

Andrea

**Comment by jsichi** [comment]
There are no current plans for JSON import/export.  If you don't need any particular JSON schema, then you can just use one of the other exporters to convert to a string, and then use that string as an attribute in your JSON-serializable object (and then do the reverse on the import side).

**Comment by spi-x-i** [comment]
Hi @jsichi , thank you for the kind answer.
Actually, I need JSON Schema to collaborate with [jsPlumb](https://github.com/jsplumb/jsplumb) on the presentation layer. 

So, AFAIU I need to implement a custom adapter, is it right?

**Comment by d-michail** [comment]
I am not aware of any well established JSON schema for graphs. It does, however, make sense to have at least an exporter, for easy integration with javascript visualization libraries. 

[Cytoscape](http://manual.cytoscape.org/en/stable/Supported_Network_File_Formats.html) has a custom JSON exporter and so does [Gephi](https://gephi.org/).  

Maybe it makes sense to output something compatible with [sigmajs](http://sigmajs.org/).

Regarding implementation you need to implement `GraphExporter`. See the jgrapht-io package for several examples.

**Comment by d-michail** [comment]
We have added both an exporter (#775) and an importer (#783).
