### ISSUE TITLE
What's the best way to deal with unchecked call warnings?

### ISSUE THREAD

**Issue by sammyjava** [jgrapht/jgrapht#777]
So this isn't really an issue but a Java coding practice question. I'm getting a lot of **unchecked call** warnings when I implement JGraphT interfaces or extend JGraphT classes. I thought I understood generics and typing, but I've not come up with the proper way to avoid these messages other than `@SuppressWarnings`.

Suggestions?

 * JGraphT version:
```
    // https://mvnrepository.com/artifact/org.jgrapht/jgrapht-core
    compile group: 'org.jgrapht', name: 'jgrapht-core', version: '1.3.0'
```
 * Java version (java -version)/platform:  
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)
```
**Issue**
```
> Task :compileJava
/home/shokin/java/ncgr/fr/src/main/java/org/ncgr/jgraph/PathWalk.java:27: warning: [unchecked] unchecked call to GraphWalk(Graph<V,E>,List<V>,double) as a member of the raw type GraphWalk
        super(graph, nodeList, 1.0);
             ^
  where V,E are type-variables:
    V extends Object declared in class GraphWalk
    E extends Object declared in class GraphWalk
1 warning
```
**Steps to reproduce (small coding example)**
```
public class PathWalk extends GraphWalk implements Comparable<PathWalk> {

    String name;     // the name identifying this path, a sample or individual
    int genotype;    // the genotype identifier for this path: 0 or 1
    String label;    // an optional label, like "+1", "-1", "case", "control", "M", "F"
    String sequence; // this path's full genomic sequence

    /**
     * Creates a walk defined by a sequence of nodes; weight=1.0.
     */
    PathWalk(Graph<Node,Edge> graph, List<Node> nodeList) {
        super(graph, nodeList, 1.0);
    }
```
**Expected behaviour**

This is expected, but I'd like to figure out how to avoid it properly, without using @SuppressWarnings.

**Comment by jkinable** [comment]
Please ask your questions on stackoverflow (use tag: jgrapht).

Short answer: GraphWalk is a generic class: `GraphWalk<V, E>` so you must specify V and E.
Solution 1:
`public class PathWalk<V,E> extends GraphWalk<V,E> implements Comparable<PathWalk<V,E>>`
or
Solution 2:
`public class PathWalk extends GraphWalk<Node,Edge> implements Comparable<PathWalk>`

From your issue it seems you are looking for solution 2.

**Comment by sammyjava** [comment]
Boom! Thanks! I'll hit stackoverflow for future non-issues. :)
