### ISSUE TITLE
If duplicate edge weight, then addEdge() fails.

### ISSUE THREAD

**Issue by uncttao** [jgrapht/jgrapht#784]
```
 * JGraphT version: 1.3.0
 * Java version (java -version)/platform:  Java 10/Windows
```

**Issue**
If duplicate edge weight, then addEdge() fails.
For example, use String as the edge type. If I have two different edges (i.e. two edges that connect different pairs of vertices) with the same String, then addEdge() returns false (reporting that the edge already exists).

**Steps to reproduce (small coding example)**
(described above)

**Expected behaviour**
Adding edge should not fail in the above circumstance.

**Other information**

**Comment by jsichi** [comment]
The behavior you observe is correct.  Please read this doc:

https://jgrapht.org/guide/VertexAndEdgeTypes
