### ISSUE TITLE
VF2 isomorphism algorithm does not support directed weighted graphs. Perhaps raise exception if intended?

### ISSUE THREAD

**Issue by uncttao** [jgrapht/jgrapht#785]
```
 * JGraphT version: 1.3.0
 * Java version (java -version)/platform:  Java 10 / Windows
```

**Issue**

When running `VF2GraphIsomorphismInspector::isomorphismExists` on two `SimpleDirectedWeightedGraph`s, the result may be incorrect (see example below).

If the VF2 algorithm does not support directed weighted graphs, perhaps JGraphT should raise an exception saying it is not supported instead of silently yielding wrong results?

**Steps to reproduce (small coding example)**

Construct two `SimpleDirectedWeightedGraph`.
`g1`: 1 ->(99)-> 3; 2 ->(99)-> 3
`g2`: 3 ->(99)-> 1; 3 ->(99)-> 2
> ->(99)-> means the edge weight is 99: Integer.

Run `VF2GraphIsomorphismInspector(g1, g2).isomorphismExists()`.

The algorithm reports they are isomorphic.

**Expected behaviour**

Either report correct results for all `SimpleDirectedWeightedGraph` isomorphism detection, or raise unsupported exceptions.

**Other information**

N/A

**Comment by d-michail** [comment]
There are a lot of stuff in JGraphT which depend on equality of vertices, edges, proper use of hashCode() and equals(), etc. 

Please submit the full code of a [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example). Preferably as a unit test. 

Thanks

**Comment by d-michail** [comment]
I just tested the scenario that you are describing and I get no isomorphism. My code is the following

```
    @Test
    public void testDirectedWeighted()
    {
        Graph<Integer,
            DefaultWeightedEdge> g1 = GraphTypeBuilder
                .directed().weighted(true).vertexSupplier(SupplierUtil.createIntegerSupplier())
                .edgeSupplier(SupplierUtil.DEFAULT_WEIGHTED_EDGE_SUPPLIER).buildGraph();

        g1.addVertex(1);
        g1.addVertex(2);
        g1.addVertex(3);
        g1.setEdgeWeight(g1.addEdge(1, 3), 99);
        g1.setEdgeWeight(g1.addEdge(2, 3), 99);

        Graph<Integer,
            DefaultWeightedEdge> g2 = GraphTypeBuilder
                .directed().weighted(true).vertexSupplier(SupplierUtil.createIntegerSupplier())
                .edgeSupplier(SupplierUtil.DEFAULT_WEIGHTED_EDGE_SUPPLIER).buildGraph();

        g2.addVertex(1);
        g2.addVertex(2);
        g2.addVertex(3);

        g2.setEdgeWeight(g2.addEdge(3, 1), 99);
        g2.setEdgeWeight(g2.addEdge(3, 2), 99);

        VF2GraphIsomorphismInspector<Integer, DefaultWeightedEdge> vf =
            new VF2GraphIsomorphismInspector<>(g1, g2);

        assertFalse(vf.isomorphismExists());
    }
```

If you still think that there is a bug, you need to submit as I mentioned in my previous post, a minimal reproducible example.

**Comment by uncttao** [comment]
The code I used was

```kotlin
val g1 = SimpleDirectedWeightedGraph<Int, Int>(null, null)
g1.addVertex(1)
g1.addVertex(2)
g1.addVertex(3)
g1.addEdge(1, 3, 99)
g1.addEdge(2, 3, 99)

val g2 = SimpleDirectedWeightedGraph<Int, Int>(null, null)
g2.addVertex(1)
g2.addVertex(2)
g2.addVertex(3)
g2.addEdge(3, 1, 99)
g2.addEdge(3, 2, 99)

println(VF2GraphIsomorphismInspector(g1, g2).isomorphismExists())
```

It's in Kotlin but that should not be a problem.

Perhaps I got wrong use of graph constructors? As you noticed I did not use the graph builder interface.

**Comment by d-michail** [comment]
My example works fine even if you construct the graphs using 
```
Graph<Integer, DefaultWeightedEdge> g1 = new SimpleDirectedWeightedGraph<>(DefaultWeightedEdge.class);
```

Your issue is different. The 3rd parameter of the call to `addEdge` is not the weight, but the actual edge instance. You are using the edge 99 multiple times in your graph. 

Please read the following [VertexAndEdgeTypes](https://jgrapht.org/guide/VertexAndEdgeTypes).

Quick fix would be to use

```
DefaultWeightedEdge e = new DefaultWeightedEdge();
g1.addEdge(1,3, e);
g1.setWeight(e, 99);
```

Otherwise, use an edge supplier as I am doing and use

```
g1.setWeight(g1.addEdge(1,3), 99);
```

**Comment by uncttao** [comment]
OK. I guess that is that.

However, I modified your Java example a bit and the following result is nevertheless unexpected.

```java
Graph<Integer,
    DefaultWeightedEdge> g1 = GraphTypeBuilder
    .directed().weighted(true).vertexSupplier(SupplierUtil.createIntegerSupplier())
    .edgeSupplier(SupplierUtil.DEFAULT_WEIGHTED_EDGE_SUPPLIER).buildGraph();

g1.addVertex(1);
g1.addVertex(2);
g1.addVertex(3);
g1.setEdgeWeight(g1.addEdge(1, 3), 99);
g1.setEdgeWeight(g1.addEdge(2, 3), 99);

Graph<Integer,
            DefaultWeightedEdge> g2 = GraphTypeBuilder
    .directed().weighted(true).vertexSupplier(SupplierUtil.createIntegerSupplier())
    .edgeSupplier(SupplierUtil.DEFAULT_WEIGHTED_EDGE_SUPPLIER).buildGraph();

g2.addVertex(4);    // Here
g2.addVertex(5);    // Here
g2.addVertex(6);    // Here

g2.setEdgeWeight(g2.addEdge(4, 6), 96);    // Here
g2.setEdgeWeight(g2.addEdge(5, 6), 99);    // Here

VF2GraphIsomorphismInspector<Integer, DefaultWeightedEdge> vf =
    new VF2GraphIsomorphismInspector<>(g1, g2);

System.out.println(vf.isomorphismExists());     // true
```

**Comment by d-michail** [comment]
The algorithm, in its default setting, does not care about weights. If you do care about weights, you need to provide another constructor argument which is the `edgeComparator`. 

I guess the documentation needs to be improved.
