### ISSUE TITLE
Upgrade advice

### ISSUE THREAD

**Issue by cosmincatalin** [jgrapht/jgrapht#807]
I am are currently using the `ChromaticNumber` algorithm on version 0.9.2 of the library.
I would like to upgrade to the latest version but am unsure of the algorithm to choose for replacing `ChromaticNumber`.
I would like the results to be as much as possible the same when using one of the suggested algorithms.

**Comment by d-michail** [comment]
Version 0.9.2 included the greedy algorithm which first sorted the vertices by degree and then colored the vertices greedily. This means that in current versions you should use `LargestDegreeFirstColoring`.

However, the `SaturationDegreeColoring` is slighly slower but might give you better results w.r.t the number of colors used.

**Comment by cosmincatalin** [comment]
Thank you for the quick response. I will try that.
