### ISSUE TITLE
ArrayDeque is (usually) much faster than LinkedList

### ISSUE THREAD

**Issue by shevek** [jgrapht/jgrapht#809]
https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/traverse/TopologicalOrderIterator.java#L96

Consider ArrayDeque. Just a thought, I haven't proved it.

**Comment by rtkg12** [comment]
I would like to contribute to this project and this seems like a great first issue. Can I work on this?

**Comment by jsichi** [comment]
Yes, that would be great!

**Comment by rtkg12** [comment]
Perfect! I'll try to send a PR as soon as possible. Since I'm new to this project and open source in general, it would be great if you could send me any guidelines you have for unit tests, etc. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jsichi** [comment]
As a matter of fact we do :)

https://github.com/jgrapht/jgrapht/wiki/Dev-guide%3A-How-to-make-your-first-%28code%29-contribution

**Comment by rtkg12** [comment]
Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
