### ISSUE TITLE
Graph with clusters

### ISSUE THREAD

**Issue by edwinjo555** [jgrapht/jgrapht#817]
Is there any way to create a graph with clusters? 
In the graph below, "process #1" and "process #2" are clusters

![download](https://user-images.githubusercontent.com/40605196/64417119-22eb9300-d0b6-11e9-8aab-c41dea0d1667.png)

Expected dot file content : 

digraph G {

  subgraph cluster_0 {
    style=filled;
    color=lightgrey;
    node [style=filled,color=white];
    a0 -> a1 -> a2 -> a3;
    label = "process #1";
  }

  subgraph cluster_1 {
    node [style=filled];
    b0 -> b1 -> b2 -> b3;
    label = "process #2";
    color=blue
  }
  start -> a0;
  start -> b0;
  a1 -> b3;
  b2 -> a3;
  a3 -> a0;
  a3 -> end;
  b3 -> end;

  start [shape=Mdiamond];
  end [shape=Msquare];
}

**Comment by jkinable** [comment]
Please ask your question on stackoverflow using the jgrapht tag. That way, other users can find your questions/answers as well.

**Comment by jkinable** [comment]
Question answered in: https://stackoverflow.com/questions/57820898/creating-graph-with-clusters-using-jgrapht/57837344#57837344
