### ISSUE TITLE
SupplierUtil.createSupplier returns a slow supplier

### ISSUE THREAD

**Issue by shevek** [jgrapht/jgrapht#820]
**Issue**

https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/util/SupplierUtil.java#L58

Calls getDeclaredConstructor every time.

**Expected behaviour**

Hoist the call to getDeclaredConstructor and close over it.
```
    @Nonnull
    public static <T> Supplier<T> createSupplier(Class<? extends T> edgeClass) {
        try {
            Constructor<? extends E> constructor = edgeClass.getDeclaredConstructor();
            return () -> {
                try {
                    return constructor.newInstance();
                } catch (ReflectiveOperationException e) {
                    throw new RuntimeException(e);
                }
            };
        } catch (ReflectiveOperationException | SecurityException e) {
            throw new RuntimeException(e);
        }
    }
```

**Conclusions**

LOL another performance issue from those random idiots who are doing WTF? :D :D

**Comment by jkinable** [comment]
Can you be a little bit more descriptive: what exactly is the issue. Are you proposing some solution or not?

**Comment by shevek** [comment]
The code I linked to in jgrapht is slow. The code I pasted is a much faster replacement.

**Comment by shevek** [comment]
Hrm, I guess what I pasted into #820 was just as good, I see now why it can't be hoisted: Constructor isn't serializable (without e.g. TypeSerializer). However, we changed this because of a significant perf difference. Perhaps this can't merge into mainline.

**Comment by d-michail** [comment]
Is it possible to explain why you need such a performance increase? Do you create a lot of different small graphs? 

In this case you could create the graph using a precomputed supplier using `GraphTypeBuilder`.

```
Graph<String, DefaultEdge> g = GraphTypeBuilder
                .undirected()
                .allowingMultipleEdges(true)
                .allowingSelfLoops(true)
                .vertexSupplier(SupplierUtil.createStringSupplier())
                .edgeSupplier(SupplierUtil.DEFAULT_EDGE_SUPPLIER)
                .buildGraph()
```

I am a bit reluctant in including code which does too much reflection. We recently had success with using ahead-of-time compilation by using the recently introduced GraalVM. As you may expect, reflection APIs and AOT compilation do not go well together.

**Comment by shevek** [comment]
In the current implementation, it's the EXECUTION of the supplier which is slow, because it calls getDeclaredConstructor() every time, not the CREATION of the supplier, which is fast.

**Comment by shevek** [comment]
Even if you only have one graph, this patch gives a 2x-3x speedup. Honestly, if the serialization is important, drop this one. We should be using lambdas as suppliers anyway; using an edge-class rather than an edge-supplier is pretty deprecated, right? Again, in jgrapt-ext or jgrapht-opt, using reflectasm will be even faster by another order of magnitude, even for a single graph.

**Comment by shevek** [comment]
Mind you, even in the PR I made, making the Constructor transient and adding ser/deser hooks is probably worth it for a 2x perf increase on adding nodes.

**Comment by shevek** [comment]
There, I pushed a new commit. :grin: Let's see how badly that breaks.

**Comment by jsichi** [comment]
@d-michail we were already using reflection here (clazz.getDeclaredConstructor.newInstance), so I don't think this change will add any extra reflection configuration requirement.

**Comment by d-michail** [comment]
I am mostly concerned with stuff like adjusting permissions using reflection. I can certainly try testing the resulting code w.r.t AOT before we merge anything.

**Comment by d-michail** [comment]
I tested AOT and there is no problem with this change. 

Closing this one in favor of version with proper serialization (#821).
