### ISSUE TITLE
enforce checkstyle for test directories

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#823]
The default for the includeTestSourceDirectory configuration parameter is false; we need to set it to true in order for checkstyle to be applied to tests.  But first we have to clean up all the existing violations in test files.

**Comment by besza** [comment]
What would be the requirement for test files regarding Javadoc?

The biggest blocker for going forward with this is the massive amount of errors (~1900) for missing Javadoc (package, type, method). I think it is an unreasonable expectation to add them retroactively and even then I think it would serve no purpose.

Suppressing the above mentioned checks for test files gives us the following report:
[jgrapht-checkstyle-report-20201017.txt](https://github.com/jgrapht/jgrapht/files/5395578/jgrapht-checkstyle-report-20201017.txt)

**Comment by jsichi** [comment]
I agree, highest priority should be on rules for things such as making sure all files have the correct headers.  It would be fine to defer the Javadoc portion for now, or maybe forever.

The etc/checkstyle_suppressions.xml file can be used to selectively suppress checks for the test files (at least I hope that will work).
