### ISSUE TITLE
'Jon Arryn' is not a valid value for 'NMTOKEN'

### ISSUE THREAD

**Issue by florecista** [jgrapht/jgrapht#831]
```
 * JGraphT version: 1.3.1
 * Java version / platform:  Open JDK Zulu 11
```

**Issue**
I'm testing org.jgrapht.io.GraphMLImporter with some different GraphML files and for a couple of them I'm hitting this error - org.xml.sax.SAXParseException; lineNumber: 291; columnNumber: 28; cvc-datatype-valid.1.2.1: 'Jon Arryn' is not a valid value for 'NMTOKEN'.

'Jon Arryn' is an id for a node. I'm not sure why it is causing the import to fail.

Line 291 is the open node tag below -

```
      <node id="Jon Arryn">
         <data key="label">Jon Arryn</data>
      </node>
```

The unit test is here -

https://github.com/florecista/jgrapht-graphml-test/blob/master/src/test/java/GOTNetworkFileTest.java

The GraphML file is here -

https://github.com/florecista/jgrapht-graphml-test/blob/master/src/test/resources/data/got-network.graphml

I understand that org.jgrapht.io.GraphMLImporter is most likely working perfectly and it is the format of the GraphML file I am using so this might not be the forum for requesting help. Apologies if that is the case.

I can't understand why the id of a node is breaking the import.

**Steps to reproduce (small coding example)**
Simply run the test

**Expected behaviour**
The expected result is to read the GraphML file into memory and be able to set up some assertions on numbers of Nodes and Edges.

Any advice is greatly appreciated.

**Comment by d-michail** [comment]
NMTOKEN does not allow whitespace, which means that the identifier cannot contain whitespace.

**Comment by florecista** [comment]
Huge thank you.
I wrongly assumed this file I inherited was 'good to go'..... My bad.
