### ISSUE TITLE
Bollobas Directed scale-free graph generator implementation

### ISSUE THREAD

**Issue by aalhossary** [jgrapht/jgrapht#832]
**Issue**
I created a generator for _Bollobas Directed scale-free graph_ , described in:

> Bollobás, Béla, et al. "Directed scale-free graphs." Proceedings of the fourteenth annual ACM-SIAM symposium on Discrete algorithms. Society for Industrial and Applied Mathematics, 2003.

https://dl.acm.org/citation.cfm?id=644133

The class and unit test are available at
https://github.com/aalhossary/jgrapht/commit/675dd2681634bfff4539d3e7d7e3930e8b560a87
Shall I open a Pull Request now?

**Comment by d-michail** [comment]
Yes. I would suggest to simply name it `DirectedScaleFreeGraphGenerator` and mention the paper and all authors in the documentation of the class. 

Usually in SODA (the conference where this paper first appeared) the author names are listed in alphabetical order.

**Comment by aalhossary** [comment]
Done!
Travis CI build passed as well.

**Comment by d-michail** [comment]
Implemented in #833.
