### ISSUE TITLE
NaiveLCAFinder.getLCA may return a common ancestor but not lowest

### ISSUE THREAD

**Issue by sh5i** [jgrapht/jgrapht#839]
```
 * JGraphT version: 1.3.1
 * Java version (java -version)/platform:
java version "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)
```

**Issue**
`NaiveLCAFinder.getLCA` may reach a common but not lowest ancestor earlier than any lowest ones and return it incorrectly.

**Steps to reproduce (small coding example)**
Test.java:
```
import org.jgrapht.alg.lca.NaiveLCAFinder;
import org.jgrapht.graph.DirectedAcyclicGraph;
public class Test {
    public static void main(String[] args) {
        DirectedAcyclicGraph<Integer, Object> g = new DirectedAcyclicGraph<>(Object.class);
        g.addVertex(1);
        g.addVertex(2);
        g.addVertex(3);
        g.addVertex(4);
        g.addEdge(1, 2);
        g.addEdge(2, 3);
        g.addEdge(3, 4);
        g.addEdge(1, 4);
        NaiveLCAFinder<Integer, Object> finder = new NaiveLCAFinder<>(g);
        System.out.println(finder.getLCASet(2, 4));
        System.out.println(finder.getLCA(2, 4));
    }
}
```

```
$ javac -cp jgrapht-core-1.3.1.jar Test.java
$ java -cp .:jgrapht-core-1.3.1.jar Test
[2]
1
```

**Expected behaviour**
```
[2]
2
```

**Other information**
`NaiveLCAFinder.getLCASet` seems to be correct, which leads to a strange situation that the result set of `getLCASet` does not include the result of `getLCA`.

**Comment by d-michail** [comment]
Nice catch! It seems the problem is this [if statement](https://github.com/jgrapht/jgrapht/blob/a8e7fddd579cce683313a312c7ca9d753bcbd0bc/jgrapht-core/src/main/java/org/jgrapht/alg/lca/NaiveLCAFinder.java#L228). If you remove it, it works.

@AlexandruValeanu Would it be possible to have a closer look?
