### ISSUE TITLE
HashMap capacity computed incorrectly

### ISSUE THREAD

**Issue by HannesWell** [jgrapht/jgrapht#846]
```
 * JGraphT version: 1.3.1
 * Java version (java -version)/platform:  all
```

**Issue**
When going trough JGraphT I noticed that for many `(Linked)HashMap` creations in JGraphT the int-argument constructor is used to specify the Map's initial capacity. This good in order to avoid rehashing/resizing of the backing array. But unfortunately the default load factor of `(Linked)HashMap` is never considered, so even if only the indented number of elements is added, the internal storage of the Map is likely resized, which causes additional runtime.

The int-argument in the constructor of `(Linked)HashMap` specifies an initial capacity/size of the Map's internal storage rather than an initial _size_ of the Map. Unlike for example an `ArrayList` a `(Linked)HashMap` is usually not fully populated in order to improve performance in case of hash-collisions.
Therefore one can add as many elements as specified in the int-constructor to an `ArrayList` without any resizing of the internal storage, but for an `(Linked)HashMap` resizing of the backing array happens before the `Map` has a `size` equal to the specified capacity. The maximal population-degree is expressed by the _load factor_ of a Map who has a default value of `0.75f` in present and previous OpenJDK implementations. See [java.util.HashMap](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html)for more details. In order to avoid rehashing this load factor need to be considered in a way like this:

>  new HashMap<>((int) (expectedSize / 0.75f + 1)); // for default load factor of 0.75f

**Proposal for solution**
Google's Guava library provides the method [`newHashMapWithExpectedSize(int)` in its `com.google.common.collect.Maps`](https://github.com/google/guava/blob/28b36c80447729d1edeffedd70dc4a7ac91e76ce/guava/src/com/google/common/collect/Maps.java#L317) utility class to address this issue.

Since Guava is not available within JGraphT, JGraphT could provide its own `org.jgrapht.util.MapUtil` with a similar method. That method could be called everywhere in the library where a Map with an expected size is created.

If your are interested in such a solution I would be glad to contribute it.

**Expected outcome**
Slightly reduced runtime of all code that uses `(Linked)HashMap` with an expected size due to less rehashing while populating the Map, especially for large graphs.

**Comment by jsichi** [comment]
Your MapUtil proposal sounds good to me.

**Comment by HannesWell** [comment]
Happy to hear that.
I was about to submit a PR and it came into my mind that the capacity!=expectedSize-issue also applies to HashSet and LinkedHashSet. I think I should cover that, too.

To avoid too many small utility classes I will create a `CollectionUtil` class that also provides the corresponding methods for `HashSet` and `LinkedHashSet`. When other `Collection` related utility methods are required in the future and are not available in `java.util.Collections` they could go there. The unqualified class name also does not clash with `java.util.Collections` so both can be used in one class without fully qualified class names.

**Comment by HannesWell** [comment]
The PR to solve this issue is merged.
