### ISSUE TITLE
Sparse Kuhn-Munkres / Sparse cost-matrix

### ISSUE THREAD

**Issue by harmanpa** [jgrapht/jgrapht#848]
```
 * JGraphT version: 1.3.2-SNAPSHOT
 * Java version (java -version)/platform:  java8
```

**Issue**

```KuhnMunkresMinimalWeightBipartitePerfectMatching``` uses 2 n x n double[][] matrices, consequently it doesn't scale well to large problems.

The newly-added (@d-michail) ```CSRBooleanMatrix``` would be ideal for building a class representing a sparse cost-matrix which would enhance Kukn-Munkres and probably some other algorithms.

Is this something already planned?

**Comment by d-michail** [comment]
In the Hungarian algorithm the matrix is dense (it is a complete bipartite graph) so using a sparse matrix is not going to make things better. 

However, this might be true in other places.

The drawback of the sparse matrix (in CSR) is that you (partially) loose random access. It is very efficient if you always need to read the entire row, e.g. multiplying matrix with vector or accessing all adjacent vertices of a particular vertex.

If we indeed find a place where is makes sense, we could move this class (and probably one with Double values) in the util package.

**Comment by harmanpa** [comment]
I was assuming this was equivalent to the Jonker-Volgenant linear-assignment algorithm, which definitely supports a sparse matrix (https://github.com/kylemcdonald/ofxAssignment/blob/master/src/jv/lap.cpp).

**Comment by d-michail** [comment]
In `KuhnMunkresMinimalWeightBipartitePerfectMatching` we assume a complete instance.

In `MaximumWeightBipartiteMatching` the graph may be sparse, but there is no explicit matrix there, so you may get the additional benefit by simply using the weighted  sparse graph we introduced.

**Comment by Toptachamann** [comment]
@harmanpa you can look into the `KolmogorovWeightedPerfectMatching` or `KolmogorovWeightedMatching` as well if your use case requires running an algorithm on a sparse graph. If you specify `BlossomVOptions.InitializationType.FRACTIONAL` and your graph is bipartite, the problem will be solved during the initialization phase without too much heavy computation. 

Please, let me know if this is still an issue for you.
