### ISSUE TITLE
Merge Graphs

### ISSUE THREAD

**Issue by techmoksha** [jgrapht/jgrapht#86]
Hi,

I had a problem of merging 2 acyclic graphs such that there are no duplicates and also the merged graph needs to retain the acyclic nature. I think the library has all the pieces for this, just that they are not centralized. If you find this issue valid, I can add a general merge utility API.

**Comment by jkinable** [comment]
" there are no duplicates" -> Duplicates of what?
In general, there is no way to guarantee that the sum of 2 acyclic graph is still acyclic.
