### ISSUE TITLE
MaskEdgeSet + MaskVertexSet size calculation should be cached

### ISSUE THREAD

**Issue by omerb4** [jgrapht/jgrapht#871]
```
 * JGraphT version: 1.2.0
 * Java version (java -version)/platform:  11.0.4
```

**Issue**

When calculation size of MaskEdgeSet \ MaskVertexSet the result should be always the same.
In case I'll call the size method for the second time I will go through all the graph again and calculate the same number while there's no change in the graph between those 2 calls.

I suggest to cache the size result once it called in the first time and then use the cached result to return it in the second time.

**Steps to reproduce (small coding example)**

**Expected behaviour**

**Other information**

**Comment by d-michail** [comment]
The point of `MaskSubgraph` is to be a live version of the original graph. Changes in the underlying graph should be reflected in the `MaskSubgraph`. 

If you want to cache, you can extend class `MaskSubgraph` and replace the returned set with one that does the caching.
