### ISSUE TITLE
[QUESTION] Retain vertex values when importing a graph

### ISSUE THREAD

**Issue by ishanSharma07** [jgrapht/jgrapht#883]
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform:  openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~19.10-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

```

**Issue**
- Generated a graph with vertex of string datatype of the format "x-y-z".
- Stored the graph in Graph6 format.
- Read the graph and printed it using the toString() method.
- After reading the structure is intact but the vertex values are not the ones written to the file.

* I have read through the examples provided [here](https://github.com/jgrapht/jgrapht/tree/master/jgrapht-io/src/test/java/org/jgrapht/nio/guessraph6) and coding example is from the same. 
* I understood that this is related to the vertex supplier. But is there a way to "not supply a vertex supplier" so that the vertex values are retained from the file. 
* I guess this also extends to vertex type of a user defined class.

**Steps to reproduce (small coding example)**
```
package com.dreamlab.test.testing_maven;

import org.jgrapht.*;
import org.jgrapht.alg.interfaces.ShortestPathAlgorithm.SingleSourcePaths;
import org.jgrapht.alg.shortestpath.DijkstraShortestPath;
import org.jgrapht.graph.*;
import org.jgrapht.graph.builder.*;
import org.jgrapht.nio.csv.*;
import org.jgrapht.nio.graph6.Graph6Sparse6Exporter;
import org.jgrapht.nio.graph6.Graph6Sparse6Importer;
import org.jgrapht.util.*;
import org.junit.*;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.concurrent.TimeUnit;
	
public class HelloJGraphT {
	
	public void writeGraph6sparse6(Graph<String,DefaultEdge> g, Graph6Sparse6Exporter.Format format, String fileName) {
		Graph6Sparse6Exporter<String, DefaultEdge> exporter = new Graph6Sparse6Exporter<>(format);
		ByteArrayOutputStream bos = new ByteArrayOutputStream();
		exporter.exportGraph(g, bos);
		
		OutputStream os = null;
		BufferedOutputStream buffOut  = null;
		
		try {
			//create a file outputstream
			Path newFilePath = Paths.get(fileName);
			os = Files.newOutputStream(Files.createFile(newFilePath));
			buffOut = new BufferedOutputStream(os);
			bos.writeTo(buffOut);
			
		} catch(IOException e) {
			e.printStackTrace();
		} finally {
			try {
				buffOut.close();
				bos.close();
			} catch(IOException e) {
				e.printStackTrace();
			}
		}			
	}
	
	public Graph<String, DefaultEdge> readGraph6Sparse6(String fileName) {
		//init the graph builder
		Graph<String, DefaultEdge> g = GraphTypeBuilder
	            .undirected().allowingMultipleEdges(true).allowingSelfLoops(true).weighted(false)
	            .vertexSupplier(SupplierUtil.createStringSupplier()).edgeClass(DefaultEdge.class).buildGraph();;
		
		//init streams to null
		ByteArrayInputStream bis = null;
		InputStream is = null;
		BufferedInputStream buffIn = null;
		InputStreamReader isr = null;
		
		//define importer
		Graph6Sparse6Importer<String, DefaultEdge> importer =  new Graph6Sparse6Importer();
		try {
			Path filePath = Paths.get(fileName);
			is = Files.newInputStream(filePath);
			buffIn = new BufferedInputStream(is);
			bis = new ByteArrayInputStream(buffIn.readAllBytes());
			isr = new InputStreamReader(bis);
			
			//import the graph
			
		    importer.importGraph(g, isr);
			
		} catch(IOException e) {
			e.printStackTrace();
		} finally {
			try {
				isr.close();
			} catch(IOException e) {
				e.printStackTrace();
			}
		}
		
		return g;			
	}
	 
    public static void main(String args[]) {
    	HelloJGraphT obj = new HelloJGraphT();
    	Graph<String, DefaultEdge> g = new SimpleGraph<>(DefaultEdge.class);
    	Graphs.addAllVertices(g, Arrays.asList("0-0-0","0-0-1","0-0-2"));
    	g.addEdge("0-0-0", "0-0-1");
    	g.addEdge("0-0-1", "0-0-2");
    	g.addEdge("0-0-2", "0-0-0");
    	System.out.println(g);
    	
    	//exporting the graph
    	obj.writeGraph6sparse6(g, Graph6Sparse6Exporter.Format.GRAPH6, "/home/ishan/test.graph6");
    	//importing the graph
    	Graph<String, DefaultEdge> rG = obj.readGraph6Sparse6("/home/ishan/test.graph6");
    	System.out.println(rG);    	
    }
}

```

**Expected behaviour**
- After reading the graph the vertex values should be the same as the ones that were written in the graph.

**Other information**

**Comment by jsichi** [comment]
It should be possible to get the desired behavior back via:

https://github.com/jgrapht/jgrapht/pull/882

**Comment by d-michail** [comment]
The `sparse6` format does not preserve vertex labels. These are compact graph formats which assume that vertices are integers starting from 0. Even if your vertices are not integers, when you output to a file it is assumed they are. 

This means that whatever graph you output in a `sparse6` or `graph6` format, when you read it back, you will get integers in the range of $0..n-1$ where $n$ is the number of vertices. There is no choice here, as the format loses the information.

Thus, using `SupplierUtil.createIntegerSupplier()` for the vertex supplier will read back exactly what is written to the file. If you want vertices to be strings, you can use `SupplierUtil.createStringSupplier()`.

If you require to maintain vertex information, you must choose some other exporter.

**Comment by d-michail** [comment]
I added a vertex factory in #885 but it will still not solve your problem. 

When you read the graph, your vertices are always going to be `0,1,2,...` since that is the only information in the file.

**Comment by jsichi** [comment]
Oops, I was speed-reading when I saw this issue :)

**Comment by ishanSharma07** [comment]
Thanks a lot. I used csv format, [#822]{https://github.com/jgrapht/jgrapht/pull/882} works perfectly.
