### ISSUE TITLE
Contribution proposal: faster exact graph coloring

### ISSUE THREAD

**Issue by kazimierz-256** [jgrapht/jgrapht#886]
**Hi JGraphT community!**

The existing BrownBacktrackColoring algorithm is great but it starts to struggle to color graphs having only 40 vertices. I spent months optimizing my custom solver (in C#) that starts to struggle with graphs having 60 vertices! The problem is NP-Complete so this kind of improvement is a big deal. The algorithm is already tested (in C#) and circulates in the literature as the backGCP algorithm.

I am considering contributing the algorithm to JGraphT, therefore, I would like to consult the community: **Is such a contribution in demand**?

**Comment by d-michail** [comment]
Yes of course. Such an improvement would be most welcome. Best to write it in its own class.
