### ISSUE TITLE
BetweennessCentrality and multiple parallel edges

### ISSUE THREAD

**Issue by dpdearing** [jgrapht/jgrapht#890]
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform:  AdoptOpenJDK (build 11.0.6+10) / macOS
```

**Issue**

When using `BetweennessCentrality`to calculate the betweenness scores of a graph with parallel edges, the parallel edges are treated as separate edge weights.

https://github.com/jgrapht/jgrapht/blob/b40f575e9d9a1c2742b45556025dd5920cc1e9dc/jgrapht-core/src/main/java/org/jgrapht/alg/scoring/BetweennessCentrality.java#L177-L179

**Expected behaviour**

The weight of multiple parallel edges to be combined when calculating the distance/edge weight between vertices `v` and `w`

**Comment by dpdearing** [comment]
After further thought, I wonder if the current behavior is intentional for a graph with multiple parallel edges?

Should weighted betweenness centrality be calculated using the edge with the lowest weight among many parallel edges or the total sum of parallel edge weights?

**Comment by d-michail** [comment]
The algorithm of Brandes supports both self-loops and multiple edges. See his paper 
"A Faster Algorithm for Betweenness Centrality".

In general, reductions and special cases like the one you are describing should happen on the "user" side. If you want to use the lowest weight, you can either build a new graph which only contains the lowest weight, or you can mask out the remaining edges, etc.  The same with the total sum of the multiple edge weights, you can build a graph with a single edge and adjust its weight accordingly.

**Comment by dpdearing** [comment]
Thanks for the information.  Closing.
