### ISSUE TITLE
KShortestSimplePaths bug

### ISSUE THREAD

**Issue by SChudakov** [jgrapht/jgrapht#892]
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform:  11.0.6 / Ubuntu 18.04 LTS
```

I\`ve encountered a following bug in the  `KShortestSimplePaths` algorithm.

For the graph

[graph.txt](https://github.com/jgrapht/jgrapht/files/4383165/graph.txt)

for `source vertes = 2`, `target vertex = 6` and `k = 100` the algorithm produces not all expected shortest paths. I\`ve made the comparison against the existing `YenKShortestPath` implementation and the implementation provided by the `networkx` library.

Expected paths:

[networkx_paths.txt](https://github.com/jgrapht/jgrapht/files/4383168/networkx_paths.txt)

[yen_paths.txt](https://github.com/jgrapht/jgrapht/files/4383169/yen_paths.txt)

Paths produces by the  `KShortestSimplePaths`:

[kssp_paths.txt](https://github.com/jgrapht/jgrapht/files/4383173/kssp_paths.txt)

In particular the `kssp_paths.txt` does not contain the ***79th*** and ***82th*** paths comparing to the correct implementations.

**Comment by SChudakov** [comment]
Java code:

**Comment by SChudakov** [comment]
```java
package org.jgrapht.alg.shortestpath;

import org.jgrapht.Graph;
import org.jgrapht.GraphPath;
import org.jgrapht.Graphs;
import org.jgrapht.alg.interfaces.KShortestPathAlgorithm;
import org.jgrapht.graph.DefaultWeightedEdge;
import org.jgrapht.graph.SimpleDirectedWeightedGraph;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

public class KSSPDemonstration {
    private static final String GRAPH_PATH = "/home/semen/drive/python/networkx-trials/data/yen/graph.txt";
    private static final String YEN_PATHS_PATH = "/home/semen/drive/python/networkx-trials/data/yen/yen_paths.txt";
    private static final String KSSP_PATHS_PATH = "/home/semen/drive/python/networkx-trials/data/yen/kssp_paths.txt";

    public static void main(String[] args) {
        Graph<Integer, DefaultWeightedEdge> graph = new SimpleDirectedWeightedGraph<>(DefaultWeightedEdge.class);
        readGraph(GRAPH_PATH, graph);

        writePaths(new YenKShortestPath<>(graph), YEN_PATHS_PATH);
        writePaths(new KShortestSimplePaths<>(graph), KSSP_PATHS_PATH);
    }

    private static void writePaths(KShortestPathAlgorithm<Integer, DefaultWeightedEdge> algorithm,
                                   String filePath) {
        Integer source = 2;
        Integer target = 6;
        List<GraphPath<Integer, DefaultWeightedEdge>> paths = algorithm.getPaths(source, target, 100);
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            for (int i = 0; i < paths.size(); ++i) {
                GraphPath<Integer, DefaultWeightedEdge> path = paths.get(i);
                writer.write(String.valueOf(i));
                writer.write(" ");
                writer.write(String.valueOf(path.getWeight()));
                writer.write(" ");
                writer.write(path.getVertexList().toString());
                writer.write("\n");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void readGraph(String filePath, Graph<Integer, DefaultWeightedEdge> graph) {
        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            reader.readLine(); // skip number of vertices
            String line;
            while ((line = reader.readLine()) != null) {
                String[] edgeData = line.split(" ");
                Graphs.addEdgeWithVertices(graph,
                        Integer.parseInt(edgeData[0]),
                        Integer.parseInt(edgeData[1]),
                        Double.parseDouble(edgeData[2]));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

```

**Comment by SChudakov** [comment]
Python code:

**Comment by SChudakov** [comment]
```python
import networkx as nx

_graph_file_path = '/home/semen/drive/python/networkx-trials/data/yen/graph.txt'
_paths_file_path = '/home/semen/drive/python/networkx-trials/data/yen/networkx_paths.txt'


def read_graph(file_path, graph):
    with open(file_path) as read_file:
        lines = read_file.readlines()
        num_of_vertices = int(lines[0])
        for i in range(num_of_vertices):
            graph.add_node(i)
        for i in range(1, len(lines)):
            data = lines[i].split()
            source = int(data[0])
            target = int(data[1])
            weight = float(data[2])
            graph.add_edge(source, target, weight=weight)
    return graph


def path_weight(graph, path):
    result = 0.0
    for i in range(len(path) - 1):
        source = path[i]
        target = path[i + 1]
        result += graph.edges[source, target]['weight']
    return result


def write_path(file_path, graph, paths):
    with open(file_path, 'w') as write_file:
        for i, path in enumerate(paths):
            write_file.write(str(i))
            write_file.write(' ')
            write_file.write(str(path_weight(graph, path)))
            write_file.write(' ')
            write_file.write(str(path))
            write_file.write('\n')


if __name__ == '__main__':
    graph = nx.DiGraph()
    source = 2
    target = 6
    read_graph(_graph_file_path, graph)
    paths = list(nx.shortest_simple_paths(graph, source, target, 'weight'))
    write_path(_paths_file_path, graph, paths)

```

**Comment by SChudakov** [comment]
Note: if provide `k = Integer.MAX_VALUE` for `KShortestSimplePaths` the bug disappears.

**Comment by SChudakov** [comment]
**Bug summary**

The algorithm is a modification of the Dijkstra\`s algorithm, which is originally designed for **k shortest paths** problem and **not** for the **k shortest simple paths problem**. The `KShortestSimplePaths` implementation attempts to adapt the original algorithm to solving **k shortest simple paths problem**. 

The loopy variant of the algorithm is as follows. For every vertex in a graph it maintains **k** shortest paths together with edges data, which allows to restore those paths once the computation is finished. It is possible to limit the number of paths for each vertex to `k`, because by doing so the algorithm is still able to correctly compute `k` shortest paths for the `target` vertex. 

Example. `k = 1`

There are 2 shortest paths from `source` vertex to a vertex `u` in the graph `G`
```
p1 = [source, u1, u2, v]
p2 = [source, u3, u4, v]

u1, u2, u3 and u4 are all unique

weight(p1) <= weight(p2)
```
If `v` is connected to `target`, we can build the shortest path from `source` to `target` by combining
`p1` with the shortest path from `u` to `target`, because we are not limited to shortest **simple** paths between `source` and `target`. 
 
If `v` is not connected to `target`, then `p1` and `p2` will not be parts of any shortest path form `source` to `target`.

Therefore we can safely limit the number of paths we maintain for each vertex to `k`.

The `KShortestSimplePaths` proposes the following adaptation for this algorithm to solve the k shortest **simple** paths problem. It still limits the number of shortest paths for each vertex to `k`. And for each such shortest paths it checks, that having a partial path `p` from `source` to current vertex `u` (`p1` is such partial path in previous example) it is possible to extend it with a spur path from `u` to `target` such that the combined path is simple. This is achieved by masking the partial path and checking that current vertex is connected to the `target`. The check for connectivity is delegated to the `ConnectivityInspector`, which makes it invalid for directed graphs. 

There is also a problem with maintaining only `k` shortest paths for each vertex.

Example. `k = 1`
```
p1 = [source, u1, u2, v]
p2 = [source, u3, u4, v]

u1, u2, u3 and u4 are all unique

weight(p1) <= weight(p2)

For path p1 we mask vertices source, u1, u2  and find a spur path [v, u3, target].
For path p2 we mask vertices source, u3, u4  and find a spur path [v, u1, target].

weight([v, u3, target]) > weight([v, u1, target]) 

and 

weight([source, u1, u2, v, u3, target]) > weight([source, u3, u4, v, u1, target])
```

Therefore, when maintaining only `k` shortest simple path for each vertex we cannot build `k` shortest simple paths to the target vertex.

**Comment by SChudakov** [comment]
**Fix summary**

1. Remove the `k` parameter at all from the `RankingPathElementList` class to consider all partial paths during the computation.
2. Select top `k` computed paths in the `KShortestSimplePaths`.
3. Add differentiation for directed and undirected graphs when checking for connectivity. Perform connectivity check for directed graphs with `KosarajuStrongConnectivityInspector`.

**Comment by d-michail** [comment]
Some relevant questions: 
  - Is there some functionality of `KShortestSimplePaths` which is not provided by our implementation of Yen's algorithm?  I guess one answer is the path validator which I guess we already have started implementing. Any others? Do both work in directed and/or undirected graphs? etc. 
  - After your proposed changes (which might indeed make it correct) what is going to happen in the performance of the algorithm? 

My point is that one possible approach is to completely remove the algorithm. It seems that this implementation is a custom algorithm which has not been peer-reviewed in some proper forum w.r.t. its correctness.

I am not really in favor of keeping algorithms which are incorrect in the library. 

@Toptachamann @jkinable @jsichi  May I ask your viewpoint on this?

**Comment by SChudakov** [comment]
`KShortestSimplePaths` is an implementation of `KShortestPathsAlgorithm` with the possibility to validate the paths via `PathValidator` as well limit the number of hops of the paths. It operates on all types of graphs. 

 `YenKShortestPaths` also implements `KShortestPathsAlgorithm` and with #891 provides `PathValidator` functionality. It would not a problem to add a limit of the number of hops to the algorithm. `YenKShortestPaths` also operates on all types of graphs. 

Regarding the performance. The fix which has been implemented in #891 sets `k = Integer.MAX_VALUE`. This makes the algorithm correct since it considers all possible partial shortest paths `[source, ..., u]` for every vertex `u` in a graph. On the other side this fix makes the algorithm very inefficient as shown on performance plots of the PR.

Therefore I am also in favor of deprecating the algorithm.

**Comment by Toptachamann** [comment]
@d-michail In the case, we will be able to add to the Yen's algorithm the functionality of limiting the number of edges in the resulting paths without significant performance impact, I vote for deprecating the `KShortestSimplePath` algorithm. The main reason is the performance gap: it doesn't make sense to offer such a slow alternative given the same functionality.

**Comment by jsichi** [comment]
I'm fine with deprecating and then removing the old one.
