### ISSUE TITLE
KShortestSimplePaths tests cleanup

### ISSUE THREAD

**Issue by SChudakov** [jgrapht/jgrapht#893]
Currently, for the `KShortestSimplePaths` there are 5 test classes:

`KSPExampleTest`
`KShortestPathCostTest`
`KShortestPathKValuesTest`
`KSPPathValidatorTest`
`KSPDiscardsValidPathsTest`

and 5 classes which represent graph instances for tests:

`KShortestPathCompleteGraph4`
`KShortestPathCompleteGraph5`
`KShortestPathCompleteGraph6`
`KSPExampleGraph`
`Picture1Graph`

This pollutes the `shortestpath` test package. Therefore my suggestion is that 
1. the test graph instances should be moved into the test classes, where they are used (or into a parent class, if they are used in multiple test classes);
2. the test classes should be merged into a single file.

What do you think @jkinable, @d-michail, @Toptachamann?

**Comment by jsichi** [comment]
I don't think it matters too much either way (1 file per fixture vs combining them all into one file).

**Comment by SChudakov** [comment]
The `KShortestSimplePaths` algorithm was deprecated and consequently removed from the codebase.  This automatically resolves the issue.
