### ISSUE TITLE
Re-adding an edge results in inconsistent internal state.

### ISSUE THREAD

**Issue by gdgib-roche** [jgrapht/jgrapht#894]
```
 * JGraphT version: 1.3.0 and 1.4.0 (probably others)
 * Java version (java -version)/platform:  Java 8, Windows
```

**Issue**

Adding an edge to a graph that already contains that edge leaves the graph data structures inconsistent.

**Steps to reproduce (small coding example)**

```
public class JGraphTIssue {
	public static class Vertex {}

	public static class Edge extends DefaultEdge {
		private static final long serialVersionUID = 1L;
	}

	@Test
	public void test() {
		DefaultDirectedGraph<Vertex, Edge> graph = new DefaultDirectedGraph<>(null, null, false);
		final Vertex a = new Vertex(), b = new Vertex(), c = new Vertex();
		final Edge x = new Edge();
		graph.addVertex(a);
		graph.addVertex(b);
		graph.addVertex(c);
		graph.addEdge(a, b, x);
		graph.addEdge(a, c, x);
		Assert.assertTrue(graph.incomingEdgesOf(b).isEmpty()); // Clearly B should have no incoming edges at this point.
	}
}
```

**Expected behaviour**

One of the following two should happen.  Either would be acceptable.

1. `b` should have no incoming edges, because the edge has been moved to `c`.  This is preferable, since it would allow the modification of a graph without changing the order of incident edges on `a`.
2. There could be an exception when trying to execute `graph.addEdge(a, c, x);` because `x` is already in the graph.  This provides less functionality, but at least leaves the graph consistent.

The problem is that right now the target of `x` is `c` but both `b` and `c` think `x` is an incoming edge.  Ouch!

**Other information**

Looks like a bug in [AbstractBashGraph](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/graph/AbstractBaseGraph.java#L258) whereby it does not remove the edge from `b` incidence list.

**Comment by jsichi** [comment]
Yeah, not great.  The second addEdge does correctly return false (per your solution 2) but the operation is not rolled back (so graph.incomingEdgesOf(c).isEmpty incorrectly returns false

**Comment by d-michail** [comment]
Nice catch!  We did some speed improvements recently, which introduced this bug (probably PR #725). Taking them back in PR #895 as being correct is more important than being fast.

**Comment by gdgib-roche** [comment]
This is the fastest fix I've ever seen from an open source project.  Well done.  Thank you so much.
