### ISSUE TITLE
Build failure in DirectedScaleFreeGraphGeneratorTest.testNoInDegreeZero

### ISSUE THREAD

**Issue by SChudakov** [jgrapht/jgrapht#898]
I\`ve experienced a build failure in `DirectedScaleFreeGraphGeneratorTest` in the `testNoInDegreeZero` method.
Build logs:
```
[ERROR] Failures: 
[ERROR]   DirectedScaleFreeGraphGeneratorTest.testNoInDegreeZero:151 expected:<0> but was:<1>
```

**Comment by d-michail** [comment]
We previously had same problems with this class (PR #832).

We have to fix the seed in the tests, as the generator is not stable enough. I already suggested that to the original author, but I guess we have to do this ourselves.

**Comment by Toptachamann** [comment]
I was able to reproduce this bug on my local PC. Specifically, with `seed = 20` in the `DirectedScaleFreeGraphGeneratorTest.testNoInDegreeZero` you can reproduce it too. 

I will submit a PR asap
