### ISSUE TITLE
Querying DAG

### ISSUE THREAD

**Issue by techmoksha** [jgrapht/jgrapht#90]
Should jgraph also have ability through API to perform queries on graphs. I am not suggesting venturing into full scale graph DB but surely an API/language based constructs could be very helpful.

**Comment by jkinable** [comment]
I'm not entire sure what functionality you are missing. I'm closing this pull request for now. If you have specific functionality that you would like to see, consider posting an enhancement issue. Or even beter: send us a pull request with your implementation :)
