### ISSUE TITLE
NPE in BoyerMyrvoldPlanarityInspector

### ISSUE THREAD

**Issue by mdeck1** [jgrapht/jgrapht#906]
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform:  1.8.0_221
```

**Issue**
BoyerMyrvoldPlanarityInspector#getKuratowskiSubdivision() throws NullPointerException

**Steps to reproduce (small coding example)**
1. Produce the Graph K11
2. Call new BoyerMyrvoldPlanarityInspector(graph).getKuratorwskitSubdivision()
3. NPE is thrown

**Expected behaviour**
A Kuratowski subdivision is returned.

**Other information**
The instance variable 'failedV' being passed to findFailedEdge() is null, which becomes a problem when stack.isEmpty() returns true.

StackTrace: 
[org.jgrapht.alg.planar.BoyerMyrvoldPlanarityInspector.findFailedEdge(BoyerMyrvoldPlanarityInspector.java:1241), org.jgrapht.alg.planar.BoyerMyrvoldPlanarityInspector.lazyExtractKuratowskiSubdivision(BoyerMyrvoldPlanarityInspector.java:1271), org.jgrapht.alg.planar.BoyerMyrvoldPlanarityInspector.getKuratowskiSubdivision(BoyerMyrvoldPlanarityInspector.java:1497), 
...

If necessary, I can upload an MVP reproduction to Github, but that probably shouldn't be necessary here.

**Comment by d-michail** [comment]
Thanks for reporting. Is the complete graph created with our own generator, or by hand? It would be useful to just include a small test method just with the code that fails.

**Comment by Toptachamann** [comment]
@mdeck1 Thanks for spotting. The problem is that the algorithm does not initialize its internal structure when you directly call `.getKuratowskiSubdivision()` (which is a bug). At the moment, you can use the algorithm safely the following way:
``` java
if(inspector.isPlanar()){
    inspector.getEmbedding();
}else{
    inspector.getKuratowskiSubdivision();
}
```

The #907 should fix this
