### ISSUE TITLE
document is not accurate:  ClusteringCoefficient

### ISSUE THREAD

**Issue by xiangfa** [jgrapht/jgrapht#915]
```
 * JGraphT version:
 * Java version (java -version)/platform:  
```

**Issue**
As in title see ` local clustering coefficient ` from the below link:
https://jgrapht.org/javadoc-1.3.0/org/jgrapht/alg/scoring/ClusteringCoefficient.html

**Steps to reproduce (small coding example)**

**Expected behaviour**

**Other information**

**Comment by jkinable** [comment]
Can you be a little more descriptive as to what exactly ain't accurate? That saves us some guessing work :).

**Comment by d-michail** [comment]
Indeed, the implementation of `local clustering coefficient` is correct, although the docs mention something else.

We should also adjust the results on whether the graph is directed or not.

**Comment by xiangfa** [comment]
Thank you for quick replies.

In the doc for clusteringCoefficient(https://jgrapht.org/javadoc-1.3.0/org/jgrapht/alg/scoring/ClusteringCoefficient.html), the described approach to compute "local clustering coefficient" is the same as the computation for betweennesscentrality (https://jgrapht.org/javadoc/org/jgrapht/alg/scoring/BetweennessCentrality.html). 

the local cluster coefficient is "given by the proportion of links between the vertices within its neighbourhood divided by the number of links that could possibly exist between them." (from wiki). The JgraphT lib also implements by this definition, not by using shortest paths. 

Could you please help check this?

**Comment by xiangfa** [comment]
> Indeed, the implementation of `local clustering coefficient` is correct, although the docs mention something else.
> 
> We should also adjust the results on whether the graph is directed or not.

Yes. The implementation is correct, but doc is inaccurate.  👍

**Comment by xiangfa** [comment]
> Can you be a little more descriptive as to what exactly ain't accurate? That saves us some guessing work :).

Sure! Sorry for the confusing. Please see my above post.
