### ISSUE TITLE
IntrusiveEdge breaks inheritance hierarchy.

### ISSUE THREAD

**Issue by ckbhatt** [jgrapht/jgrapht#916]
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform:  8
```

**Issue**
IntrusiveEdge defines source and target in default scope so extending DefaultEdge to create a custom edge does not inherit source and target.

**Steps to reproduce (small coding example)**

**Expected behaviour**
These variable should make protected so that inherited classes can access them.

**Other information**

**Comment by jsichi** [comment]
This is intentional.  These are only intended to be modified by graph internals, so making them protected would allow bad things to happen.  If you just want to access them (not modify them), you can (very cautiously) use the protected accessors getSource/getTarget in DefaultEdge.
