### ISSUE TITLE
DOTExporter attributes without double quotes not supported

### ISSUE THREAD

**Issue by szoszk** [jgrapht/jgrapht#922]
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform: 1.8.0_202 Windows 10 Version 1909
```

**Issue**
Right now when using the `DOTExporter.java`, for the attributes you have the choice between the values being in-between `" "` or `< >`.  But for example if you want to change the shape of the verticies you need an attribute with its value without double quotes (see https://renenyffenegger.ch/notes/tools/Graphviz/examples/index). This doesn't seem to be possible with the current `DOTExporter.java`.

Changing this is fairly easy, which is why I already made a proposal on how to fix this on my fork of the project: https://github.com/szoszk/jgrapht/commit/071eb9c76fdeecb9967210b24641da66c9ccd555

**Comment by d-michail** [comment]
The docs (https://www.graphviz.org/doc/info/lang.html) say that you could use quotes instead, and it should be valid dot. However, other programs might not import it correctly, so I get your point.

In the grammar, we are at the rule `ID=ID` which suggests to name `IDENTIFIER` the new type in the `AttributeType` enum. 

Could you make that change and submit a PR? Thanks!
