### ISSUE TITLE
javadoc links were all broken by move to modules

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#950]
```
 * JGraphT version: 1.5.0
```

For example, in 1.4.0, the Javadoc for the Graphs utility class was at:

https://jgrapht.org/javadoc-1.4.0/org/jgrapht/Graphs.html
 
Now it's at:

https://jgrapht.org/javadoc-1.5.0/org.jgrapht.core/org/jgrapht/Graphs.html

Why does this suck?  Because we have lots of version-independent links in our docs to things like:

https://jgrapht.org/javadoc/org/jgrapht/Graphs.html

So these all broke in the latest release.

If there's a way to omit the module from the generated URL's, or generate redirects, that would be nice, since there are probably lots of incoming links scattered across the web as well.

**Comment by jsichi** [comment]
Apparently there was a way to do this, but it's gone now:

https://bugs.openjdk.java.net/browse/JDK-8215582

**Comment by jsichi** [comment]
I'm just gonna fix the docs, oh well.

**Comment by jsichi** [comment]
Google is full of bad links now, e.g. search for "JGraphT Graph interface"

**Comment by jsichi** [comment]
Docs fixed in d62fa8f7768d2c950b89278761a067735766dadb

I'm going to see if I can think of a way to easily auto-generate redirects.

**Comment by d-michail** [comment]
Is there some `rewrite` plugin for jekyll?

**Comment by jsichi** [comment]
There's jekyll-redirect-from, but it's designed for redirecting individual posts, not en masse via pattern.  Also, the redirection pattern here is tricky (you can get the package-relative path from the module-relative path just by removing the module, but the other direction requires finer-grained mapping).

And .htaccess is banned as well.

So in 2c5496e5d53b86b7cbe9520069891173e50e3460 I did something crude:  just copy all the files as part of preparing the doc site, stripping the module subdirectories.  In case of overlap, it'll be arbitrary which one gets chosen, but I don't think there's any.

This at least avoids the 404 and returns the page, but the rendering is shit because all the links to stylesheets, javascript, etc are relative paths which break.

Locally, I tried copying to a "combined" directory (to preserve the depth) and then adding a symlink to achieve the level-skipping redirect, but it doesn't help, since the relative paths get expanded with respect to the symlink, not to the real file location.  Plus I'm scared from what I'm reading about symlinks plus jekyll plus github pages.

There's a super ugly solution involving copying all the css/js up a level as well, but yuck.  I'll see if I can come up with anything better.

BTW @jkinable remember when you wrote "that's very rare that a bug fixes itself" about #884?  Well, this breakage is karma reminding us that TANSTAAFL.

**Comment by jsichi** [comment]
A little script to autogenerate a big ol' tree of redirect files for jekyll-redirect-from would probably be the best way to go.

**Comment by d-michail** [comment]
Any chance we can include a 'latest' symlink (directory) and run jekyll with `JEKYLL_ENV=production`?  Just a random suggestion, I am pretty sure it was the first thing you considered.

**Comment by jsichi** [comment]
Well, the problem isn't our versioning (we already deal with that as part
of our release process).  The problem is the reorganization of the javadoc
file tree due to the changes they made when modules were introduced.

**Comment by jsichi** [comment]
I wrote the little script, yet another piece of bash that will surely come back to haunt me in a couple of years or sooner.  But for now, all is well.

63421c0945e0f6b416538006c2b0d44e6c2ff7ed
