### ISSUE TITLE
edge iterators

### ISSUE THREAD

**Issue by d-michail** [jgrapht/jgrapht#965]
We currently have vertex iterators, such as bfs, dfs, etc. It makes sense to also have edge iterators with the same functionality.  Any ideas on how to accomplice this?

**Comment by jkinable** [comment]
What do you have in mind? I'm not sure what you are looking for. I'm not aware of edge iteration algorithms in the context of graphs. The bfs and dfs iteration algorithms already return the edge through which a node is visited.

**Comment by d-michail** [comment]
You are right, probably not needed.  I was thinking that all iterators should support this.
