### ISSUE TITLE
Maven javadoc does not produces documentation for a new package. 

### ISSUE THREAD

**Issue by SChudakov** [jgrapht/jgrapht#974]
I\`ve recently opened a PR with an implementation of ZhangShasha algorithm. However when I run the `mvn javadoc:aggregate` command to produce HTML documentation the `target/site/apidocs/org.jgrapht.core/org/jgrapht/alg/` folder does not contain the `similarity` package with the corresponding HTML documentation file. Is this because of the newly introduced modularity?

**Comment by d-michail** [comment]
You probably need to also export it in the [module-info](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/module-info.java). There is one more level now where things get exported or not. You can even 
disable reflection.

**Comment by SChudakov** [comment]
Now it works. Thanks!
