### ISSUE TITLE
Maven build failure: 'class file has wrong version 55.0, should be 52.0'

### ISSUE THREAD

**Issue by bissim** [jgrapht/jgrapht#975]
```
 * JGraphT version: 1.5.0
 * Java version (java -version)/platform:  1.8
```

I'm trying to automate the release process for a library of mine that is based on JGraphT. Both in Travis CI and in GitHub Actions, however, I'm bumping against this build failure:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/runner/work/FLY-graph/FLY-graph/java/src/main/java/isislab/fly/Graph.java:[16,36] cannot access org.jgrapht.alg.connectivity.ConnectivityInspector
  bad class file: /home/runner/.m2/repository/org/jgrapht/jgrapht-core/1.5.0/jgrapht-core-1.5.0.jar(org/jgrapht/alg/connectivity/ConnectivityInspector.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.057 s
[INFO] Finished at: 2020-08-04T15:02:04Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project fly-graph: Compilation failure
[ERROR] /home/runner/work/FLY-graph/FLY-graph/java/src/main/java/isislab/fly/Graph.java:[16,36] cannot access org.jgrapht.alg.connectivity.ConnectivityInspector
```

[Here](https://github.com/bissim/FLY-graph/blob/master/java/pom.xml) is my project POM.

Moreover, I suspect `ConnectivityInspector` not to be the only class that may cause this problem.

By the way, this failure are occurring since 1.4.1-SNAPSHOT.

**Comment by jkinable** [comment]
In 1.4.1-SNAPSHOT and 1.5.0 we've upgraded the Java version to version 11. Could you try whether you see this error when you upgrade your java from 1.8 to 11?

**Comment by bissim** [comment]
Hello @jkinable,
Thank you for your prompt answer.

I've set an environment matrix for Travis CI in order to test both on Java 8 and on Java 11 and indeed building succeeds for Java 11, without changing POM though.

**Comment by jkinable** [comment]
I'm not sure how the Travis CI environment matrix works w.r.t. the POM. Since jgrapht 1.5.0 and beyond require at least Java 11, I'd recommend you use Java 11 in your project. Alternatively, if you prefer to stick to 1.8, you would need to use jgrapht 1.4 or lower. To set Java 11 in your project:
 ```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.0</version>
    <configuration>
        <release>11</release>
    </configuration>
</plugin>
```
I presume the issue has been resolved, so I will close it. Feel free to re-open if there's still some problem.
