### ISSUE TITLE
FRLayoutAlgorithm2D  has divide by 0 bug

### ISSUE THREAD

**Issue by rlbns** [jgrapht/jgrapht#978]
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform:  8
```

**Issue**
When using FRLayoutAlgorithm2D with an initializer that provides identical locations for 2 vertexes, a divide by 0 error occurs. Specifically, in calculateRepulsiveForces() deltaLen is calculated to be 0.

When this occurs the next line causes NaN values to be created for x and y values as follows:
Point2D dispContribution = Points.scalarMultiply(delta, repulsiveForce(deltaLen) / deltaLen)

**Steps to reproduce (small coding example)**
Use an initializer and supply identical points for >1 vertexes.

**Expected behaviour**
No error.

**Other information**
New user - awesome library, thanks for supporting it.

**Comment by d-michail** [comment]
Added a small fix. Consider testing and providing feedback.

**Comment by rlbns** [comment]
Can't test unfortunately - stuck on java 8 / JGraphT 1.4.0
