### ISSUE TITLE
FRLayoutAlgorithm2D has no-edge vertex bug

### ISSUE THREAD

**Issue by rlbns** [jgrapht/jgrapht#980]
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform:  8
```

**Issue**
FRLayoutAlgorithm2D causes a null pointer exception when a vertex with no edges is processed. The problem is between calculateRepulsiveForces() and calculateAttractiveForces(). The former drives off graph.vertexSet() whereas the later drives off graph.edgeSet() - both return a map which are used together as follows:

Point2D vDisp = Points.add(repulsiveDisp.get(v), attractiveDisp.get(v));

When a vertex has no edges the attractiveDisp map does not have an entry for it and the above line of code results in a NullPointerException.

**Steps to reproduce (small coding example)**
Layout a graph with FRLayoutAlgorithm2D that has a vertex with no edges.

**Expected behaviour**
No error.

**Other information**

**Comment by d-michail** [comment]
Thanks for reporting. Fixed this in the same PR.
