### ISSUE TITLE
Duplicate edges led to an unexpected number of triangles

### ISSUE THREAD

**Issue by FlorentinD** [jgrapht/jgrapht#981]
```
 * JGraphT version: 1.5.0
 * Java version (java -version)/platform:  openjdk 11.0.7/ Ubuntu
```

**Issue**
GraphMetrics.getNumberOfTriangles sometimes returns the wrong count.
It does return correct ones in many other examples I tried.

**Steps to reproduce (small coding example)**
* EdgeList:
```
0,1
1,2
0,3
1,3
2,5
3,5
4,5
1,6
2,6
1,7
2,7
3,7
4,7
1,8
2,8
2,9
1,10
7,10
1,11
2,11
2,12
3,13
4,13
1,15
6,15
9,15
1,16
4,16
11,16
1,18
2,18
1,19
3,19
6,19
1,20
2,20
2,21
3,21
3,22
5,22
10,22
3,23
19,23
1,24
2,24
```

* Code (need to 
```
int nodeCount = 25;
SparseIntUndirectedGraph graph = new SparseIntUndirectedGraph(nodeCount, edges);
// JGraphT finds 34 Triangles
assertEquals(16, GraphMetrics.getNumberOfTriangles(graph));
```

**Expected behaviour**

* 16 expected Triangles

```
Triangle{0, 1, 3}
Triangle{1, 2, 6}
Triangle{1, 2, 7}
Triangle{1, 2, 8}
Triangle{1, 2, 11}
Triangle{1, 2, 18}
Triangle{1, 2, 20}
Triangle{1, 2, 24}
Triangle{1, 3, 7}
Triangle{1, 3, 19}
Triangle{1, 6, 15}
Triangle{1, 6, 19}
Triangle{1, 7, 10}
Triangle{1, 11, 16}
Triangle{3, 5, 22}
Triangle{3, 19, 23}
```

**Other information**

I am sorry, that I couldn't break this down any further, this finding is based on a randomly generated graph.
As a starting point, you could print the Triangles you found and assert, that they are really triangles.

**Comment by d-michail** [comment]
Thanks for reporting. We will have a look.

Does the method `naiveCountTriangles` return the correct number?

**Comment by FlorentinD** [comment]
Unfortunately the method is not public so I cannot test it in my project.
When I find the time, I will try it out.

**Comment by d-michail** [comment]
I just tested your example but cannot reproduce the issue. I am running with the master branch, using the following code: 

```
    @Test
    public void testCountTriangles()
    {
        int[][] allEdges = { { 0, 1 }, { 1, 2 }, { 0, 3 }, { 1, 3 }, { 2, 5 }, { 3, 5 }, { 4, 5 },
            { 1, 6 }, { 2, 6 }, { 1, 7 }, { 2, 7 }, { 3, 7 }, { 4, 7 }, { 1, 8 }, { 2, 8 },
            { 2, 9 }, { 1, 10 }, { 7, 10 }, { 1, 11 }, { 2, 11 }, { 2, 12 }, { 3, 13 }, { 4, 13 },
            { 1, 15 }, { 6, 15 }, { 9, 15 }, { 1, 16 }, { 4, 16 }, { 11, 16 }, { 1, 18 }, { 2, 18 },
            { 1, 19 }, { 3, 19 }, { 6, 19 }, { 1, 20 }, { 2, 20 }, { 2, 21 }, { 3, 21 }, { 3, 22 },
            { 5, 22 }, { 10, 22 }, { 3, 23 }, { 19, 23 }, { 1, 24 }, { 2, 24 } };

        List<Pair<Integer, Integer>> edges = new ArrayList<>();
        for (int[] e : allEdges) {
            edges.add(Pair.of(e[0], e[1]));
        }

        int nodeCount = 25;

        SparseIntUndirectedGraph graph = new SparseIntUndirectedGraph(nodeCount, edges);

        assertEquals(16, GraphMetrics.getNumberOfTriangles(graph));
    }
```

It outputs 16 triangles.

**Comment by FlorentinD** [comment]
Thank you for testing this!
It seems like I wrongly simplified the test.
I assumed the `SparseIntUndirectedGraph` would filter out duplicate edges. 
I guess these duplicate edges are counted as different ones? (e.g. using a Multi-Graph model)

```
    @Test
    public void wrongTCcountForDuplicateEdges() {
        int[][] allEdges = { { 0, 1 }, { 1, 2 }, { 0, 3 }, { 1, 3 }, { 2, 5 }, { 3, 5 }, { 4, 5 },
                { 1, 6 }, { 2, 6 }, { 1, 7 }, { 2, 7 }, { 3, 7 }, { 4, 7 }, { 1, 8 }, { 2, 8 },
                { 2, 9 }, { 1, 10 }, { 7, 10 }, { 1, 11 }, { 2, 11 }, { 2, 12 }, { 3, 13 }, { 4, 13 },
                { 1, 15 }, { 6, 15 }, { 9, 15 }, { 1, 16 }, { 4, 16 }, { 11, 16 }, { 1, 18 }, { 2, 18 },
                { 1, 19 }, { 3, 19 }, { 6, 19 }, { 1, 20 }, { 2, 20 }, { 2, 21 }, { 3, 21 }, { 3, 22 },
                { 5, 22 }, { 10, 22 }, { 3, 23 }, { 19, 23 }, { 1, 24 }, { 2, 24 } };

        List<Pair<Integer, Integer>> edges = new ArrayList<>();
        for (int[] e : allEdges) {
            edges.add(Pair.of(e[0], e[1]));
            edges.add(Pair.of(e[1], e[0]));
        }

        int nodeCount = 25;

        SparseIntUndirectedGraph graph = new SparseIntUndirectedGraph(nodeCount, edges);

        assertEquals(16, GraphMetrics.getNumberOfTriangles(graph));
    }
```

**Comment by d-michail** [comment]
I see the problem. It seems our implementation does not support graphs with "multiple" edges, i.e. edges which have the same endpoints. 

It is due to method `naiveCountTriangles` which is called for a subset of the vertices (the ones with high degree) and assumes that the graph does not contain multiple edges. For each triplet of vertices, it only counts one triangle, while there might be more. 

What is your expected triangle count in the above example where we add all edges twice?

**Comment by FlorentinD** [comment]
I would have expected `16`, as I thought that the duplicate edges are not considered (e.g. ignored on graph creation)

**Comment by d-michail** [comment]
If the graph has multiple edges, the correct behavior would be to count more triangles. Most of the algorithms in the library try to adjust their behavior accordingly.

Some graphs can prohibit the addition of multiple edges, but the one you are using (`SparseIntUndirectedGraph`) does not.  The solution in your case is to remove duplicates from the list before adding them to the graph. One way to do so is to sort them first and then iterate over them and remove duplicates. If you have edges such as {1,2} and {2,1} you can always first reorder the endpoints from smaller to larger.

Nevertheless, we still have a bug. Our count when taking multiple edges into account is not correct. I will have a look on how to fix this.

**Comment by FlorentinD** [comment]
I could adjust my loader, so that the triangle count now matches (by removing the duplicates as you also suggested) :+1:
