### ISSUE TITLE
JSON Importer doesn't recognize negative value without decimal point

### ISSUE THREAD

**Issue by xianfuzheng** [jgrapht/jgrapht#982]
```
 * JGraphT version: latest master branch
 * Java version (java -version)/platform:  11
```

**Issue**
Generally , JSON importer can load negative weight correct if the value has a decimal point. But if it is a simple negative value like
`
-2
-3
`
it's set to 1.0 internally.

**Steps to reproduce (small coding example)**
1) JSON sample

```
{
  "nodes": [
    {
      "id": "1"
    },
    {
      "id": "2"
    }
  ],
  "edges": [
    {
      "source": "1",
      "target": "2",
      "weight": -3
    }
  ]
}
```

2) JSON importer to load graph - from JSONImporterTest.testWeightsOnWeighted
```Graph<String,
            DefaultEdge> g = GraphTypeBuilder
                .undirected().allowingMultipleEdges(true).allowingSelfLoops(true).weighted(true)
                .vertexSupplier(SupplierUtil.createStringSupplier(1))
                .edgeSupplier(SupplierUtil.DEFAULT_EDGE_SUPPLIER).buildGraph();

        JSONImporter<String, DefaultEdge> importer = new JSONImporter<>();
        importer.importGraph(g, new StringReader(input));
```

**Expected behaviour**
Currently, the weight of the edge (1 to 2) was parsed as "1.0" , it should be   **-3**

**Other information**
No issue if we put "-3.0" in the json file.

**Comment by d-michail** [comment]
I will take a look, thanks for reporting.
