### ISSUE TITLE
Unable to instantiate GmlImporter, despite providing Vertex and Edge Providers

### ISSUE THREAD

**Issue by LahaLuhem** [jgrapht/jgrapht#985]
```
 * JGraphT version: 1.5.0
 * Java version (java -version)/platform:  11
```

**Issue**
I get a error on just a single line using code provided by @d-michail :
```java
GmlImporter<String, DefaultEdge> importer = new GmlImporter<>(vp, ep);
```
at
https://github.com/jgrapht/jgrapht/issues/644

cannot infer type arguments for GmlImporter<>
reason: cannot infer type-variable(s) V,E
(actual and formal argument lists differ in length)
where V,E are type-variables:
V extends Object declared in class GmlImporter
E extends Object declared in class GmlImporter

maybe I'm using newer libraries?

**Steps to reproduce (small coding example)**
Just have the code

**Expected behaviour**
Should not give compile-time errors

**Other information**

**Comment by d-michail** [comment]
This is not related to the library. This is a pure Java problem. You are not giving enough information to the compiler in order to deduce the types. 

Our test classes contain a lot of examples on how to use the library (see for example `jgrapht-io/src/test/java/org/jgrapht/nio/gml/GmlImporterTest.java`.

**Comment by LahaLuhem** [comment]
> This is not related to the library. This is a pure Java problem. You are not giving enough information to the compiler in order to deduce the types. 
> 
> Our test classes contain a lot of examples on how to use the library (see for example `jgrapht-io/src/test/java/org/jgrapht/nio/gml/GmlImporterTest.java`.

By default, I was using another package, namely, grapht.ext, for which the constructor is very different. On changing to grapght.io your example worked straightaway.

Thanks again
