### ISSUE TITLE
DOT Importer with different node types

### ISSUE THREAD

**Issue by Schalli1987** [jgrapht/jgrapht#987]
```
 * JGraphT version: 1.5.0
 * Java version (java -version)/platform:  11.0.8
```

**Issue**
This issue is based on #881 and #882.
With the old 1.4.0 version one was able to implement a `VertexProvider` that retrieved the label and all attributes of a node to create a Java object instance.
With the new version, it's only possible to set a `VertexFactory` that only consumes the label.
My issue is now, that my concrete Java class representing my nodes depends on the attributes, not on the label.
So how can I know, which type to instantiate by only getting the label?

**Example**
I have the following graph:
```dot
digraph g {
  "Node 1" [type="A", attributeForA="something1"];
  "Node 2" [type="B", attributeForB="anything"];
  "Node 3" [type="A", attributeForA="something2"];
}
```
And I have an `AbstractNode` class that is provided as vertex class to the graph and two concrete Node implementations `NodeA` and `NodeB`.
By using the `VertexFactory` getting only the label I can not determine, which concrete node class to create, so how is this meant to be?
There's also another questions raising: Attributes are now passed one by one, what if I need to pass multiple arguments together to the concrete node class or what about attributes used as constructor arguments for concrete nodes?

**Comment by d-michail** [comment]
Indeed with our latest version, you will have to solve this in user-code. Our new importers have separated the parsing from the graph construction. You could implement a variant of `DOTImporter` that first collects the attributes in a map and then creates the node. Just look at the code inside `DOTImporter`.

**Comment by Schalli1987** [comment]
Ok, thanks, managed to "parse" my structure using a dummy graph containing only attribute maps, collecting all attributes and convert this to the one I wanted.

**Comment by d-michail** [comment]
Yes, if you can afford the memory, that is a good solution also.
