### ISSUE TITLE
Treatment of weights in AbstractGraph's equality-related methods is misleading.

### ISSUE THREAD

**Issue by vigna** [jgrapht/jgrapht#989]
```
 * JGraphT version: 1.5
 * Java version (java -version)/platform:  java version "13.0.1" 2019-10-15 Max OS X
```

**Issue**

Treatment of weights in AbstractGraph's equality-related methods is misleading.

**Steps to reproduce (small coding example)**

```
package org.jgrapht.webgraph;

import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.jgrapht.graph.guava.MutableValueGraphAdapter;
import org.junit.jupiter.api.Test;

import com.google.common.graph.MutableValueGraph;
import com.google.common.graph.ValueGraphBuilder;


class AbstractGraphTest {

	@Test
	void testSmallWeights() {
		final MutableValueGraph<Integer, Double> g = ValueGraphBuilder.directed().build();
		g.addNode(0);
		g.addNode(1);
		g.putEdgeValue(0, 1, 1e-10);

		final MutableValueGraph<Integer, Double> h = ValueGraphBuilder.directed().build();
		h.addNode(0);
		h.addNode(1);
		h.putEdgeValue(0, 1, 1.2e-10);
		// Document or eliminate approximate test
		assertNotEquals(new MutableValueGraphAdapter<>(g, Double.valueOf(1), x -> x), new MutableValueGraphAdapter<>(h, Double.valueOf(1), x -> x));
	}

	@Test
	void testHashcode() {
		final MutableValueGraph<Integer, Double> g = ValueGraphBuilder.directed().build();
		g.addNode(0);
		g.addNode(1);
		g.putEdgeValue(0, 1, 1.);

		final MutableValueGraph<Integer, Double> h = ValueGraphBuilder.directed().build();
		h.addNode(0);
		h.addNode(1);
		h.putEdgeValue(0, 1, 1.2);
		// Use Double.doubleToLongBits() instead of casting to long
		assertNotEquals(new MutableValueGraphAdapter<>(g, Double.valueOf(1), x -> x).hashCode(), new MutableValueGraphAdapter<>(h, Double.valueOf(1), x -> x).hashCode());
	}
}
```

**Expected behaviour**

AbstractGraph should pass these two tests, as graphs with different weights should be considered different. Hardwiring a threshold for doubles in the code is very dangerous as people might have all constants below the threshold. Casting weights to long can lead to collapsing of weights.

**Comment by jsichi** [comment]
Good point.  This was broken from the get-go in the the original PR #6, where I guess code review fatigue set in.  Changing it now could potentially break some apps in mysterious ways, but there's no deprecation path available for a change like this, so we should probably just go ahead with it directly.  equals should just use Double.equals, and hashCode should just use Double.hashCode.

**Comment by vigna** [comment]
Yes, you're right, Double.hashCode() is better than Double.doubleToLongBits().

However, I'd suggest Double.compare() rather than Double.equals(), as you can avoid boxing. Moreover, Double.compare() should be intrinsified on most JVMs.

Since you're at it, I would change the multiplier in the hash code to a prime—Java strings use 31. Using 27 should cause a bit more probability of collisions than a prime.
