### ISSUE TITLE
AbstractGraph's hashCode() implementation is incoherent with equals() on weighted graphs

### ISSUE THREAD

**Issue by vigna** [jgrapht/jgrapht#991]
```
 * JGraphT version: 1.5.0
 * Java version (java -version)/platform:  java version "13.0.1" 2019-10-15 Mac OS X
```

**Issue**

AbstractGraph's hashCode() implementation is incoherent with equals() on weighted graphs.

**Steps to reproduce (small coding example)**

```
package org.jgrapht.webgraph;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.jgrapht.graph.guava.MutableGraphAdapter;
import org.jgrapht.graph.guava.MutableValueGraphAdapter;
import org.junit.jupiter.api.Test;

import com.google.common.graph.MutableValueGraph;
import com.google.common.graph.ValueGraphBuilder;

class AbstractGraphTest {
	@Test
	void testHashcodeEquals() {
		final MutableValueGraph<Integer, Double> g = ValueGraphBuilder.directed().build();
		g.addNode(0);
		g.addNode(1);
		g.putEdgeValue(0, 1, 2 + 1e-08);

		final MutableValueGraph<Integer, Double> h = ValueGraphBuilder.directed().build();
		h.addNode(0);
		h.addNode(1);
		h.putEdgeValue(0, 1, 2 - 1e-08);
		// Use Double.doubleToLongBits() instead of casting to long
		assertEquals(new MutableValueGraphAdapter<>(g, Double.valueOf(1), x -> x), new MutableValueGraphAdapter<>(h, Double.valueOf(1), x -> x));
		assertEquals(new MutableValueGraphAdapter<>(g, Double.valueOf(1), x -> x).hashCode(), new MutableValueGraphAdapter<>(h, Double.valueOf(1), x -> x).hashCode());
	}
}
```

**Expected behaviour**

If two graphs are equal, their hash codes should be equal, too. This is related to #989, but different. The problem is that the two methods use two different relations to consider weight "equal": one is an equivalence relation (casting to long) and the other one is not (difference large enough). There is no way to fix this except to remove the approximate test in equals(), as presently it does not implement an equivalence relation.

**Other information**

In the same way, it would be easy to create a test with graphs a, b, c such that a equals b, b equals c buy a does not equal c, contrarily to equals()'s contract.

**Comment by jsichi** [comment]
See my comments on #989.
